# Copyright (c) 2019 by Frédéric Hamel, All Rights Reserved.
# Copyright (c) 2019 by Marc Feeley, All Rights Reserved.

herefromlib = _pkg
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _pkg\#.scm
MODULES_SCM = _pkg.scm
MAIN_MODULES = _pkg
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
