# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/23
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 23\#.scm
MODULES_SCM = 23.scm 23.sld test.scm
MAIN_MODULES = 23
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
