#!/bin/sh
set -eu
cd "$(dirname "$0")"
cd ../include
GIT="${GIT:-git}"
version() {
    value="$($GIT describe --tag --always 2>/dev/null)"
    value="$(printf '%s' "$value" | sed -e 's/-bootstrap$//')"
    value="${value:-$PACKAGE_VERSION}"
    printf '/* Generated by stamp.sh for each build */\n'
    printf '#define ___STAMP_VERSION \"%s\"\n' "$value"
}
version >stamp.h.new
mv stamp.h.new stamp.h
