# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme
libfromhere = ..
SUBDIRS = base case-lambda char complex cxr eval file inexact lazy load process-context r5rs read repl time write
HEADERS_SCM =
MODULES_SCM =
MAIN_MODULES =
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
