# Copyright (c) 2008-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/match
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = match\#.scm match-expand\#.scm
MODULES_SCM = match.scm match-expand.scm match-test.scm
MAIN_MODULES = match match-expand
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
