(include "#.scm")

(test-eq 'alpha (string->symbol "alpha"))
(test-equal "alpha" (symbol->string 'alpha))
(test-eq #t (symbol=? 'a 'a 'a))
(test-eq #f (symbol=? 'a 'a 'b))
(test-error type-exception? (symbol=? 'a "a"))
(test-eq alpha: (string->keyword "alpha"))
(test-equal "alpha" (keyword->string alpha:))
(test-error type-exception? (symbol->string #f))
(test-error type-exception? (keyword->string 'alpha))
(test-error type-exception? (string->symbol #f))
(test-error type-exception? (string->keyword #f))
(test-eq #f (uninterned-symbol? 'a))
(test-eq #t (uninterned-symbol? (string->uninterned-symbol "a")))
(test-eq #f (uninterned-keyword? a:))
(test-eq #t (uninterned-keyword? (string->uninterned-keyword "a")))
(test-assert
 (let ((a (gensym 'temporary)) (b (gensym 'temporary)))
   (and (symbol? a) (uninterned-symbol? a) (not (eq? a b)))))
(test-eqv (symbol-hash 'alpha) (symbol-hash (string->symbol "alpha")))
(test-eqv (keyword-hash alpha:) (keyword-hash (string->keyword "alpha")))
(test-error type-exception? (symbol-hash #f))
(test-error type-exception? (keyword-hash #f))
