# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/43
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 43\#.scm
MODULES_SCM = 43.scm 43.sld test.scm
MAIN_MODULES = 43
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
