# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _hamt
libfromhere = ..
SUBDIRS = primitive-hamt
HEADERS_SCM = _hamt\#.scm
MODULES_SCM = _hamt.scm test/test.scm
MAIN_MODULES = _hamt
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
