# Copyright (c) 2019 by Frédéric Hamel, All Rights Reserved.
# Copyright (c) 2019 by Marc Feeley, All Rights Reserved.

herefromlib = _http
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _http\#.scm
MODULES_SCM = _http.scm test.scm
MAIN_MODULES = _http
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
