# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/case-lambda
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = case-lambda.sld
MAIN_MODULES = case-lambda
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
