# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _geiser
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _geiser\#.scm
MODULES_SCM = _geiser.scm
MAIN_MODULES = _geiser
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
