# Copyright (c) 2024 by Marc Feeley, All Rights Reserved.

herefromlib = _irregex
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _irregex\#.scm
MODULES_SCM = _irregex.scm _irregex.sld irregex.scm \
test/test.scm test/irregex-utils.scm test/test-irregex-from-gauche.scm \
test/test-irregex-pcre.scm test/test-irregex-scsh.scm \
test/test-irregex-utf8.scm
MAIN_MODULES = _irregex
OTHER_RCFILES = makefile check-updates.sh

include $(libfromhere)/module-common.mk
