# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/git
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = git\#.scm
MODULES_SCM = git.scm
MAIN_MODULES = git
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
