# Copyright (c) 1994-2022 by Marc Feeley, All Rights Reserved.
# Copyright (c) 2022 by Marc-André Bélanger, All Rights Reserved.

herefromlib = _ffi/js/dom
libfromhere = ../../..
SUBDIRS =
HEADERS_SCM = dom\#.scm
MODULES_SCM = dom.scm
MAIN_MODULES = dom
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
