# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/6
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 6\#.scm
MODULES_SCM = 6.scm 6.sld test/test.scm
MAIN_MODULES = 6
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
