# Copyright (c) 1994-2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/14
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 14\#.scm
MODULES_SCM = 14.scm 14.sld test/test.scm
MAIN_MODULES = 14
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
