# Copyright (c) 1994-2023 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/19
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 19\#.scm
MODULES_SCM = 19.scm 19.sld test/test.scm
MAIN_MODULES = 19
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
