# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/define-library
libfromhere = ../..
SUBDIRS =

HEADERS_SCM = define-library\#.scm define-library-expand\#.scm

MODULES_SCM = define-library.scm define-library-expand.scm define-library-test.scm \
              syntaxboot.scm syntaxcasexformboot.scm syntaxcasexform.scm syntaxcommon.scm \
              syntaxpattern.scm syntaxrulesxform.scm syntax.scm syntaxtemplate.scm \
              syntaxxformboot.scm syntaxxform.scm withsyntaxboot.scm

MAIN_MODULES = define-library define-library-expand

OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
