# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/random
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = random\#.scm
MODULES_SCM = random.scm random.sld
MAIN_MODULES = random
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
