# Copyright (c) 2024 by Marc Feeley, All Rights Reserved.

herefromlib = _csv
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _csv\#.scm
MODULES_SCM = _csv.scm _csv.sld test/test.scm
MAIN_MODULES = _csv
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
