# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit
libfromhere = ..
SUBDIRS = git pkg tar hamt http digest define-library uri zlib test match geiser
HEADERS_SCM = gambit\#.scm
MODULES_SCM = gambit.scm
MAIN_MODULES =
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
