# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit
libfromhere = ..
SUBDIRS =
HEADERS_SCM = gambit\#.scm
MODULES_SCM = gambit.scm
MAIN_MODULES = gambit
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
