# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit
libfromhere = ..
SUBDIRS = prim
HEADERS_SCM = gambit\#.scm
MODULES_SCM = gambit.scm gambit.sld
MAIN_MODULES = gambit
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
