# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _define-library
libfromhere = ..
SUBDIRS =

HEADERS_SCM = _define-library\#.scm define-library-expand\#.scm

MODULES_SCM = _define-library.scm define-library-expand.scm debug.scm test.scm

MAIN_MODULES = _define-library define-library-expand debug

OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
