# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _define-library
libfromhere = ..
SUBDIRS =

HEADERS_SCM = _define-library\#.scm define-library-expand\#.scm

MODULES_SCM = _define-library.scm define-library-expand.scm test.scm \
              syntaxboot.scm syntaxcasexformboot.scm syntaxcasexform.scm syntaxcommon.scm \
              syntaxpattern.scm syntaxrulesxform.scm syntax.scm syntaxtemplate.scm \
              syntaxxformboot.scm syntaxxform.scm withsyntaxboot.scm

MAIN_MODULES = _define-library define-library-expand

OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
