# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/hamt
libfromhere = ../..
SUBDIRS = primitive-hamt
HEADERS_SCM = hamt\#.scm
MODULES_SCM = hamt.scm
MAIN_MODULES = hamt
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
