(include "#.scm")

(define (caught thunk) (with-exception-catcher (lambda (e) e) thunk))
(define-type-of-thread uninitialized-test-thread)
(define uninitialized (make-uninitialized-test-thread))
(define initialized (make-thread list))
(define finished (thread-start! (make-thread list)))
(thread-join! finished 10)
(define killed (make-thread list))
(thread-terminate! killed)
(define failed (thread-start! (make-thread (lambda () (raise 'failure)))))
(define waiting (thread-start! (make-thread (lambda () (thread-receive 30 'expired)))))

(let ((e (caught (lambda () (thread-start! uninitialized)))))
  (test-eq #t (uninitialized-thread-exception? e))
  (test-eq #f (uninitialized-thread-exception? #f))
  (test-eq thread-start! (uninitialized-thread-exception-procedure e))
  (test-equal (list uninitialized) (uninitialized-thread-exception-arguments e)))

(let ((e (caught (lambda () (thread-init! initialized list)))))
  (test-eq #t (initialized-thread-exception? e))
  (test-eq #f (initialized-thread-exception? #f))
  (test-eq thread-init! (initialized-thread-exception-procedure e))
  (test-equal (list initialized list) (initialized-thread-exception-arguments e)))

(let ((e (caught (lambda () (thread-interrupt! initialized)))))
  (test-eq #t (inactive-thread-exception? e))
  (test-eq #f (inactive-thread-exception? #f))
  (test-eq thread-interrupt! (inactive-thread-exception-procedure e))
  (test-equal (list initialized) (inactive-thread-exception-arguments e)))

(let ((e (caught (lambda () (thread-start! finished)))))
  (test-eq #t (started-thread-exception? e))
  (test-eq #f (started-thread-exception? #f))
  (test-eq thread-start! (started-thread-exception-procedure e))
  (test-equal (list finished) (started-thread-exception-arguments e)))

(let ((e (caught (lambda () (thread-join! killed)))))
  (test-eq #t (terminated-thread-exception? e))
  (test-eq #f (terminated-thread-exception? #f))
  (test-eq thread-join! (terminated-thread-exception-procedure e))
  (test-equal (list killed) (terminated-thread-exception-arguments e)))

(let ((e (caught (lambda () (thread-join! failed 10)))))
  (test-eq #t (uncaught-exception? e))
  (test-eq #f (uncaught-exception? #f))
  (test-eq thread-join! (uncaught-exception-procedure e))
  (test-equal (list failed 10) (uncaught-exception-arguments e))
  (test-eq 'failure (uncaught-exception-reason e)))

(let ((e (caught (lambda () (thread-join! waiting 0)))))
  (test-eq #t (join-timeout-exception? e))
  (test-eq #f (join-timeout-exception? #f))
  (test-eq thread-join! (join-timeout-exception-procedure e))
  (test-equal (list waiting 0) (join-timeout-exception-arguments e)))

(thread-terminate! waiting)
(test-equal '(#t #f #t (0))
 (thread-join!
  (thread-start!
   (make-thread
    (lambda ()
      (let ((e (caught (lambda () (thread-receive 0)))))
        (list (mailbox-receive-timeout-exception? e)
              (mailbox-receive-timeout-exception? #f)
              (eq? thread-receive (mailbox-receive-timeout-exception-procedure e))
              (mailbox-receive-timeout-exception-arguments e))))))
  10 'timed-out))

(let* ((m (make-mutex))
       (owner (thread-start! (make-thread (lambda () (mutex-lock! m))))))
  (thread-join! owner 10)
  (let ((e (caught (lambda () (mutex-lock! m 10)))))
    (test-eq #t (abandoned-mutex-exception? e))
    (test-eq #f (abandoned-mutex-exception? #f)))
  (mutex-unlock! m))
