# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/load
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = load.sld
MAIN_MODULES = load
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
