# Copyright (c) 2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/124
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = 124.scm 124.sld test.scm
MAIN_MODULES = 124
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
