# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/base
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = base.sld
MAIN_MODULES = base
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
