# Copyright (c) 1994-2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/13
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 13\#.scm
MODULES_SCM = 13.scm 13.sld test/test.scm
MAIN_MODULES = 13
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
