# Copyright (c) 1994-2021 by Marc Feeley, All Rights Reserved.

herefromlib = _six
libfromhere = ..
SUBDIRS =

HEADERS_SCM = js\#.scm python\#.scm six-expand\#.scm

MODULES_SCM = js.scm js.sld python.scm python.sld six-expand.scm test/test.scm

MAIN_MODULES = js python six-expand

OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
