(include "#.scm")

(test-equal 42 42)
(test-equal #t #t)
(test-equal #f #f)
(test-equal #\x #\x)
(test-equal "abc" "abc")
(test-equal 'hello 'hello)
(test-equal '() '())
(test-equal '(1 2 3) '(1 2 3))
(test-equal '#(1 2 3) '#(1 2 3))
