# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = srfi
libfromhere = ..
SUBDIRS = 0 4 6 8 9 23 27 28 64 69 132
HEADERS_SCM =
MODULES_SCM =
MAIN_MODULES =
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
