# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/41
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 41\#.scm
MODULES_SCM = 41.scm 41.sld test/test.scm
MAIN_MODULES = 41
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
