# Copyright (c) 2020-2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/193
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 193\#.scm
MODULES_SCM = 193.scm 193.sld test/test.scm
MAIN_MODULES = 193
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
