# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/r5rs
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = r5rs.sld
MAIN_MODULES = r5rs
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
