# Copyright (c) 2022 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/48
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 48\#.scm
MODULES_SCM = 48.scm 48.sld test/test.scm
MAIN_MODULES = 48
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
