# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _tar
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _tar\#.scm
MODULES_SCM = _tar.scm
MAIN_MODULES = _tar
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
