# Copyright (c) 2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/111
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 111\#.scm
MODULES_SCM = 111.scm 111.sld test/test.scm
MAIN_MODULES = 111
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
