# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/inexact
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = inexact.sld
MAIN_MODULES = inexact
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
