# Copyright (c) 1994-2022 by Marc Feeley, All Rights Reserved.

herefromlib = srfi
libfromhere = ..
SUBDIRS = 231 179 132 41 158 69 \
0 1 2 4 5 6 8 9 13 14 23 26 27 28 31 33 42 45 48 64 111 124 141 151 193 219
HEADERS_SCM =
MODULES_SCM =
MAIN_MODULES =
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
