# Copyright (c) 1994-2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi
libfromhere = ..
SUBDIRS = 179 132 41 158 69 \
0 1 2 4 6 8 9 13 14 23 26 27 28 31 33 45 64 124 193 219
HEADERS_SCM =
MODULES_SCM =
MAIN_MODULES =
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
