(include "#.scm")

;; Character ordering is by Unicode scalar value. Case-insensitive comparison
;; uses simple case folding, including the two lowercase forms of Greek sigma.

(test-eq #t (char? #\a))
(test-eq #f (char? "a"))
(test-eq #f (char? 97))
(test-eqv 97 (char->integer #\a))
(test-eqv #x1f642 (char->integer #\x1f642))
(test-eqv #\a (integer->char 97))
(test-eqv #\x10ffff (integer->char #x10ffff))
(test-error range-exception? (integer->char -1))
(test-error range-exception? (integer->char #x110000))
(test-error range-exception? (integer->char #xd800))
(test-error range-exception? (integer->char #xdfff))
(test-error type-exception? (integer->char #f))
(test-error type-exception? (char->integer "a"))

(test-eq #t (char=? #\a #\a #\a))
(test-eq #f (char=? #\a #\a #\b))
(test-eq #t (char<? #\a #\b #\c))
(test-eq #f (char<? #\a #\b #\a))
(test-eq #f (char<? #\a #\a))
(test-eq #t (char>? #\c #\b #\a))
(test-eq #f (char>? #\c #\b #\c))
(test-eq #f (char>? #\a #\a))
(test-eq #t (char<=? #\a #\a #\b))
(test-eq #f (char<=? #\a #\b #\a))
(test-eq #t (char>=? #\b #\b #\a))
(test-eq #f (char>=? #\b #\a #\b))
(test-eq #t (char<? #\x7f #\x80 #\x100 #\x1f642))

(test-eq #t (char-ci=? #\a #\A #\a))
(test-eq #f (char-ci=? #\a #\A #\b))
(test-eq #t (char-ci=? #\x3a3 #\x3c3 #\x3c2))
(test-eq #t (char-ci<? #\a #\B #\c))
(test-eq #f (char-ci<? #\a #\B #\A))
(test-eq #f (char-ci<? #\a #\A))
(test-eq #t (char-ci>? #\C #\b #\A))
(test-eq #f (char-ci>? #\C #\b #\C))
(test-eq #f (char-ci>? #\a #\A))
(test-eq #t (char-ci<=? #\a #\A #\b))
(test-eq #f (char-ci<=? #\a #\B #\a))
(test-eq #t (char-ci>=? #\B #\b #\a))
(test-eq #f (char-ci>=? #\B #\a #\B))
(test-error type-exception? (char=? #\a "a"))
(test-error type-exception? (char<? #\a 98))
(test-error type-exception? (char>? #\a #f))
(test-error type-exception? (char<=? #\a 'a))
(test-error type-exception? (char>=? #\a '()))
(test-error type-exception? (char-ci=? #\a "a"))
(test-error type-exception? (char-ci<? #\a 98))
(test-error type-exception? (char-ci>? #\a #f))
(test-error type-exception? (char-ci<=? #\a 'a))
(test-error type-exception? (char-ci>=? #\a '()))

;; Positive and negative classifications include non-ASCII characters.

(test-eq #t (char-alphabetic? #\A))
(test-eq #t (char-alphabetic? #\x3bb))
(test-eq #f (char-alphabetic? #\7))
(test-eq #t (char-numeric? #\7))
(test-eq #t (char-numeric? #\x663))
(test-eq #f (char-numeric? #\A))
(test-eq #t (char-whitespace? #\space))
(test-eq #t (char-whitespace? #\newline))
(test-eq #t (char-whitespace? #\x2003))
(test-eq #f (char-whitespace? #\a))
(test-eq #t (char-upper-case? #\A))
(test-eq #t (char-upper-case? #\x3a3))
(test-eq #f (char-upper-case? #\a))
(test-eq #f (char-upper-case? #\7))
(test-eq #t (char-lower-case? #\a))
(test-eq #t (char-lower-case? #\x3c3))
(test-eq #f (char-lower-case? #\A))
(test-eq #f (char-lower-case? #\7))
(test-eqv #\A (char-upcase #\a))
(test-eqv #\x3a3 (char-upcase #\x3c2))
(test-eqv #\7 (char-upcase #\7))
(test-eqv #\a (char-downcase #\A))
(test-eqv #\x3c3 (char-downcase #\x3a3))
(test-eqv #\7 (char-downcase #\7))
(test-eqv #\a (char-foldcase #\A))
(test-eqv #\x3c3 (char-foldcase #\x3c2))
(test-eqv #\7 (char-foldcase #\7))
(test-eqv 7 (digit-value #\7))
(test-eqv 3 (digit-value #\x663))
(test-eq #f (digit-value #\a))
(test-error type-exception? (char-alphabetic? "a"))
(test-error type-exception? (char-numeric? 7))
(test-error type-exception? (char-whitespace? #f))
(test-error type-exception? (char-upper-case? 'a))
(test-error type-exception? (char-lower-case? '()))
(test-error type-exception? (char-upcase "a"))
(test-error type-exception? (char-downcase "A"))
(test-error type-exception? (char-foldcase "A"))
(test-error type-exception? (digit-value 7))

(test-assert
 (let ((set (char-set #\a)))
   (let ((result (string->char-set! "bba" set)))
     (char-set= result (char-set #\a #\b)))))
