(include "#.scm")

(test-eqv #\a (char-downcase #\A))
(test-eq #t (char? #\a))
(test-eq #f (char? 1))
(test-eq #t (char-alphabetic? #\a))
(test-eq #f (char-alphabetic? #\0))
(test-eq #t (char-numeric? #\0))
(test-eq #f (char-numeric? #\a))
(test-eq #t (char-whitespace? #\space))
(test-eq #f (char-whitespace? #\a))
(test-eq #t (char-ci=? #\a #\A))
(test-eq #f (char-ci=? #\a #\b))
(test-eq #t (char-ci<? #\a #\b))
(test-eq #f (char-ci<? #\a #\A))
(test-eq #t (char-ci>? #\b #\a))
(test-eq #t (char-ci<=? #\a #\A))
(test-eqv #\a (char-foldcase #\A))
(test-eqv #\A (char-upcase #\a))
(test-eq #t (char-lower-case? #\a))
(test-eq #f (char-lower-case? #\A))
(test-eq #t (char-upper-case? #\A))
(test-eq #f (char-upper-case? #\a))
(test-error-tail type-exception? (char-downcase 1))
(test-error-tail type-exception? (char-alphabetic? 1))
(test-error-tail type-exception? (char-ci=? #\a 1))
(test-error-tail type-exception? (char-upcase 1))
(test-error-tail type-exception? (char-lower-case? 1))
(test-error-tail type-exception? (char-upper-case? 1))
