(include "#.scm")

(test-eq #t (string-prefix? "ab" "abracadabra"))
(test-eq #f (string-prefix? "ba" "abracadabra"))
(test-eq #t (string-suffix? "bra" "abracadabra"))
(test-eq #f (string-suffix? "abr" "abracadabra"))
(test-eq #t (string-prefix-ci? "Ab" "abracadabra"))
(test-eq #t (string-suffix-ci? "Bra" "abracadabra"))
(test-eqv 2 (string-prefix-length "abcd" "abracadabra"))
(test-eqv 2 (string-prefix-length-ci "Abcd" "abracadabra"))
(test-eqv 2 (string-suffix-length "extra" "abracadabra"))
(test-eqv 2 (string-suffix-length-ci "extrA" "abracadabra"))
(test-eq #t (string-ci=? "Ab" "ab"))
(test-eq #f (string-ci=? "ab" "cd"))
(test-equal "AB" (string-map char-upcase "ab"))
(test-eqv 2
  (let ((n 0))
    (string-for-each (lambda (c) (set! n (+ n 1))) "ab")
    n))
(test-error-tail type-exception? (string-prefix? 1 "ab"))
(test-error-tail type-exception? (string-suffix? "ab" 1))
(test-error-tail type-exception? (string-prefix-ci? 1 "ab"))
(test-error-tail type-exception? (string-suffix-ci? "ab" 1))
