;;;============================================================================

;;; File: "exception-gambit#.scm"

;;; Copyright (c) 1994-2022 by Marc Feeley, All Rights Reserved.

;;;============================================================================

;;; Exception operations in Gambit.

(##namespace ("##"

(abort unimplemented#abort)
(cfun-conversion-exception-arguments unimplemented#cfun-conversion-exception-arguments)
(cfun-conversion-exception-code unimplemented#cfun-conversion-exception-code)
(cfun-conversion-exception-message unimplemented#cfun-conversion-exception-message)
(cfun-conversion-exception-procedure unimplemented#cfun-conversion-exception-procedure)
(cfun-conversion-exception? unimplemented#cfun-conversion-exception?)
(current-exception-handler unimplemented#current-exception-handler)
(datum-parsing-exception-kind unimplemented#datum-parsing-exception-kind)
(datum-parsing-exception-parameters unimplemented#datum-parsing-exception-parameters)
(datum-parsing-exception-readenv unimplemented#datum-parsing-exception-readenv)
(datum-parsing-exception? unimplemented#datum-parsing-exception?)
(divide-by-zero-exception-arguments unimplemented#divide-by-zero-exception-arguments)
(divide-by-zero-exception-procedure unimplemented#divide-by-zero-exception-procedure)
(divide-by-zero-exception? unimplemented#divide-by-zero-exception?)

error

(error-exception-message unimplemented#error-exception-message)
(error-exception-parameters unimplemented#error-exception-parameters)
(error-exception? unimplemented#error-exception?)
(error-object-irritants unimplemented#error-object-irritants)
(error-object-message unimplemented#error-object-message)
(error-object? unimplemented#error-object?)
(expression-parsing-exception-kind unimplemented#expression-parsing-exception-kind)
(expression-parsing-exception-parameters unimplemented#expression-parsing-exception-parameters)
(expression-parsing-exception-source unimplemented#expression-parsing-exception-source)
(expression-parsing-exception? unimplemented#expression-parsing-exception?)
(file-exists-exception-arguments unimplemented#file-exists-exception-arguments)
(file-exists-exception-procedure unimplemented#file-exists-exception-procedure)
(file-exists-exception? unimplemented#file-exists-exception?)
(fixnum-overflow-exception-arguments unimplemented#fixnum-overflow-exception-arguments)
(fixnum-overflow-exception-procedure unimplemented#fixnum-overflow-exception-procedure)
(fixnum-overflow-exception? unimplemented#fixnum-overflow-exception?)
(heap-overflow-exception? unimplemented#heap-overflow-exception?)
(invalid-hash-number-exception-arguments unimplemented#invalid-hash-number-exception-arguments)
(invalid-hash-number-exception-procedure unimplemented#invalid-hash-number-exception-procedure)
(invalid-hash-number-exception? unimplemented#invalid-hash-number-exception?)
(invalid-utf8-encoding-exception-arguments unimplemented#invalid-utf8-encoding-exception-arguments)
(invalid-utf8-encoding-exception-procedure unimplemented#invalid-utf8-encoding-exception-procedure)
(invalid-utf8-encoding-exception? unimplemented#invalid-utf8-encoding-exception?)
(keyword-expected-exception-arguments unimplemented#keyword-expected-exception-arguments)
(keyword-expected-exception-procedure unimplemented#keyword-expected-exception-procedure)
(keyword-expected-exception? unimplemented#keyword-expected-exception?)
(length-mismatch-exception-arg-id unimplemented#length-mismatch-exception-arg-id)
(length-mismatch-exception-arguments unimplemented#length-mismatch-exception-arguments)
(length-mismatch-exception-procedure unimplemented#length-mismatch-exception-procedure)
(length-mismatch-exception? unimplemented#length-mismatch-exception?)
(module-not-found-exception-arguments unimplemented#module-not-found-exception-arguments)
(module-not-found-exception-procedure unimplemented#module-not-found-exception-procedure)
(module-not-found-exception? unimplemented#module-not-found-exception?)
(multiple-c-return-exception? unimplemented#multiple-c-return-exception?)
(no-such-file-or-directory-exception-arguments unimplemented#no-such-file-or-directory-exception-arguments)
(no-such-file-or-directory-exception-procedure unimplemented#no-such-file-or-directory-exception-procedure)
(no-such-file-or-directory-exception? unimplemented#no-such-file-or-directory-exception?)
(noncontinuable-exception-reason unimplemented#noncontinuable-exception-reason)
(noncontinuable-exception? unimplemented#noncontinuable-exception?)
(nonempty-input-port-character-buffer-exception-arguments unimplemented#nonempty-input-port-character-buffer-exception-arguments)
(nonempty-input-port-character-buffer-exception-procedure unimplemented#nonempty-input-port-character-buffer-exception-procedure)
(nonempty-input-port-character-buffer-exception? unimplemented#nonempty-input-port-character-buffer-exception?)
(nonprocedure-operator-exception-arguments unimplemented#nonprocedure-operator-exception-arguments)
(nonprocedure-operator-exception-code unimplemented#nonprocedure-operator-exception-code)
(nonprocedure-operator-exception-operator unimplemented#nonprocedure-operator-exception-operator)
(nonprocedure-operator-exception-rte unimplemented#nonprocedure-operator-exception-rte)
(nonprocedure-operator-exception? unimplemented#nonprocedure-operator-exception?)
(number-of-arguments-limit-exception-arguments unimplemented#number-of-arguments-limit-exception-arguments)
(number-of-arguments-limit-exception-procedure unimplemented#number-of-arguments-limit-exception-procedure)
(number-of-arguments-limit-exception? unimplemented#number-of-arguments-limit-exception?)
(os-exception-arguments unimplemented#os-exception-arguments)
(os-exception-code unimplemented#os-exception-code)
(os-exception-message unimplemented#os-exception-message)
(os-exception-procedure unimplemented#os-exception-procedure)
(os-exception? unimplemented#os-exception?)
(permission-denied-exception-arguments unimplemented#permission-denied-exception-arguments)
(permission-denied-exception-procedure unimplemented#permission-denied-exception-procedure)
(permission-denied-exception? unimplemented#permission-denied-exception?)
(primordial-exception-handler unimplemented#primordial-exception-handler)

r7rs-raise
r7rs-raise-continuable
r7rs-with-exception-handler
raise

(range-exception-arg-id unimplemented#range-exception-arg-id)
(range-exception-arguments unimplemented#range-exception-arguments)
(range-exception-procedure unimplemented#range-exception-procedure)
(range-exception? unimplemented#range-exception?)
(rpc-remote-error-exception-arguments unimplemented#rpc-remote-error-exception-arguments)
(rpc-remote-error-exception-message unimplemented#rpc-remote-error-exception-message)
(rpc-remote-error-exception-procedure unimplemented#rpc-remote-error-exception-procedure)
(rpc-remote-error-exception? unimplemented#rpc-remote-error-exception?)
(scheduler-exception-reason unimplemented#scheduler-exception-reason)
(scheduler-exception? unimplemented#scheduler-exception?)
(sfun-conversion-exception-arguments unimplemented#sfun-conversion-exception-arguments)
(sfun-conversion-exception-code unimplemented#sfun-conversion-exception-code)
(sfun-conversion-exception-message unimplemented#sfun-conversion-exception-message)
(sfun-conversion-exception-procedure unimplemented#sfun-conversion-exception-procedure)
(sfun-conversion-exception? unimplemented#sfun-conversion-exception?)
(stack-overflow-exception? unimplemented#stack-overflow-exception?)
(type-exception-arg-id unimplemented#type-exception-arg-id)
(type-exception-arguments unimplemented#type-exception-arguments)
(type-exception-procedure unimplemented#type-exception-procedure)
(type-exception-type-id unimplemented#type-exception-type-id)
(type-exception? unimplemented#type-exception?)
(unbound-global-exception-code unimplemented#unbound-global-exception-code)
(unbound-global-exception-rte unimplemented#unbound-global-exception-rte)
(unbound-global-exception-variable unimplemented#unbound-global-exception-variable)
(unbound-global-exception? unimplemented#unbound-global-exception?)
(unbound-key-exception-arguments unimplemented#unbound-key-exception-arguments)
(unbound-key-exception-procedure unimplemented#unbound-key-exception-procedure)
(unbound-key-exception? unimplemented#unbound-key-exception?)
(unbound-os-environment-variable-exception-arguments unimplemented#unbound-os-environment-variable-exception-arguments)
(unbound-os-environment-variable-exception-procedure unimplemented#unbound-os-environment-variable-exception-procedure)
(unbound-os-environment-variable-exception? unimplemented#unbound-os-environment-variable-exception?)
(unbound-serial-number-exception-arguments unimplemented#unbound-serial-number-exception-arguments)
(unbound-serial-number-exception-procedure unimplemented#unbound-serial-number-exception-procedure)
(unbound-serial-number-exception? unimplemented#unbound-serial-number-exception?)
(uncaught-exception-arguments unimplemented#uncaught-exception-arguments)
(uncaught-exception-procedure unimplemented#uncaught-exception-procedure)
(uncaught-exception-reason unimplemented#uncaught-exception-reason)
(uncaught-exception? unimplemented#uncaught-exception?)
(unknown-keyword-argument-exception-arguments unimplemented#unknown-keyword-argument-exception-arguments)
(unknown-keyword-argument-exception-procedure unimplemented#unknown-keyword-argument-exception-procedure)
(unknown-keyword-argument-exception? unimplemented#unknown-keyword-argument-exception?)
(unterminated-process-exception-arguments unimplemented#unterminated-process-exception-arguments)
(unterminated-process-exception-procedure unimplemented#unterminated-process-exception-procedure)
(unterminated-process-exception? unimplemented#unterminated-process-exception?)

with-exception-catcher
with-exception-handler

(wrong-number-of-arguments-exception-arguments unimplemented#wrong-number-of-arguments-exception-arguments)
(wrong-number-of-arguments-exception-procedure unimplemented#wrong-number-of-arguments-exception-procedure)
(wrong-number-of-arguments-exception? unimplemented#wrong-number-of-arguments-exception?)
(wrong-number-of-values-exception-code unimplemented#wrong-number-of-values-exception-code)
(wrong-number-of-values-exception-rte unimplemented#wrong-number-of-values-exception-rte)
(wrong-number-of-values-exception-vals unimplemented#wrong-number-of-values-exception-vals)
(wrong-number-of-values-exception? unimplemented#wrong-number-of-values-exception?)
(wrong-processor-c-return-exception? unimplemented#wrong-processor-c-return-exception?)

))

;;;============================================================================
