# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/read
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = read.sld
MAIN_MODULES = read
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
