# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _digest
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _digest\#.scm
MODULES_SCM = _digest.scm test/test.scm
MAIN_MODULES = _digest
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
