# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/27
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 27\#.scm
MODULES_SCM = 27.scm 27.sld test.scm
MAIN_MODULES = 27
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
