# Copyright (c) 2020 by Bradley J. Lucier, All Rights Reserved.

herefromlib = srfi/231
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 231\#.scm
MODULES_SCM = 231.scm 231.sld generalized-arrays.scm test-arrays.scm girl.pgm test.pgm
MAIN_MODULES = 231
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
