# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/uri
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = uri\#.scm
MODULES_SCM = uri.scm
MAIN_MODULES = uri
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
