# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _uri
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _uri\#.scm
MODULES_SCM = _uri.scm test.scm
MAIN_MODULES = _uri
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
