# Copyright (c) 1994-2022 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/42
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 42\#.scm
MODULES_SCM = 42.scm 42.sld test/test.scm
MAIN_MODULES = 42
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
