# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/lazy
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = lazy.sld
MAIN_MODULES = lazy
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
