# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/tar
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = tar\#.scm
MODULES_SCM = tar.scm
MAIN_MODULES = tar
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
