# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/repl
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = repl.sld
MAIN_MODULES = repl
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
