# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = termite
libfromhere = ..
SUBDIRS = otp
HEADERS_SCM = termite\#.scm match\#.scm match-support\#.scm utils\#.scm
MODULES_SCM = termite.scm data.scm deftype.scm match.scm match-support.scm io.scm process.scm recv.scm uuid.scm utils.scm
MAIN_MODULES = termite match match-support utils
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
