# Copyright (c) 2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/33
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 33\#.scm
MODULES_SCM = 33.scm 33.sld test/test.scm
MAIN_MODULES = 33
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
