# Copyright (c) 2022 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/95
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 95\#.scm
MODULES_SCM = 95.scm 95.sld test/test.scm
MAIN_MODULES = 95
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
