# Copyright (c) 1994-2026 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/16
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 16\#.scm
MODULES_SCM = 16.scm 16.sld test/test.scm demo/demo.scm
MAIN_MODULES = 16
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
