herefromlib = srfi/26
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 26\#.scm expand\#.scm
MODULES_SCM = 26.scm expand.scm test/test.scm
MAIN_MODULES = 26 expand
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
