(include "#.scm")

;; Check portable structure and internal consistency, not host-specific values.
(test-assert (every string? (command-args)))
(test-assert (file-exists? (executable-path)))
(test-assert (every symbol? (features)))
(test-assert (memq 'gambit (features)))
(test-assert (exact-integer? (system-version)))
(test-assert (> (system-version) 0))
(test-assert (> (string-length (system-version-string)) 0))
(test-assert (every symbol? (system-type)))
(test-assert (> (string-length (system-type-string)) 0))
(test-assert (string? (configure-command-string)))
(test-assert (exact-integer? (system-stamp)))
(test-assert (> (system-stamp) 0))
(test-assert (string? (host-name)))
(test-assert
 (let ((times (process-times)))
   (and (f64vector? times) (= 3 (f64vector-length times))
        (every (lambda (x) (>= x 0)) (f64vector->list times)))))
(test-assert (>= (cpu-time) 0))
(test-assert (>= (real-time) 0))
(test-assert (string? (err-code->string 0)))
(test-assert (input-port? (repl-input-port)))
(test-assert (output-port? (repl-output-port)))
(test-assert (output-port? (repl-error-port)))
(test-eq #f (tty? (open-input-string "x")))
