# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/write
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = write.sld
MAIN_MODULES = write
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
