# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/list
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = list\#.scm
MODULES_SCM = list.scm list.sld
MAIN_MODULES = list
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
