# Copyright (c) 2019 by Frédéric Hamel, All Rights Reserved.
# Copyright (c) 2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/http
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = http\#.scm
MODULES_SCM = http.scm
MAIN_MODULES = http
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
