# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _git
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _git\#.scm
MODULES_SCM = _git.scm
MAIN_MODULES = _git
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
