(include "#.scm")

(define bool #f)

(define a0 (cons 0 1))
(define a1 (cons 2 3))
(define a2 (cons 4 5))
(define a3 (cons 6 7))
(define a4 (cons 8 9))
(define a5 (cons 10 11))
(define a6 (cons 12 13))
(define a7 (cons 14 15))
(define a8 (cons 16 17))
(define a9 (cons 18 19))
(define a10 (cons 20 21))
(define a11 (cons 22 23))
(define a12 (cons 24 25))
(define a13 (cons 26 27))
(define a14 (cons 28 29))
(define a15 (cons 30 31))

(define b0 (cons a0 a1))
(define b1 (cons a2 a3))
(define b2 (cons a4 a5))
(define b3 (cons a6 a7))
(define b4 (cons a8 a9))
(define b5 (cons a10 a11))
(define b6 (cons a12 a13))
(define b7 (cons a14 a15))

(define c0 (cons b0 b1))
(define c1 (cons b2 b3))
(define c2 (cons b4 b5))
(define c3 (cons b6 b7))

(define d0 (cons c0 c1))
(define d1 (cons c2 c3))

(define e0 (cons d0 d1))

(test-error-tail type-exception? (car bool))
(test-eqv 0 (car a0))
(test-eqv 2 (car a1))
(test-eqv 4 (car a2))
(test-eqv 6 (car a3))
(test-eqv 8 (car a4))
(test-eqv 10 (car a5))
(test-eqv 12 (car a6))
(test-eqv 14 (car a7))
(test-eqv 16 (car a8))
(test-eqv 18 (car a9))
(test-eqv 20 (car a10))
(test-eqv 22 (car a11))
(test-eqv 24 (car a12))
(test-eqv 26 (car a13))
(test-eqv 28 (car a14))
(test-eqv 30 (car a15))
(test-eq a0 (car b0))
(test-eq a2 (car b1))
(test-eq a4 (car b2))
(test-eq a6 (car b3))
(test-eq a8 (car b4))
(test-eq a10 (car b5))
(test-eq a12 (car b6))
(test-eq a14 (car b7))
(test-eq b0 (car c0))
(test-eq b2 (car c1))
(test-eq b4 (car c2))
(test-eq b6 (car c3))
(test-eq c0 (car d0))
(test-eq c2 (car d1))
(test-eq d0 (car e0))
(test-error-tail wrong-number-of-arguments-exception? (car))
(test-error-tail wrong-number-of-arguments-exception? (car a0 a0))

(test-error-tail type-exception? (cdr bool))
(test-eqv 1 (cdr a0))
(test-eqv 3 (cdr a1))
(test-eqv 5 (cdr a2))
(test-eqv 7 (cdr a3))
(test-eqv 9 (cdr a4))
(test-eqv 11 (cdr a5))
(test-eqv 13 (cdr a6))
(test-eqv 15 (cdr a7))
(test-eqv 17 (cdr a8))
(test-eqv 19 (cdr a9))
(test-eqv 21 (cdr a10))
(test-eqv 23 (cdr a11))
(test-eqv 25 (cdr a12))
(test-eqv 27 (cdr a13))
(test-eqv 29 (cdr a14))
(test-eqv 31 (cdr a15))
(test-eq a1 (cdr b0))
(test-eq a3 (cdr b1))
(test-eq a5 (cdr b2))
(test-eq a7 (cdr b3))
(test-eq a9 (cdr b4))
(test-eq a11 (cdr b5))
(test-eq a13 (cdr b6))
(test-eq a15 (cdr b7))
(test-eq b1 (cdr c0))
(test-eq b3 (cdr c1))
(test-eq b5 (cdr c2))
(test-eq b7 (cdr c3))
(test-eq c1 (cdr d0))
(test-eq c3 (cdr d1))
(test-eq d1 (cdr e0))
(test-error-tail wrong-number-of-arguments-exception? (cdr))
(test-error-tail wrong-number-of-arguments-exception? (cdr a0 a0))

(test-error-tail type-exception? (caar bool))
(test-error-tail type-exception? (caar a0))
(test-error-tail type-exception? (caar a1))
(test-error-tail type-exception? (caar a2))
(test-error-tail type-exception? (caar a3))
(test-error-tail type-exception? (caar a4))
(test-error-tail type-exception? (caar a5))
(test-error-tail type-exception? (caar a6))
(test-error-tail type-exception? (caar a7))
(test-error-tail type-exception? (caar a8))
(test-error-tail type-exception? (caar a9))
(test-error-tail type-exception? (caar a10))
(test-error-tail type-exception? (caar a11))
(test-error-tail type-exception? (caar a12))
(test-error-tail type-exception? (caar a13))
(test-error-tail type-exception? (caar a14))
(test-error-tail type-exception? (caar a15))
(test-eqv 0 (caar b0))
(test-eqv 4 (caar b1))
(test-eqv 8 (caar b2))
(test-eqv 12 (caar b3))
(test-eqv 16 (caar b4))
(test-eqv 20 (caar b5))
(test-eqv 24 (caar b6))
(test-eqv 28 (caar b7))
(test-eq a0 (caar c0))
(test-eq a4 (caar c1))
(test-eq a8 (caar c2))
(test-eq a12 (caar c3))
(test-eq b0 (caar d0))
(test-eq b4 (caar d1))
(test-eq c0 (caar e0))
(test-error-tail wrong-number-of-arguments-exception? (caar))
(test-error-tail wrong-number-of-arguments-exception? (caar a0 a0))

(test-error-tail type-exception? (cadr bool))
(test-error-tail type-exception? (cadr a0))
(test-error-tail type-exception? (cadr a1))
(test-error-tail type-exception? (cadr a2))
(test-error-tail type-exception? (cadr a3))
(test-error-tail type-exception? (cadr a4))
(test-error-tail type-exception? (cadr a5))
(test-error-tail type-exception? (cadr a6))
(test-error-tail type-exception? (cadr a7))
(test-error-tail type-exception? (cadr a8))
(test-error-tail type-exception? (cadr a9))
(test-error-tail type-exception? (cadr a10))
(test-error-tail type-exception? (cadr a11))
(test-error-tail type-exception? (cadr a12))
(test-error-tail type-exception? (cadr a13))
(test-error-tail type-exception? (cadr a14))
(test-error-tail type-exception? (cadr a15))
(test-eqv 2 (cadr b0))
(test-eqv 6 (cadr b1))
(test-eqv 10 (cadr b2))
(test-eqv 14 (cadr b3))
(test-eqv 18 (cadr b4))
(test-eqv 22 (cadr b5))
(test-eqv 26 (cadr b6))
(test-eqv 30 (cadr b7))
(test-eq a2 (cadr c0))
(test-eq a6 (cadr c1))
(test-eq a10 (cadr c2))
(test-eq a14 (cadr c3))
(test-eq b2 (cadr d0))
(test-eq b6 (cadr d1))
(test-eq c2 (cadr e0))
(test-error-tail wrong-number-of-arguments-exception? (cadr))
(test-error-tail wrong-number-of-arguments-exception? (cadr a0 a0))

(test-error-tail type-exception? (cdar bool))
(test-error-tail type-exception? (cdar a0))
(test-error-tail type-exception? (cdar a1))
(test-error-tail type-exception? (cdar a2))
(test-error-tail type-exception? (cdar a3))
(test-error-tail type-exception? (cdar a4))
(test-error-tail type-exception? (cdar a5))
(test-error-tail type-exception? (cdar a6))
(test-error-tail type-exception? (cdar a7))
(test-error-tail type-exception? (cdar a8))
(test-error-tail type-exception? (cdar a9))
(test-error-tail type-exception? (cdar a10))
(test-error-tail type-exception? (cdar a11))
(test-error-tail type-exception? (cdar a12))
(test-error-tail type-exception? (cdar a13))
(test-error-tail type-exception? (cdar a14))
(test-error-tail type-exception? (cdar a15))
(test-eqv 1 (cdar b0))
(test-eqv 5 (cdar b1))
(test-eqv 9 (cdar b2))
(test-eqv 13 (cdar b3))
(test-eqv 17 (cdar b4))
(test-eqv 21 (cdar b5))
(test-eqv 25 (cdar b6))
(test-eqv 29 (cdar b7))
(test-eq a1 (cdar c0))
(test-eq a5 (cdar c1))
(test-eq a9 (cdar c2))
(test-eq a13 (cdar c3))
(test-eq b1 (cdar d0))
(test-eq b5 (cdar d1))
(test-eq c1 (cdar e0))
(test-error-tail wrong-number-of-arguments-exception? (cdar))
(test-error-tail wrong-number-of-arguments-exception? (cdar a0 a0))

(test-error-tail type-exception? (cddr bool))
(test-error-tail type-exception? (cddr a0))
(test-error-tail type-exception? (cddr a1))
(test-error-tail type-exception? (cddr a2))
(test-error-tail type-exception? (cddr a3))
(test-error-tail type-exception? (cddr a4))
(test-error-tail type-exception? (cddr a5))
(test-error-tail type-exception? (cddr a6))
(test-error-tail type-exception? (cddr a7))
(test-error-tail type-exception? (cddr a8))
(test-error-tail type-exception? (cddr a9))
(test-error-tail type-exception? (cddr a10))
(test-error-tail type-exception? (cddr a11))
(test-error-tail type-exception? (cddr a12))
(test-error-tail type-exception? (cddr a13))
(test-error-tail type-exception? (cddr a14))
(test-error-tail type-exception? (cddr a15))
(test-eqv 3 (cddr b0))
(test-eqv 7 (cddr b1))
(test-eqv 11 (cddr b2))
(test-eqv 15 (cddr b3))
(test-eqv 19 (cddr b4))
(test-eqv 23 (cddr b5))
(test-eqv 27 (cddr b6))
(test-eqv 31 (cddr b7))
(test-eq a3 (cddr c0))
(test-eq a7 (cddr c1))
(test-eq a11 (cddr c2))
(test-eq a15 (cddr c3))
(test-eq b3 (cddr d0))
(test-eq b7 (cddr d1))
(test-eq c3 (cddr e0))
(test-error-tail wrong-number-of-arguments-exception? (cddr))
(test-error-tail wrong-number-of-arguments-exception? (cddr a0 a0))

(test-error-tail type-exception? (caaar bool))
(test-error-tail type-exception? (caaar a0))
(test-error-tail type-exception? (caaar a1))
(test-error-tail type-exception? (caaar a2))
(test-error-tail type-exception? (caaar a3))
(test-error-tail type-exception? (caaar a4))
(test-error-tail type-exception? (caaar a5))
(test-error-tail type-exception? (caaar a6))
(test-error-tail type-exception? (caaar a7))
(test-error-tail type-exception? (caaar a8))
(test-error-tail type-exception? (caaar a9))
(test-error-tail type-exception? (caaar a10))
(test-error-tail type-exception? (caaar a11))
(test-error-tail type-exception? (caaar a12))
(test-error-tail type-exception? (caaar a13))
(test-error-tail type-exception? (caaar a14))
(test-error-tail type-exception? (caaar a15))
(test-error-tail type-exception? (caaar b0))
(test-error-tail type-exception? (caaar b1))
(test-error-tail type-exception? (caaar b2))
(test-error-tail type-exception? (caaar b3))
(test-error-tail type-exception? (caaar b4))
(test-error-tail type-exception? (caaar b5))
(test-error-tail type-exception? (caaar b6))
(test-error-tail type-exception? (caaar b7))
(test-eqv 0 (caaar c0))
(test-eqv 8 (caaar c1))
(test-eqv 16 (caaar c2))
(test-eqv 24 (caaar c3))
(test-eq a0 (caaar d0))
(test-eq a8 (caaar d1))
(test-eq b0 (caaar e0))
(test-error-tail wrong-number-of-arguments-exception? (caaar))
(test-error-tail wrong-number-of-arguments-exception? (caaar a0 a0))

(test-error-tail type-exception? (caadr bool))
(test-error-tail type-exception? (caadr a0))
(test-error-tail type-exception? (caadr a1))
(test-error-tail type-exception? (caadr a2))
(test-error-tail type-exception? (caadr a3))
(test-error-tail type-exception? (caadr a4))
(test-error-tail type-exception? (caadr a5))
(test-error-tail type-exception? (caadr a6))
(test-error-tail type-exception? (caadr a7))
(test-error-tail type-exception? (caadr a8))
(test-error-tail type-exception? (caadr a9))
(test-error-tail type-exception? (caadr a10))
(test-error-tail type-exception? (caadr a11))
(test-error-tail type-exception? (caadr a12))
(test-error-tail type-exception? (caadr a13))
(test-error-tail type-exception? (caadr a14))
(test-error-tail type-exception? (caadr a15))
(test-error-tail type-exception? (caadr b0))
(test-error-tail type-exception? (caadr b1))
(test-error-tail type-exception? (caadr b2))
(test-error-tail type-exception? (caadr b3))
(test-error-tail type-exception? (caadr b4))
(test-error-tail type-exception? (caadr b5))
(test-error-tail type-exception? (caadr b6))
(test-error-tail type-exception? (caadr b7))
(test-eqv 4 (caadr c0))
(test-eqv 12 (caadr c1))
(test-eqv 20 (caadr c2))
(test-eqv 28 (caadr c3))
(test-eq a4 (caadr d0))
(test-eq a12 (caadr d1))
(test-eq b4 (caadr e0))
(test-error-tail wrong-number-of-arguments-exception? (caadr))
(test-error-tail wrong-number-of-arguments-exception? (caadr a0 a0))

(test-error-tail type-exception? (cadar bool))
(test-error-tail type-exception? (cadar a0))
(test-error-tail type-exception? (cadar a1))
(test-error-tail type-exception? (cadar a2))
(test-error-tail type-exception? (cadar a3))
(test-error-tail type-exception? (cadar a4))
(test-error-tail type-exception? (cadar a5))
(test-error-tail type-exception? (cadar a6))
(test-error-tail type-exception? (cadar a7))
(test-error-tail type-exception? (cadar a8))
(test-error-tail type-exception? (cadar a9))
(test-error-tail type-exception? (cadar a10))
(test-error-tail type-exception? (cadar a11))
(test-error-tail type-exception? (cadar a12))
(test-error-tail type-exception? (cadar a13))
(test-error-tail type-exception? (cadar a14))
(test-error-tail type-exception? (cadar a15))
(test-error-tail type-exception? (cadar b0))
(test-error-tail type-exception? (cadar b1))
(test-error-tail type-exception? (cadar b2))
(test-error-tail type-exception? (cadar b3))
(test-error-tail type-exception? (cadar b4))
(test-error-tail type-exception? (cadar b5))
(test-error-tail type-exception? (cadar b6))
(test-error-tail type-exception? (cadar b7))
(test-eqv 2 (cadar c0))
(test-eqv 10 (cadar c1))
(test-eqv 18 (cadar c2))
(test-eqv 26 (cadar c3))
(test-eq a2 (cadar d0))
(test-eq a10 (cadar d1))
(test-eq b2 (cadar e0))
(test-error-tail wrong-number-of-arguments-exception? (cadar))
(test-error-tail wrong-number-of-arguments-exception? (cadar a0 a0))

(test-error-tail type-exception? (caddr bool))
(test-error-tail type-exception? (caddr a0))
(test-error-tail type-exception? (caddr a1))
(test-error-tail type-exception? (caddr a2))
(test-error-tail type-exception? (caddr a3))
(test-error-tail type-exception? (caddr a4))
(test-error-tail type-exception? (caddr a5))
(test-error-tail type-exception? (caddr a6))
(test-error-tail type-exception? (caddr a7))
(test-error-tail type-exception? (caddr a8))
(test-error-tail type-exception? (caddr a9))
(test-error-tail type-exception? (caddr a10))
(test-error-tail type-exception? (caddr a11))
(test-error-tail type-exception? (caddr a12))
(test-error-tail type-exception? (caddr a13))
(test-error-tail type-exception? (caddr a14))
(test-error-tail type-exception? (caddr a15))
(test-error-tail type-exception? (caddr b0))
(test-error-tail type-exception? (caddr b1))
(test-error-tail type-exception? (caddr b2))
(test-error-tail type-exception? (caddr b3))
(test-error-tail type-exception? (caddr b4))
(test-error-tail type-exception? (caddr b5))
(test-error-tail type-exception? (caddr b6))
(test-error-tail type-exception? (caddr b7))
(test-eqv 6 (caddr c0))
(test-eqv 14 (caddr c1))
(test-eqv 22 (caddr c2))
(test-eqv 30 (caddr c3))
(test-eq a6 (caddr d0))
(test-eq a14 (caddr d1))
(test-eq b6 (caddr e0))
(test-error-tail wrong-number-of-arguments-exception? (caddr))
(test-error-tail wrong-number-of-arguments-exception? (caddr a0 a0))

(test-error-tail type-exception? (cdaar bool))
(test-error-tail type-exception? (cdaar a0))
(test-error-tail type-exception? (cdaar a1))
(test-error-tail type-exception? (cdaar a2))
(test-error-tail type-exception? (cdaar a3))
(test-error-tail type-exception? (cdaar a4))
(test-error-tail type-exception? (cdaar a5))
(test-error-tail type-exception? (cdaar a6))
(test-error-tail type-exception? (cdaar a7))
(test-error-tail type-exception? (cdaar a8))
(test-error-tail type-exception? (cdaar a9))
(test-error-tail type-exception? (cdaar a10))
(test-error-tail type-exception? (cdaar a11))
(test-error-tail type-exception? (cdaar a12))
(test-error-tail type-exception? (cdaar a13))
(test-error-tail type-exception? (cdaar a14))
(test-error-tail type-exception? (cdaar a15))
(test-error-tail type-exception? (cdaar b0))
(test-error-tail type-exception? (cdaar b1))
(test-error-tail type-exception? (cdaar b2))
(test-error-tail type-exception? (cdaar b3))
(test-error-tail type-exception? (cdaar b4))
(test-error-tail type-exception? (cdaar b5))
(test-error-tail type-exception? (cdaar b6))
(test-error-tail type-exception? (cdaar b7))
(test-eqv 1 (cdaar c0))
(test-eqv 9 (cdaar c1))
(test-eqv 17 (cdaar c2))
(test-eqv 25 (cdaar c3))
(test-eq a1 (cdaar d0))
(test-eq a9 (cdaar d1))
(test-eq b1 (cdaar e0))
(test-error-tail wrong-number-of-arguments-exception? (cdaar))
(test-error-tail wrong-number-of-arguments-exception? (cdaar a0 a0))

(test-error-tail type-exception? (cdadr bool))
(test-error-tail type-exception? (cdadr a0))
(test-error-tail type-exception? (cdadr a1))
(test-error-tail type-exception? (cdadr a2))
(test-error-tail type-exception? (cdadr a3))
(test-error-tail type-exception? (cdadr a4))
(test-error-tail type-exception? (cdadr a5))
(test-error-tail type-exception? (cdadr a6))
(test-error-tail type-exception? (cdadr a7))
(test-error-tail type-exception? (cdadr a8))
(test-error-tail type-exception? (cdadr a9))
(test-error-tail type-exception? (cdadr a10))
(test-error-tail type-exception? (cdadr a11))
(test-error-tail type-exception? (cdadr a12))
(test-error-tail type-exception? (cdadr a13))
(test-error-tail type-exception? (cdadr a14))
(test-error-tail type-exception? (cdadr a15))
(test-error-tail type-exception? (cdadr b0))
(test-error-tail type-exception? (cdadr b1))
(test-error-tail type-exception? (cdadr b2))
(test-error-tail type-exception? (cdadr b3))
(test-error-tail type-exception? (cdadr b4))
(test-error-tail type-exception? (cdadr b5))
(test-error-tail type-exception? (cdadr b6))
(test-error-tail type-exception? (cdadr b7))
(test-eqv 5 (cdadr c0))
(test-eqv 13 (cdadr c1))
(test-eqv 21 (cdadr c2))
(test-eqv 29 (cdadr c3))
(test-eq a5 (cdadr d0))
(test-eq a13 (cdadr d1))
(test-eq b5 (cdadr e0))
(test-error-tail wrong-number-of-arguments-exception? (cdadr))
(test-error-tail wrong-number-of-arguments-exception? (cdadr a0 a0))

(test-error-tail type-exception? (cddar bool))
(test-error-tail type-exception? (cddar a0))
(test-error-tail type-exception? (cddar a1))
(test-error-tail type-exception? (cddar a2))
(test-error-tail type-exception? (cddar a3))
(test-error-tail type-exception? (cddar a4))
(test-error-tail type-exception? (cddar a5))
(test-error-tail type-exception? (cddar a6))
(test-error-tail type-exception? (cddar a7))
(test-error-tail type-exception? (cddar a8))
(test-error-tail type-exception? (cddar a9))
(test-error-tail type-exception? (cddar a10))
(test-error-tail type-exception? (cddar a11))
(test-error-tail type-exception? (cddar a12))
(test-error-tail type-exception? (cddar a13))
(test-error-tail type-exception? (cddar a14))
(test-error-tail type-exception? (cddar a15))
(test-error-tail type-exception? (cddar b0))
(test-error-tail type-exception? (cddar b1))
(test-error-tail type-exception? (cddar b2))
(test-error-tail type-exception? (cddar b3))
(test-error-tail type-exception? (cddar b4))
(test-error-tail type-exception? (cddar b5))
(test-error-tail type-exception? (cddar b6))
(test-error-tail type-exception? (cddar b7))
(test-eqv 3 (cddar c0))
(test-eqv 11 (cddar c1))
(test-eqv 19 (cddar c2))
(test-eqv 27 (cddar c3))
(test-eq a3 (cddar d0))
(test-eq a11 (cddar d1))
(test-eq b3 (cddar e0))
(test-error-tail wrong-number-of-arguments-exception? (cddar))
(test-error-tail wrong-number-of-arguments-exception? (cddar a0 a0))

(test-error-tail type-exception? (cdddr bool))
(test-error-tail type-exception? (cdddr a0))
(test-error-tail type-exception? (cdddr a1))
(test-error-tail type-exception? (cdddr a2))
(test-error-tail type-exception? (cdddr a3))
(test-error-tail type-exception? (cdddr a4))
(test-error-tail type-exception? (cdddr a5))
(test-error-tail type-exception? (cdddr a6))
(test-error-tail type-exception? (cdddr a7))
(test-error-tail type-exception? (cdddr a8))
(test-error-tail type-exception? (cdddr a9))
(test-error-tail type-exception? (cdddr a10))
(test-error-tail type-exception? (cdddr a11))
(test-error-tail type-exception? (cdddr a12))
(test-error-tail type-exception? (cdddr a13))
(test-error-tail type-exception? (cdddr a14))
(test-error-tail type-exception? (cdddr a15))
(test-error-tail type-exception? (cdddr b0))
(test-error-tail type-exception? (cdddr b1))
(test-error-tail type-exception? (cdddr b2))
(test-error-tail type-exception? (cdddr b3))
(test-error-tail type-exception? (cdddr b4))
(test-error-tail type-exception? (cdddr b5))
(test-error-tail type-exception? (cdddr b6))
(test-error-tail type-exception? (cdddr b7))
(test-eqv 7 (cdddr c0))
(test-eqv 15 (cdddr c1))
(test-eqv 23 (cdddr c2))
(test-eqv 31 (cdddr c3))
(test-eq a7 (cdddr d0))
(test-eq a15 (cdddr d1))
(test-eq b7 (cdddr e0))
(test-error-tail wrong-number-of-arguments-exception? (cdddr))
(test-error-tail wrong-number-of-arguments-exception? (cdddr a0 a0))

(test-error-tail type-exception? (caaaar bool))
(test-error-tail type-exception? (caaaar a0))
(test-error-tail type-exception? (caaaar a1))
(test-error-tail type-exception? (caaaar a2))
(test-error-tail type-exception? (caaaar a3))
(test-error-tail type-exception? (caaaar a4))
(test-error-tail type-exception? (caaaar a5))
(test-error-tail type-exception? (caaaar a6))
(test-error-tail type-exception? (caaaar a7))
(test-error-tail type-exception? (caaaar a8))
(test-error-tail type-exception? (caaaar a9))
(test-error-tail type-exception? (caaaar a10))
(test-error-tail type-exception? (caaaar a11))
(test-error-tail type-exception? (caaaar a12))
(test-error-tail type-exception? (caaaar a13))
(test-error-tail type-exception? (caaaar a14))
(test-error-tail type-exception? (caaaar a15))
(test-error-tail type-exception? (caaaar b0))
(test-error-tail type-exception? (caaaar b1))
(test-error-tail type-exception? (caaaar b2))
(test-error-tail type-exception? (caaaar b3))
(test-error-tail type-exception? (caaaar b4))
(test-error-tail type-exception? (caaaar b5))
(test-error-tail type-exception? (caaaar b6))
(test-error-tail type-exception? (caaaar b7))
(test-error-tail type-exception? (caaaar c0))
(test-error-tail type-exception? (caaaar c1))
(test-error-tail type-exception? (caaaar c2))
(test-error-tail type-exception? (caaaar c3))
(test-eqv 0 (caaaar d0))
(test-eqv 16 (caaaar d1))
(test-eq a0 (caaaar e0))
(test-error-tail wrong-number-of-arguments-exception? (caaaar))
(test-error-tail wrong-number-of-arguments-exception? (caaaar a0 a0))

(test-error-tail type-exception? (caaadr bool))
(test-error-tail type-exception? (caaadr a0))
(test-error-tail type-exception? (caaadr a1))
(test-error-tail type-exception? (caaadr a2))
(test-error-tail type-exception? (caaadr a3))
(test-error-tail type-exception? (caaadr a4))
(test-error-tail type-exception? (caaadr a5))
(test-error-tail type-exception? (caaadr a6))
(test-error-tail type-exception? (caaadr a7))
(test-error-tail type-exception? (caaadr a8))
(test-error-tail type-exception? (caaadr a9))
(test-error-tail type-exception? (caaadr a10))
(test-error-tail type-exception? (caaadr a11))
(test-error-tail type-exception? (caaadr a12))
(test-error-tail type-exception? (caaadr a13))
(test-error-tail type-exception? (caaadr a14))
(test-error-tail type-exception? (caaadr a15))
(test-error-tail type-exception? (caaadr b0))
(test-error-tail type-exception? (caaadr b1))
(test-error-tail type-exception? (caaadr b2))
(test-error-tail type-exception? (caaadr b3))
(test-error-tail type-exception? (caaadr b4))
(test-error-tail type-exception? (caaadr b5))
(test-error-tail type-exception? (caaadr b6))
(test-error-tail type-exception? (caaadr b7))
(test-error-tail type-exception? (caaadr c0))
(test-error-tail type-exception? (caaadr c1))
(test-error-tail type-exception? (caaadr c2))
(test-error-tail type-exception? (caaadr c3))
(test-eqv 8 (caaadr d0))
(test-eqv 24 (caaadr d1))
(test-eq a8 (caaadr e0))
(test-error-tail wrong-number-of-arguments-exception? (caaadr))
(test-error-tail wrong-number-of-arguments-exception? (caaadr a0 a0))

(test-error-tail type-exception? (caadar bool))
(test-error-tail type-exception? (caadar a0))
(test-error-tail type-exception? (caadar a1))
(test-error-tail type-exception? (caadar a2))
(test-error-tail type-exception? (caadar a3))
(test-error-tail type-exception? (caadar a4))
(test-error-tail type-exception? (caadar a5))
(test-error-tail type-exception? (caadar a6))
(test-error-tail type-exception? (caadar a7))
(test-error-tail type-exception? (caadar a8))
(test-error-tail type-exception? (caadar a9))
(test-error-tail type-exception? (caadar a10))
(test-error-tail type-exception? (caadar a11))
(test-error-tail type-exception? (caadar a12))
(test-error-tail type-exception? (caadar a13))
(test-error-tail type-exception? (caadar a14))
(test-error-tail type-exception? (caadar a15))
(test-error-tail type-exception? (caadar b0))
(test-error-tail type-exception? (caadar b1))
(test-error-tail type-exception? (caadar b2))
(test-error-tail type-exception? (caadar b3))
(test-error-tail type-exception? (caadar b4))
(test-error-tail type-exception? (caadar b5))
(test-error-tail type-exception? (caadar b6))
(test-error-tail type-exception? (caadar b7))
(test-error-tail type-exception? (caadar c0))
(test-error-tail type-exception? (caadar c1))
(test-error-tail type-exception? (caadar c2))
(test-error-tail type-exception? (caadar c3))
(test-eqv 4 (caadar d0))
(test-eqv 20 (caadar d1))
(test-eq a4 (caadar e0))
(test-error-tail wrong-number-of-arguments-exception? (caadar))
(test-error-tail wrong-number-of-arguments-exception? (caadar a0 a0))

(test-error-tail type-exception? (caaddr bool))
(test-error-tail type-exception? (caaddr a0))
(test-error-tail type-exception? (caaddr a1))
(test-error-tail type-exception? (caaddr a2))
(test-error-tail type-exception? (caaddr a3))
(test-error-tail type-exception? (caaddr a4))
(test-error-tail type-exception? (caaddr a5))
(test-error-tail type-exception? (caaddr a6))
(test-error-tail type-exception? (caaddr a7))
(test-error-tail type-exception? (caaddr a8))
(test-error-tail type-exception? (caaddr a9))
(test-error-tail type-exception? (caaddr a10))
(test-error-tail type-exception? (caaddr a11))
(test-error-tail type-exception? (caaddr a12))
(test-error-tail type-exception? (caaddr a13))
(test-error-tail type-exception? (caaddr a14))
(test-error-tail type-exception? (caaddr a15))
(test-error-tail type-exception? (caaddr b0))
(test-error-tail type-exception? (caaddr b1))
(test-error-tail type-exception? (caaddr b2))
(test-error-tail type-exception? (caaddr b3))
(test-error-tail type-exception? (caaddr b4))
(test-error-tail type-exception? (caaddr b5))
(test-error-tail type-exception? (caaddr b6))
(test-error-tail type-exception? (caaddr b7))
(test-error-tail type-exception? (caaddr c0))
(test-error-tail type-exception? (caaddr c1))
(test-error-tail type-exception? (caaddr c2))
(test-error-tail type-exception? (caaddr c3))
(test-eqv 12 (caaddr d0))
(test-eqv 28 (caaddr d1))
(test-eq a12 (caaddr e0))
(test-error-tail wrong-number-of-arguments-exception? (caaddr))
(test-error-tail wrong-number-of-arguments-exception? (caaddr a0 a0))

(test-error-tail type-exception? (cadaar bool))
(test-error-tail type-exception? (cadaar a0))
(test-error-tail type-exception? (cadaar a1))
(test-error-tail type-exception? (cadaar a2))
(test-error-tail type-exception? (cadaar a3))
(test-error-tail type-exception? (cadaar a4))
(test-error-tail type-exception? (cadaar a5))
(test-error-tail type-exception? (cadaar a6))
(test-error-tail type-exception? (cadaar a7))
(test-error-tail type-exception? (cadaar a8))
(test-error-tail type-exception? (cadaar a9))
(test-error-tail type-exception? (cadaar a10))
(test-error-tail type-exception? (cadaar a11))
(test-error-tail type-exception? (cadaar a12))
(test-error-tail type-exception? (cadaar a13))
(test-error-tail type-exception? (cadaar a14))
(test-error-tail type-exception? (cadaar a15))
(test-error-tail type-exception? (cadaar b0))
(test-error-tail type-exception? (cadaar b1))
(test-error-tail type-exception? (cadaar b2))
(test-error-tail type-exception? (cadaar b3))
(test-error-tail type-exception? (cadaar b4))
(test-error-tail type-exception? (cadaar b5))
(test-error-tail type-exception? (cadaar b6))
(test-error-tail type-exception? (cadaar b7))
(test-error-tail type-exception? (cadaar c0))
(test-error-tail type-exception? (cadaar c1))
(test-error-tail type-exception? (cadaar c2))
(test-error-tail type-exception? (cadaar c3))
(test-eqv 2 (cadaar d0))
(test-eqv 18 (cadaar d1))
(test-eq a2 (cadaar e0))
(test-error-tail wrong-number-of-arguments-exception? (cadaar))
(test-error-tail wrong-number-of-arguments-exception? (cadaar a0 a0))

(test-error-tail type-exception? (cadadr bool))
(test-error-tail type-exception? (cadadr a0))
(test-error-tail type-exception? (cadadr a1))
(test-error-tail type-exception? (cadadr a2))
(test-error-tail type-exception? (cadadr a3))
(test-error-tail type-exception? (cadadr a4))
(test-error-tail type-exception? (cadadr a5))
(test-error-tail type-exception? (cadadr a6))
(test-error-tail type-exception? (cadadr a7))
(test-error-tail type-exception? (cadadr a8))
(test-error-tail type-exception? (cadadr a9))
(test-error-tail type-exception? (cadadr a10))
(test-error-tail type-exception? (cadadr a11))
(test-error-tail type-exception? (cadadr a12))
(test-error-tail type-exception? (cadadr a13))
(test-error-tail type-exception? (cadadr a14))
(test-error-tail type-exception? (cadadr a15))
(test-error-tail type-exception? (cadadr b0))
(test-error-tail type-exception? (cadadr b1))
(test-error-tail type-exception? (cadadr b2))
(test-error-tail type-exception? (cadadr b3))
(test-error-tail type-exception? (cadadr b4))
(test-error-tail type-exception? (cadadr b5))
(test-error-tail type-exception? (cadadr b6))
(test-error-tail type-exception? (cadadr b7))
(test-error-tail type-exception? (cadadr c0))
(test-error-tail type-exception? (cadadr c1))
(test-error-tail type-exception? (cadadr c2))
(test-error-tail type-exception? (cadadr c3))
(test-eqv 10 (cadadr d0))
(test-eqv 26 (cadadr d1))
(test-eq a10 (cadadr e0))
(test-error-tail wrong-number-of-arguments-exception? (cadadr))
(test-error-tail wrong-number-of-arguments-exception? (cadadr a0 a0))

(test-error-tail type-exception? (caddar bool))
(test-error-tail type-exception? (caddar a0))
(test-error-tail type-exception? (caddar a1))
(test-error-tail type-exception? (caddar a2))
(test-error-tail type-exception? (caddar a3))
(test-error-tail type-exception? (caddar a4))
(test-error-tail type-exception? (caddar a5))
(test-error-tail type-exception? (caddar a6))
(test-error-tail type-exception? (caddar a7))
(test-error-tail type-exception? (caddar a8))
(test-error-tail type-exception? (caddar a9))
(test-error-tail type-exception? (caddar a10))
(test-error-tail type-exception? (caddar a11))
(test-error-tail type-exception? (caddar a12))
(test-error-tail type-exception? (caddar a13))
(test-error-tail type-exception? (caddar a14))
(test-error-tail type-exception? (caddar a15))
(test-error-tail type-exception? (caddar b0))
(test-error-tail type-exception? (caddar b1))
(test-error-tail type-exception? (caddar b2))
(test-error-tail type-exception? (caddar b3))
(test-error-tail type-exception? (caddar b4))
(test-error-tail type-exception? (caddar b5))
(test-error-tail type-exception? (caddar b6))
(test-error-tail type-exception? (caddar b7))
(test-error-tail type-exception? (caddar c0))
(test-error-tail type-exception? (caddar c1))
(test-error-tail type-exception? (caddar c2))
(test-error-tail type-exception? (caddar c3))
(test-eqv 6 (caddar d0))
(test-eqv 22 (caddar d1))
(test-eq a6 (caddar e0))
(test-error-tail wrong-number-of-arguments-exception? (caddar))
(test-error-tail wrong-number-of-arguments-exception? (caddar a0 a0))

(test-error-tail type-exception? (cadddr bool))
(test-error-tail type-exception? (cadddr a0))
(test-error-tail type-exception? (cadddr a1))
(test-error-tail type-exception? (cadddr a2))
(test-error-tail type-exception? (cadddr a3))
(test-error-tail type-exception? (cadddr a4))
(test-error-tail type-exception? (cadddr a5))
(test-error-tail type-exception? (cadddr a6))
(test-error-tail type-exception? (cadddr a7))
(test-error-tail type-exception? (cadddr a8))
(test-error-tail type-exception? (cadddr a9))
(test-error-tail type-exception? (cadddr a10))
(test-error-tail type-exception? (cadddr a11))
(test-error-tail type-exception? (cadddr a12))
(test-error-tail type-exception? (cadddr a13))
(test-error-tail type-exception? (cadddr a14))
(test-error-tail type-exception? (cadddr a15))
(test-error-tail type-exception? (cadddr b0))
(test-error-tail type-exception? (cadddr b1))
(test-error-tail type-exception? (cadddr b2))
(test-error-tail type-exception? (cadddr b3))
(test-error-tail type-exception? (cadddr b4))
(test-error-tail type-exception? (cadddr b5))
(test-error-tail type-exception? (cadddr b6))
(test-error-tail type-exception? (cadddr b7))
(test-error-tail type-exception? (cadddr c0))
(test-error-tail type-exception? (cadddr c1))
(test-error-tail type-exception? (cadddr c2))
(test-error-tail type-exception? (cadddr c3))
(test-eqv 14 (cadddr d0))
(test-eqv 30 (cadddr d1))
(test-eq a14 (cadddr e0))
(test-error-tail wrong-number-of-arguments-exception? (cadddr))
(test-error-tail wrong-number-of-arguments-exception? (cadddr a0 a0))

(test-error-tail type-exception? (cdaaar bool))
(test-error-tail type-exception? (cdaaar a0))
(test-error-tail type-exception? (cdaaar a1))
(test-error-tail type-exception? (cdaaar a2))
(test-error-tail type-exception? (cdaaar a3))
(test-error-tail type-exception? (cdaaar a4))
(test-error-tail type-exception? (cdaaar a5))
(test-error-tail type-exception? (cdaaar a6))
(test-error-tail type-exception? (cdaaar a7))
(test-error-tail type-exception? (cdaaar a8))
(test-error-tail type-exception? (cdaaar a9))
(test-error-tail type-exception? (cdaaar a10))
(test-error-tail type-exception? (cdaaar a11))
(test-error-tail type-exception? (cdaaar a12))
(test-error-tail type-exception? (cdaaar a13))
(test-error-tail type-exception? (cdaaar a14))
(test-error-tail type-exception? (cdaaar a15))
(test-error-tail type-exception? (cdaaar b0))
(test-error-tail type-exception? (cdaaar b1))
(test-error-tail type-exception? (cdaaar b2))
(test-error-tail type-exception? (cdaaar b3))
(test-error-tail type-exception? (cdaaar b4))
(test-error-tail type-exception? (cdaaar b5))
(test-error-tail type-exception? (cdaaar b6))
(test-error-tail type-exception? (cdaaar b7))
(test-error-tail type-exception? (cdaaar c0))
(test-error-tail type-exception? (cdaaar c1))
(test-error-tail type-exception? (cdaaar c2))
(test-error-tail type-exception? (cdaaar c3))
(test-eqv 1 (cdaaar d0))
(test-eqv 17 (cdaaar d1))
(test-eq a1 (cdaaar e0))
(test-error-tail wrong-number-of-arguments-exception? (cdaaar))
(test-error-tail wrong-number-of-arguments-exception? (cdaaar a0 a0))

(test-error-tail type-exception? (cdaadr bool))
(test-error-tail type-exception? (cdaadr a0))
(test-error-tail type-exception? (cdaadr a1))
(test-error-tail type-exception? (cdaadr a2))
(test-error-tail type-exception? (cdaadr a3))
(test-error-tail type-exception? (cdaadr a4))
(test-error-tail type-exception? (cdaadr a5))
(test-error-tail type-exception? (cdaadr a6))
(test-error-tail type-exception? (cdaadr a7))
(test-error-tail type-exception? (cdaadr a8))
(test-error-tail type-exception? (cdaadr a9))
(test-error-tail type-exception? (cdaadr a10))
(test-error-tail type-exception? (cdaadr a11))
(test-error-tail type-exception? (cdaadr a12))
(test-error-tail type-exception? (cdaadr a13))
(test-error-tail type-exception? (cdaadr a14))
(test-error-tail type-exception? (cdaadr a15))
(test-error-tail type-exception? (cdaadr b0))
(test-error-tail type-exception? (cdaadr b1))
(test-error-tail type-exception? (cdaadr b2))
(test-error-tail type-exception? (cdaadr b3))
(test-error-tail type-exception? (cdaadr b4))
(test-error-tail type-exception? (cdaadr b5))
(test-error-tail type-exception? (cdaadr b6))
(test-error-tail type-exception? (cdaadr b7))
(test-error-tail type-exception? (cdaadr c0))
(test-error-tail type-exception? (cdaadr c1))
(test-error-tail type-exception? (cdaadr c2))
(test-error-tail type-exception? (cdaadr c3))
(test-eqv 9 (cdaadr d0))
(test-eqv 25 (cdaadr d1))
(test-eq a9 (cdaadr e0))
(test-error-tail wrong-number-of-arguments-exception? (cdaadr))
(test-error-tail wrong-number-of-arguments-exception? (cdaadr a0 a0))

(test-error-tail type-exception? (cdadar bool))
(test-error-tail type-exception? (cdadar a0))
(test-error-tail type-exception? (cdadar a1))
(test-error-tail type-exception? (cdadar a2))
(test-error-tail type-exception? (cdadar a3))
(test-error-tail type-exception? (cdadar a4))
(test-error-tail type-exception? (cdadar a5))
(test-error-tail type-exception? (cdadar a6))
(test-error-tail type-exception? (cdadar a7))
(test-error-tail type-exception? (cdadar a8))
(test-error-tail type-exception? (cdadar a9))
(test-error-tail type-exception? (cdadar a10))
(test-error-tail type-exception? (cdadar a11))
(test-error-tail type-exception? (cdadar a12))
(test-error-tail type-exception? (cdadar a13))
(test-error-tail type-exception? (cdadar a14))
(test-error-tail type-exception? (cdadar a15))
(test-error-tail type-exception? (cdadar b0))
(test-error-tail type-exception? (cdadar b1))
(test-error-tail type-exception? (cdadar b2))
(test-error-tail type-exception? (cdadar b3))
(test-error-tail type-exception? (cdadar b4))
(test-error-tail type-exception? (cdadar b5))
(test-error-tail type-exception? (cdadar b6))
(test-error-tail type-exception? (cdadar b7))
(test-error-tail type-exception? (cdadar c0))
(test-error-tail type-exception? (cdadar c1))
(test-error-tail type-exception? (cdadar c2))
(test-error-tail type-exception? (cdadar c3))
(test-eqv 5 (cdadar d0))
(test-eqv 21 (cdadar d1))
(test-eq a5 (cdadar e0))
(test-error-tail wrong-number-of-arguments-exception? (cdadar))
(test-error-tail wrong-number-of-arguments-exception? (cdadar a0 a0))

(test-error-tail type-exception? (cdaddr bool))
(test-error-tail type-exception? (cdaddr a0))
(test-error-tail type-exception? (cdaddr a1))
(test-error-tail type-exception? (cdaddr a2))
(test-error-tail type-exception? (cdaddr a3))
(test-error-tail type-exception? (cdaddr a4))
(test-error-tail type-exception? (cdaddr a5))
(test-error-tail type-exception? (cdaddr a6))
(test-error-tail type-exception? (cdaddr a7))
(test-error-tail type-exception? (cdaddr a8))
(test-error-tail type-exception? (cdaddr a9))
(test-error-tail type-exception? (cdaddr a10))
(test-error-tail type-exception? (cdaddr a11))
(test-error-tail type-exception? (cdaddr a12))
(test-error-tail type-exception? (cdaddr a13))
(test-error-tail type-exception? (cdaddr a14))
(test-error-tail type-exception? (cdaddr a15))
(test-error-tail type-exception? (cdaddr b0))
(test-error-tail type-exception? (cdaddr b1))
(test-error-tail type-exception? (cdaddr b2))
(test-error-tail type-exception? (cdaddr b3))
(test-error-tail type-exception? (cdaddr b4))
(test-error-tail type-exception? (cdaddr b5))
(test-error-tail type-exception? (cdaddr b6))
(test-error-tail type-exception? (cdaddr b7))
(test-error-tail type-exception? (cdaddr c0))
(test-error-tail type-exception? (cdaddr c1))
(test-error-tail type-exception? (cdaddr c2))
(test-error-tail type-exception? (cdaddr c3))
(test-eqv 13 (cdaddr d0))
(test-eqv 29 (cdaddr d1))
(test-eq a13 (cdaddr e0))
(test-error-tail wrong-number-of-arguments-exception? (cdaddr))
(test-error-tail wrong-number-of-arguments-exception? (cdaddr a0 a0))

(test-error-tail type-exception? (cddaar bool))
(test-error-tail type-exception? (cddaar a0))
(test-error-tail type-exception? (cddaar a1))
(test-error-tail type-exception? (cddaar a2))
(test-error-tail type-exception? (cddaar a3))
(test-error-tail type-exception? (cddaar a4))
(test-error-tail type-exception? (cddaar a5))
(test-error-tail type-exception? (cddaar a6))
(test-error-tail type-exception? (cddaar a7))
(test-error-tail type-exception? (cddaar a8))
(test-error-tail type-exception? (cddaar a9))
(test-error-tail type-exception? (cddaar a10))
(test-error-tail type-exception? (cddaar a11))
(test-error-tail type-exception? (cddaar a12))
(test-error-tail type-exception? (cddaar a13))
(test-error-tail type-exception? (cddaar a14))
(test-error-tail type-exception? (cddaar a15))
(test-error-tail type-exception? (cddaar b0))
(test-error-tail type-exception? (cddaar b1))
(test-error-tail type-exception? (cddaar b2))
(test-error-tail type-exception? (cddaar b3))
(test-error-tail type-exception? (cddaar b4))
(test-error-tail type-exception? (cddaar b5))
(test-error-tail type-exception? (cddaar b6))
(test-error-tail type-exception? (cddaar b7))
(test-error-tail type-exception? (cddaar c0))
(test-error-tail type-exception? (cddaar c1))
(test-error-tail type-exception? (cddaar c2))
(test-error-tail type-exception? (cddaar c3))
(test-eqv 3 (cddaar d0))
(test-eqv 19 (cddaar d1))
(test-eq a3 (cddaar e0))
(test-error-tail wrong-number-of-arguments-exception? (cddaar))
(test-error-tail wrong-number-of-arguments-exception? (cddaar a0 a0))

(test-error-tail type-exception? (cddadr bool))
(test-error-tail type-exception? (cddadr a0))
(test-error-tail type-exception? (cddadr a1))
(test-error-tail type-exception? (cddadr a2))
(test-error-tail type-exception? (cddadr a3))
(test-error-tail type-exception? (cddadr a4))
(test-error-tail type-exception? (cddadr a5))
(test-error-tail type-exception? (cddadr a6))
(test-error-tail type-exception? (cddadr a7))
(test-error-tail type-exception? (cddadr a8))
(test-error-tail type-exception? (cddadr a9))
(test-error-tail type-exception? (cddadr a10))
(test-error-tail type-exception? (cddadr a11))
(test-error-tail type-exception? (cddadr a12))
(test-error-tail type-exception? (cddadr a13))
(test-error-tail type-exception? (cddadr a14))
(test-error-tail type-exception? (cddadr a15))
(test-error-tail type-exception? (cddadr b0))
(test-error-tail type-exception? (cddadr b1))
(test-error-tail type-exception? (cddadr b2))
(test-error-tail type-exception? (cddadr b3))
(test-error-tail type-exception? (cddadr b4))
(test-error-tail type-exception? (cddadr b5))
(test-error-tail type-exception? (cddadr b6))
(test-error-tail type-exception? (cddadr b7))
(test-error-tail type-exception? (cddadr c0))
(test-error-tail type-exception? (cddadr c1))
(test-error-tail type-exception? (cddadr c2))
(test-error-tail type-exception? (cddadr c3))
(test-eqv 11 (cddadr d0))
(test-eqv 27 (cddadr d1))
(test-eq a11 (cddadr e0))
(test-error-tail wrong-number-of-arguments-exception? (cddadr))
(test-error-tail wrong-number-of-arguments-exception? (cddadr a0 a0))

(test-error-tail type-exception? (cdddar bool))
(test-error-tail type-exception? (cdddar a0))
(test-error-tail type-exception? (cdddar a1))
(test-error-tail type-exception? (cdddar a2))
(test-error-tail type-exception? (cdddar a3))
(test-error-tail type-exception? (cdddar a4))
(test-error-tail type-exception? (cdddar a5))
(test-error-tail type-exception? (cdddar a6))
(test-error-tail type-exception? (cdddar a7))
(test-error-tail type-exception? (cdddar a8))
(test-error-tail type-exception? (cdddar a9))
(test-error-tail type-exception? (cdddar a10))
(test-error-tail type-exception? (cdddar a11))
(test-error-tail type-exception? (cdddar a12))
(test-error-tail type-exception? (cdddar a13))
(test-error-tail type-exception? (cdddar a14))
(test-error-tail type-exception? (cdddar a15))
(test-error-tail type-exception? (cdddar b0))
(test-error-tail type-exception? (cdddar b1))
(test-error-tail type-exception? (cdddar b2))
(test-error-tail type-exception? (cdddar b3))
(test-error-tail type-exception? (cdddar b4))
(test-error-tail type-exception? (cdddar b5))
(test-error-tail type-exception? (cdddar b6))
(test-error-tail type-exception? (cdddar b7))
(test-error-tail type-exception? (cdddar c0))
(test-error-tail type-exception? (cdddar c1))
(test-error-tail type-exception? (cdddar c2))
(test-error-tail type-exception? (cdddar c3))
(test-eqv 7 (cdddar d0))
(test-eqv 23 (cdddar d1))
(test-eq a7 (cdddar e0))
(test-error-tail wrong-number-of-arguments-exception? (cdddar))
(test-error-tail wrong-number-of-arguments-exception? (cdddar a0 a0))

(test-error-tail type-exception? (cddddr bool))
(test-error-tail type-exception? (cddddr a0))
(test-error-tail type-exception? (cddddr a1))
(test-error-tail type-exception? (cddddr a2))
(test-error-tail type-exception? (cddddr a3))
(test-error-tail type-exception? (cddddr a4))
(test-error-tail type-exception? (cddddr a5))
(test-error-tail type-exception? (cddddr a6))
(test-error-tail type-exception? (cddddr a7))
(test-error-tail type-exception? (cddddr a8))
(test-error-tail type-exception? (cddddr a9))
(test-error-tail type-exception? (cddddr a10))
(test-error-tail type-exception? (cddddr a11))
(test-error-tail type-exception? (cddddr a12))
(test-error-tail type-exception? (cddddr a13))
(test-error-tail type-exception? (cddddr a14))
(test-error-tail type-exception? (cddddr a15))
(test-error-tail type-exception? (cddddr b0))
(test-error-tail type-exception? (cddddr b1))
(test-error-tail type-exception? (cddddr b2))
(test-error-tail type-exception? (cddddr b3))
(test-error-tail type-exception? (cddddr b4))
(test-error-tail type-exception? (cddddr b5))
(test-error-tail type-exception? (cddddr b6))
(test-error-tail type-exception? (cddddr b7))
(test-error-tail type-exception? (cddddr c0))
(test-error-tail type-exception? (cddddr c1))
(test-error-tail type-exception? (cddddr c2))
(test-error-tail type-exception? (cddddr c3))
(test-eqv 15 (cddddr d0))
(test-eqv 31 (cddddr d1))
(test-eq a15 (cddddr e0))
(test-error-tail wrong-number-of-arguments-exception? (cddddr))
(test-error-tail wrong-number-of-arguments-exception? (cddddr a0 a0))

