(include "#.scm")

(define bool #f)

;; proper lists
(define lst0 (list))
(define lst1 (list 11))
(define lst2 (list 22 33))

;; dotted list
(define lst3 (cons 44 55))
(define lst4 (cons 66 (cons 77 88)))

(test-eq '() (concatenate! lst0))
(test-eq bool (concatenate! (list bool)))
(test-eq bool (concatenate! (list lst0 bool)))
(test-eq lst0 (concatenate! (list lst0 lst0)))
(test-eq lst1 (concatenate! (list lst0 lst1)))
(test-eq lst2 (concatenate! (list lst0 lst2)))
(test-eq lst3 (concatenate! (list lst0 lst3)))
(test-eq lst4 (concatenate! (list lst0 lst4)))
(test-eq bool (concatenate! (list lst0 lst0 bool)))
(test-eq lst0 (concatenate! (list lst0 lst0 lst0)))
(test-eq lst1 (concatenate! (list lst0 lst0 lst1)))
(test-eq lst2 (concatenate! (list lst0 lst0 lst2)))
(test-eq lst3 (concatenate! (list lst0 lst0 lst3)))
(test-eq lst4 (concatenate! (list lst0 lst0 lst4)))

(define a (concatenate! (list lst1 bool)))

(test-equal '(11 . #f) a)
(test-eq lst1 a)

(define b (concatenate! (list lst0 lst0 lst2 lst0 lst1)))

(test-equal '(22 33 11 . #f) b)
(test-eq lst2 b)
(test-eq lst1 (cddr b))

(test-error-tail type-exception? (concatenate! bool))
(test-error-tail type-exception? (concatenate! (cons lst0 bool)))
(test-error-tail type-exception? (concatenate! (cons lst0 (cons lst0 bool))))
(test-error-tail type-exception? (concatenate! (cons lst1 (cons lst0 bool))))
(test-error-tail type-exception? (concatenate! (cons lst0 (cons lst1 bool))))
(test-error-tail type-exception? (concatenate! (list bool lst0)))
(test-error-tail type-exception? (concatenate! (list bool lst1)))
(test-error-tail type-exception? (concatenate! (list bool lst2)))
(test-error-tail type-exception? (concatenate! (list bool lst3)))
(test-error-tail type-exception? (concatenate! (list lst3 bool)))
(test-error-tail type-exception? (concatenate! (list lst3 lst0)))
(test-error-tail type-exception? (concatenate! (list lst3 lst1)))
(test-error-tail type-exception? (concatenate! (list lst3 lst2)))
(test-error-tail type-exception? (concatenate! (list lst3 lst3)))
(test-error-tail type-exception? (concatenate! (list lst4 bool)))
(test-error-tail type-exception? (concatenate! (list lst4 lst0)))
(test-error-tail type-exception? (concatenate! (list lst4 lst1)))
(test-error-tail type-exception? (concatenate! (list lst4 lst2)))
(test-error-tail type-exception? (concatenate! (list lst4 lst3)))
(test-error-tail type-exception? (concatenate! (list lst0 bool lst0)))
(test-error-tail type-exception? (concatenate! (list lst0 bool lst1)))
(test-error-tail type-exception? (concatenate! (list lst0 bool lst2)))
(test-error-tail type-exception? (concatenate! (list lst0 bool lst3)))
(test-error-tail type-exception? (concatenate! (list lst0 lst3 bool)))
(test-error-tail type-exception? (concatenate! (list lst0 lst3 lst0)))
(test-error-tail type-exception? (concatenate! (list lst0 lst3 lst1)))
(test-error-tail type-exception? (concatenate! (list lst0 lst3 lst2)))
(test-error-tail type-exception? (concatenate! (list lst0 lst3 lst3)))
(test-error-tail type-exception? (concatenate! (list lst0 lst4 bool)))
(test-error-tail type-exception? (concatenate! (list lst0 lst4 lst0)))
(test-error-tail type-exception? (concatenate! (list lst0 lst4 lst1)))
(test-error-tail type-exception? (concatenate! (list lst0 lst4 lst2)))
(test-error-tail type-exception? (concatenate! (list lst0 lst4 lst3)))

(test-error-tail wrong-number-of-arguments-exception? (concatenate!))
(test-error-tail wrong-number-of-arguments-exception? (concatenate! lst0 lst1))
