(include "#.scm")

(test-equal '(c d) (list-tail '(a b c d) 2))
(test-eq '() (list-tail '(a b) 2))
(test-eq 'tail (list-tail '(a . tail) 1))
(test-error range-exception? (list-tail '(a) -1))
(test-error range-exception? (list-tail '(a) 2))
(test-eq #t (not-pair? '()))
(test-eq #t (not-pair? 1))
(test-eq #f (not-pair? '(1)))
(test-eq #t (null-list? '()))
(test-eq #f (null-list? '(1)))
(test-error type-exception? (null-list? 1))
(test-eqv 3 (count odd? '(1 2 3 4 5)))
(test-eqv 2 (count < '(1 3 2) '(2 2 3)))
(test-eqv 0 (count odd? '()))
(test-eq #t (list= = '(1 2) '(1 2) '(1 2)))
(test-eq #f (list= = '(1 2) '(1 2) '(1 3)))
(test-eq #f (list= = '(1) '(1 2)))
(test-equal '((a 1) (b 2)) (zip '(a b) '(1 2)))
(test-equal '() (zip '() '(1 2)))
(test-equal '(a b) (unzip1 '((a 1) (b 2))))
(test-equal '((a b) (1 2))
 (call-with-values (lambda () (unzip2 '((a 1) (b 2)))) list))
(test-equal '((a b) (1 2) (x y))
 (call-with-values (lambda () (unzip3 '((a 1 x) (b 2 y)))) list))
(test-equal '((a b) (1 2) (x y) (#t #f))
 (call-with-values (lambda () (unzip4 '((a 1 x #t) (b 2 y #f)))) list))
(test-equal '((a b) (1 2) (x y) (#t #f) (p q))
 (call-with-values (lambda () (unzip5 '((a 1 x #t p) (b 2 y #f q)))) list))
(test-equal '(() () () () ())
 (call-with-values (lambda () (unzip5 '())) list))
