# Copyright (c) 2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/45
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 45\#.scm
MODULES_SCM = 45.scm 45.sld test/test.scm
MAIN_MODULES = 45
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
