(include "#.scm")

(test-eqv -1 (##fxand))
(test-eqv 1 (##fxand 1))
(test-eqv 0 (##fxand 4 1))
(test-eqv 2 (##fxand 14 3))
(test-eqv 3 (##fxand 15 3))
(test-eqv 5 (##fxand 13 5 29))

(test-eqv -1 (fxand))
(test-eqv 1 (fxand 1))
(test-eqv 0 (fxand 4 1))
(test-eqv 2 (fxand 14 3))
(test-eqv 3 (fxand 15 3))
(test-eqv 5 (fxand 13 5 29))

(test-error-tail type-exception? (fxand 0. 1))
(test-error-tail type-exception? (fxand .5 1))
(test-error-tail type-exception? (fxand 1 .5))
(test-error-tail type-exception? (fxand 1 1/2))
