(include "#.scm")

(check-eqv? (##fx*?  6  7)  42)
(check-eqv? (##fx*?  6 -7) -42)
(check-eqv? (##fx*? -6  7) -42)
(check-eqv? (##fx*? -6 -7)  42)

(check-eqv? (##fx*? 0 7) 0)
(check-eqv? (##fx*? 6 0) 0)
(check-eqv? (##fx*? (##greatest-fixnum) -1) (##fx- 0 (##greatest-fixnum)))
(check-eqv? (##fx*? (##least-fixnum) -1) #f)

(check-eqv? (##fx*? (##greatest-fixnum) 1) (##greatest-fixnum))
(check-eqv? (##fx*? (##least-fixnum) 1) (##least-fixnum))

(check-eqv? (##fx*? 2 (##fxquotient (##greatest-fixnum) 2))
            (##fx* 2 (##fxquotient (##greatest-fixnum) 2)))
(check-eqv? (##fx*? (##fxquotient (##greatest-fixnum) 2) 2)
            (##fx* (##fxquotient (##greatest-fixnum) 2) 2))
(check-eqv? (##fx*? (##fxquotient (##least-fixnum) 2) 2)
            (##fx* (##fxquotient (##least-fixnum) 2) 2))
(check-eqv? (##fx*? 2 (##fxquotient (##least-fixnum) 2))
            (##fx* 2 (##fxquotient (##least-fixnum) 2)))

(check-eqv? (##fx*? 2 (##fx+ (##fxquotient (##greatest-fixnum) 2) 1)) #f)
(check-eqv? (##fx*? (##fx+ (##fxquotient (##greatest-fixnum) 2) 1) 2) #f)
(check-eqv? (##fx*? (##fx- (##fxquotient (##least-fixnum) 2) 1) 2) #f)
(check-eqv? (##fx*? 2 (##fx- (##fxquotient (##least-fixnum) 2) 1)) #f)

(check-eqv? (##fx*? 3 (##fxquotient (##greatest-fixnum) 3))
            (##fx* 3 (##fxquotient (##greatest-fixnum) 3)))
(check-eqv? (##fx*? (##fxquotient (##greatest-fixnum) 3) 3)
            (##fx* (##fxquotient (##greatest-fixnum) 3) 3))
(check-eqv? (##fx*? (##fxquotient (##least-fixnum) 3) 3)
            (##fx* (##fxquotient (##least-fixnum) 3) 3))
(check-eqv? (##fx*? 3 (##fxquotient (##least-fixnum) 3))
            (##fx* 3 (##fxquotient (##least-fixnum) 3)))

(check-eqv? (##fx*? 3 (##fx+ (##fxquotient (##greatest-fixnum) 3) 1)) #f)
(check-eqv? (##fx*? (##fx+ (##fxquotient (##greatest-fixnum) 3) 1) 3) #f)
(check-eqv? (##fx*? (##fx- (##fxquotient (##least-fixnum) 3) 1) 3) #f)
(check-eqv? (##fx*? 3 (##fx- (##fxquotient (##least-fixnum) 3) 1)) #f)
