(include "#.scm")

(check-eqv? (##fx*?  6  7)  42)
(check-eqv? (##fx*?  6 -7) -42)
(check-eqv? (##fx*? -6  7) -42)
(check-eqv? (##fx*? -6 -7)  42)

(check-eqv? (##fx*? 0 7) 0)
(check-eqv? (##fx*? 6 0) 0)
(check-eqv? (##fx*? ##max-fixnum -1) (##fx- 0 ##max-fixnum))
(check-eqv? (##fx*? ##min-fixnum -1) #f)

(check-eqv? (##fx*? ##max-fixnum 1) ##max-fixnum)
(check-eqv? (##fx*? ##min-fixnum 1) ##min-fixnum)

(check-eqv? (##fx*? 2 (##fxquotient ##max-fixnum 2))
            (##fx* 2 (##fxquotient ##max-fixnum 2)))
(check-eqv? (##fx*? (##fxquotient ##max-fixnum 2) 2)
            (##fx* (##fxquotient ##max-fixnum 2) 2))
(check-eqv? (##fx*? (##fxquotient ##min-fixnum 2) 2)
            (##fx* (##fxquotient ##min-fixnum 2) 2))
(check-eqv? (##fx*? 2 (##fxquotient ##min-fixnum 2))
            (##fx* 2 (##fxquotient ##min-fixnum 2)))

(check-eqv? (##fx*? 2 (##fx+ (##fxquotient ##max-fixnum 2) 1)) #f)
(check-eqv? (##fx*? (##fx+ (##fxquotient ##max-fixnum 2) 1) 2) #f)
(check-eqv? (##fx*? (##fx- (##fxquotient ##min-fixnum 2) 1) 2) #f)
(check-eqv? (##fx*? 2 (##fx- (##fxquotient ##min-fixnum 2) 1)) #f)

(check-eqv? (##fx*? 3 (##fxquotient ##max-fixnum 3))
            (##fx* 3 (##fxquotient ##max-fixnum 3)))
(check-eqv? (##fx*? (##fxquotient ##max-fixnum 3) 3)
            (##fx* (##fxquotient ##max-fixnum 3) 3))
(check-eqv? (##fx*? (##fxquotient ##min-fixnum 3) 3)
            (##fx* (##fxquotient ##min-fixnum 3) 3))
(check-eqv? (##fx*? 3 (##fxquotient ##min-fixnum 3))
            (##fx* 3 (##fxquotient ##min-fixnum 3)))

(check-eqv? (##fx*? 3 (##fx+ (##fxquotient ##max-fixnum 3) 1)) #f)
(check-eqv? (##fx*? (##fx+ (##fxquotient ##max-fixnum 3) 1) 3) #f)
(check-eqv? (##fx*? (##fx- (##fxquotient ##min-fixnum 3) 1) 3) #f)
(check-eqv? (##fx*? 3 (##fx- (##fxquotient ##min-fixnum 3) 1)) #f)
