(include "#.scm")

(test-assert (not (eq? 123 42)))
(test-assert (not (eq? 0. 0)))
(test-assert (not (eq? -0. 0.)))
(test-assert (not (eq? #f #t)))
(test-assert (not (eq? #t #f)))
(test-assert (not (eq? #\a #\x)))
(test-assert (not (eq? 'HELLO 'hello)))
(test-assert (not (eq? '#() '())))
