(include "#.scm")

(test-assert (not (eqv? 123 42)))
(test-assert (not (eqv? 0. 0)))
(test-assert (not (eqv? -0. 0.)))
(test-assert (not (eqv? #f #t)))
(test-assert (not (eqv? #t #f)))
(test-assert (not (eqv? #\a #\x)))
(test-assert (not (eqv? 'HELLO 'hello)))
(test-assert (not (eqv? '#() '())))
