(include "#.scm")

(test-assert (not (equal? 123 42)))
(test-assert (not (equal? 0. 0)))
(test-assert (not (equal? -0. 0.)))
(test-assert (not (equal? #f #t)))
(test-assert (not (equal? #t #f)))
(test-assert (not (equal? #\a #\x)))
(test-assert (not (equal? 'HELLO 'hello)))
(test-assert (not (equal? '#() '())))
(test-assert (not (equal? '(1 2 3.) '(1 2 3))))
(test-assert (not (equal? '#(1 2 3.) '#(1 2 3))))
