# Copyright (c) 1994-2022 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/141
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 141\#.scm
MODULES_SCM = 141.scm 141.sld test/test.scm
MAIN_MODULES = 141
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
