# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _hamt/primitive-hamt
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = primitive-hamt\#.scm
MODULES_SCM = primitive-hamt.scm
MAIN_MODULES = primitive-hamt
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
