# Copyright (c) 2008-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _match
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _match\#.scm match-expand\#.scm
MODULES_SCM = _match.scm match-expand.scm _match-test.scm
MAIN_MODULES = _match match-expand
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
