# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/cxr
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = cxr.sld
MAIN_MODULES = cxr
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
