# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/28
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 28\#.scm
MODULES_SCM = 28.scm
MAIN_MODULES = 28
OTHER_RCFILES = makefile 28.sld 28-test.scm

include $(libfromhere)/module-common.mk
