# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/28
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 28\#.scm
MODULES_SCM = 28.scm 28.sld test/test.scm
MAIN_MODULES = 28
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
