(import (_test))
(import (srfi 144))


(define-syntax test-approx-eq
  (syntax-rules ()
    ((_ a b) 
     (test-assert (float-equal a b)))))

(define-syntax test-values-equal
  (syntax-rules ()
    ((_ a b)
     (let ((k (##values->list a))
           (j (##values->list b)))
       (test-approx-eq (car k) (car j))
       (test-approx-eq (cadr k) (cadr j))))))

(define (float-equal x y)
  (cond
    ((and (nan? x) (nan? y)) #t)
    ((nan? x) #f)
    ((nan? y) #f)
    (else
  (or
    (and (<= (abs (- x y)) 0.000002))
    (= x y)))))
 
(define-macro 
  (test-equivalent names arg prefix suffix)
  (define (sym . lst)
    (string->symbol
     (apply string-append
            (map (lambda (s) (if (symbol? s) (symbol->string s) s))
                 lst))))
  `(begin
     ,@(map (lambda (name)
         `(test-equal (,(sym prefix name suffix) ,@arg) (,name ,@arg)))
     names)))

(define-macro 
  (test-almost-equivalent names arg prefix suffix)
  (define (sym . lst)
    (string->symbol
     (apply string-append
            (map (lambda (s) (if (symbol? s) (symbol->string s) s))
                 lst))))
  `(begin
     ,@(map (lambda (name)
         `(test-approx-eq (,(sym prefix name suffix) ,@arg) (,name ,@arg))) names)))

(define-syntax single-number-tests
  (syntax-rules ()
    ((single-number-tests) (write 1))
    ((single-number-tests x . x*)
     (begin
       (cond 
         ((and (real? x) (inexact? x)) (test-equal (flonum x) x))
         ((exact? x) (test-equal (flonum x) (exact->inexact x)))
         (else (test-error #t (flonum x))))
       (test-equal (flinteger-exponent x)  (floor (flexponent x)))
       (if (< x 0) (test-equal (flsign-bit x) 1)
         (test-equal (flsign-bit x) 0))
       (cond ((finite? x)
              (test-equal (flinteger? x) (= x (floor x)))
              (test-equal (flpositive? x) (positive? x))
              (let-values (((y n) (flnormalized-fraction-exponent x)))
                (test-assert (exact? y))
                (test-assert (integer? n))
                (test-assert (<= 1/2 (abs y)))
                (test-assert (< y 1))
                (test-approx-eq (* y (expt 2 n)) x))
              (test-assert (<= (flexponent (abs x)) (log (abs x) 2)))
              (test-assert (<= (flinteger-exponent (abs x)) (log (abs x) 2)))
              )
             (else 
               (test-equal #f (flinteger? x))
               (test-equal #f (flpositive? x))))
       (if (integer? x)
         (test-equivalent (odd? even?) (x) fl ||)
         (begin
           (test-error #t (flodd? x))
           (test-error #t (fleven? x))))
       (when (not (nan? x))
           (test-equal (flfinite? x) (not (flinfinite? x))) ;; Sanity check
           (test-equal (flnormalized? x) (not (fldenormalized? x))) ;; sanity check
           (test-almost-equivalent
             (square sin 
             cos tan atan sinh cosh tanh) (x) fl ||)
          (if (<= (abs x) 1)
           (test-almost-equivalent
             (asin acos) (x) fl ||)
           (begin
           (test-assert (nan? (flasin x)))
           (test-assert (nan? (flacos x)))))
           (if (and (real? (atanh x)) (finite? (atanh x)))
             (test-equal (flatanh x) (atanh x))
             (test-assert (not (finite? (flatanh x)))))
                
           (test-approx-eq (flsqrt (abs x)) (sqrt (abs x)))
           (test-equal (flnumerator x) (flonum (numerator (##flonum->exact x))))
           (test-equal (fldenominator x) (flonum (denominator (##flonum->exact x))))
           (test-approx-eq (flexp2 x) (expt 2 x))
           (test-approx-eq (flexp-1 x) (- (exp x) 1))
           (test-equivalent
             (positive? negative? floor ceiling round truncate) (x) fl ||))
       (test-equivalent
         (infinite? finite? nan?) (x) fl ||)
       (test-equal (flcopysign 1.0 x) (flsgn x))
       (single-number-tests . x*)
       ))))

(define-syntax double-number-tests
  (syntax-rules ()
    ((_ x y)
     (begin
     (cond 
       ((< x y)
       (test-assert (<= (fladjacent x y) y))
       (test-assert (> (fladjacent x y) x))
       (test-assert (<= (fladjacent x y) (+ x 0.00002)))) 
       ((> x y)
           (test-assert (>= (fladjacent x y) y))
           (test-assert (< (fladjacent x y) x))
           (test-assert (>= (fladjacent x y) (- x 0.00002)))) 
       ((= x y) (test-assert (fladjacent x y) x)))
       (cond
         ((integer? y) (test-equal (make-flonum x y) (* x (expt 2 y))))
         (else (test-error #t (make-flonum x y))))
       (test-equal (abs (flcopysign x y)) (abs x))
       (cond
         ((< y 0) (test-assert (<= (flcopysign x y) 0)))
         ((> y 0) (test-assert (>= (flcopysign x y) 0))))
      (test-equivalence
        (= < > <= >=) (x y) fl ?)
      (test-equal (flunordered? x y) (flunoredered? y x)) ;; simple reflexivity test
      (test-almost-equivalent
        (max min + * - / abs) (x y) fl ||)
      (test-equal (abs (- x y)) (flabsdiff x y))
      (test-equal (max (- x y) 0) (flposdiff x y))
     ))))

(define (test-exists a)
  (test-equal a a))

(define e 2.718281828459045)
(define pi 3.1415926535897932384626433832795028841971)
(test-approx-eq fl-sqrt-2 1.4142135623730951)
(test-approx-eq fl-sqrt-3 1.7320508075688772)
(test-approx-eq fl-sqrt-5 2.23606797749979)
(test-approx-eq fl-sqrt-10 3.1622776601683795)
(test-approx-eq fl-e e)
(test-approx-eq fl-1/e 0.36787944117144233)
(test-approx-eq fl-e-pi/4 2.1932800507380152)
(test-approx-eq fl-log-2-e 1.4426950408889634)
(test-approx-eq fl-log10-e 0.4342944819032518)
(test-approx-eq fl-log-2 0.6931471805599453)
(test-approx-eq fl-1/log-2 1.4426950408889634)
(test-approx-eq fl-log-3 1.0986122886681098)
(test-approx-eq fl-log-pi 1.1447298858494002)
(test-approx-eq fl-log-10 2.302585092994046)
(test-approx-eq fl-1/log-10 0.43429448190325176)
(test-approx-eq fl-pi pi) ;; I know them by heart. no need to verify
(test-approx-eq fl-1/pi 0.3183098861837907)
(test-approx-eq fl-2pi 6.283185307179586)
(test-approx-eq fl-pi/2 1.5707963267948966)
(test-approx-eq fl-pi/4 0.7853981633974483)
(test-approx-eq fl-pi-squared 9.869604401089358)
(test-approx-eq fl-degree 0.017453292519943295)
(test-approx-eq fl-2/pi 0.6366197723675814)
(test-approx-eq fl-2/sqrt-pi 1.1283791670955126)
(test-approx-eq fl-1/sqrt-2 0.7071067811865475)
(test-approx-eq fl-cbrt-2 1.2599210498948734)
(test-approx-eq fl-4thrt-2 1.189207115002721)
(test-approx-eq fl-phi 1.618033988749895) ;; golden ratio
(test-approx-eq fl-log-phi 0.48121182505960347)
(test-approx-eq fl-euler 0.57721566490153286060651209008240243104215933593992) ;; according to https://en.wikipedia.org/wiki/Euler%27s_constant
(test-approx-eq fl-sin-1 0.8414709848078965)
(test-approx-eq fl-cos-1 0.5403023058681398)
(test-approx-eq fl-gamma-1/2 1.7724538509055159)
(test-approx-eq fl-gamma-1/3 2.678938534707748)
(test-approx-eq fl-gamma-2/3 1.3541179394264005)

(test-values-equal (flinteger-fraction 2.5) (values 2.0 0.5))
(test-values-equal (flinteger-fraction 2.75) (values 2.0 0.75))
(test-values-equal (flinteger-fraction 3.25) (values 3.0 0.25))

(test-approx-eq (flexponent 4.0) 2.0)
(test-approx-eq (flexponent 8.0) 3.0)
(test-equal 2 (flexponent 4.0))
(test-approx-eq (flexponent 2.0) 1.0)
(test-approx-eq (flexponent 4.0) 2.0)

(test-equal 0 (flsign-bit 0.0))
(test-equal 1 (flsign-bit -0.0))
(test-assert (flunordered? 1.0 +nan.0))

(test-assert (flunordered? 2.0 +nan.0))
(test-assert (flunordered? 2.0 -nan.0))

(test-assert (flinteger? 1.0))
(test-assert (not (flinteger? 1.5)))

(test-equal 2.0 (flcopysign 2.0 1.0))
(test-equal -2.0 (flcopysign 2.0 -1.0))



(test-assert (flfinite? 2.0))
(test-assert (flfinite? 3.0))
(test-assert (flfinite? 4.0))
(test-assert (flfinite? -1.0))
(test-assert (flfinite? -3.0))
(test-equal #f (flfinite? +nan.0))
(test-equal #f (flfinite? +inf.0))
(test-equal #f (flfinite? -inf.0))
(test-equal #f (flfinite? -nan.0))

(test-assert (flnan? +nan.0))
(test-assert (flnan? -nan.0))
(test-equal #f (flnan? 0.0))

(test-assert (flnormalized? 0.2))
(test-assert (fldenormalized? 0.0))
(test-assert (fldenormalized? (exact->inexact (expt 10 -385))))


(test-equal #f (fl= 1. 2.))
(test-equal #f (fl= 2. 2.03))
(test-equal #t (fl= -0. 0.))
(test-equal #f (fl= .1 .2))
(test-equal #f (fl= +nan.0 +inf.0))
(test-equal #f (fl= +nan.0 0.))
(test-equal #f (fl= +nan.0 0.))
(test-equal #f (fl= +nan.0 +nan.0))
(test-equal #f (fl= 1. 2.))
(test-equal #t (fl= +inf.0 +inf.0))

(test-equal #t (fl<= 1. 2.))
(test-equal #t (fl<= 2. 2.03))
(test-equal #t (fl<= -0. 0.))
(test-equal #t (fl<= .1 .2))
(test-equal #f (fl<= +nan.0 +inf.0))
(test-equal #f (fl<= +nan.0 0.))
(test-equal #f (fl<= +nan.0 0.))
(test-equal #f (fl<= +nan.0 +nan.0))
(test-equal #t (fl<= 1. 2.))
(test-equal #t (fl<= +inf.0 +inf.0))


(test-equal #t (fl< 1. 2.))
(test-equal #t (fl< 2. 2.03))
(test-equal #f (fl< -0. 0.))
(test-equal #t (fl< .1 .2))
(test-equal #f (fl< +nan.0 +inf.0))
(test-equal #f (fl< +nan.0 0.))
(test-equal #f (fl< +nan.0 0.))
(test-equal #f (fl< +nan.0 +nan.0))
(test-equal #t (fl< 1. 2.))
(test-equal #f (fl< +inf.0 +inf.0))
(test-equal #f (fl< +nan.0 -inf.0))
(test-equal #f (fl< +inf.0 -inf.0))

(test-equal #f (fl> 1. 2.))
(test-equal #f (fl> 2. 2.03))
(test-equal #f (fl> -0. 0.))
(test-equal #f (fl> .1 .2))
(test-approx-eq (flcbrt -8.0) -2.0)
(test-equal #f (fl> +nan.0 +inf.0))
(test-equal #f (fl> +nan.0 0.))
(test-equal #f (fl> +nan.0 0.))
(test-equal #f (fl> +nan.0 +nan.0))
(test-equal #f (fl> 1. 2.))
(test-equal #f (fl> +inf.0 +inf.0))
(test-equal #f (fl> +nan.0 -inf.0))
(test-equal #t (fl> +inf.0 -inf.0))

(test-equal #f (fl>= 1. 2.))
(test-equal #f (fl>= 2. 2.03))
(test-equal #t (fl>= -0. 0.))
(test-equal #f (fl>= .1 .2))
(test-equal #f (fl>= +nan.0 +inf.0))
(test-equal #f (fl>= +nan.0 0.))
(test-equal #f (fl>= +nan.0 0.))
(test-equal #f (fl>= +nan.0 +nan.0))
(test-equal #f (fl>= 1. 2.))
(test-equal #t (fl>= +inf.0 +inf.0))
(test-equal #f (fl>= +nan.0 -inf.0))
(test-equal #t (fl>= +inf.0 -inf.0))

(begin
  (test-equal #t (flinteger? 1.))
  (test-equal #t (flinteger? 2.))
  (test-equal #t (flinteger? 3.))
  (test-equal #t (flinteger? 4.))
  (test-equal #t (flinteger? 5.))
  (test-equal #t (flinteger? 6.))
  (test-equal #f (flinteger? 6.5))
  (test-equal #f (flinteger? -.325))
  (test-equal #f (flinteger? +inf.0))
  (test-equal #f (flinteger? +nan.0))
  (test-equal #f (flinteger? -inf.0))
  (test-equal #f (flinteger? +nan.0)))

(begin
  (test-equal #f (flzero? 1.))
  (test-equal #f (flzero? 2.))
  (test-equal #f (flzero? 3.))
  (test-equal #f (flzero? 4.))
  (test-equal #f (flzero? 5.))
  (test-equal #f (flzero? 6.))
  (test-equal #f (flzero? 6.5))
  (test-equal #f (flzero? -.325))
  (test-equal #f (flzero? +inf.0))
  (test-equal #f (flzero? +nan.0))
  (test-equal #f (flzero? -inf.0))
  (test-equal #f (flzero? +nan.0)))
(begin
  (test-equal #t (flpositive? 1.))
  (test-equal #t (flpositive? 2.))
  (test-equal #t (flpositive? 3.))
  (test-equal #t (flpositive? 4.))
  (test-equal #t (flpositive? 5.))
  (test-equal #t (flpositive? 6.))
  (test-equal #t (flpositive? 6.5))
  (test-equal #f (flpositive? -.325))
  (test-equal #t (flpositive? +inf.0))
  (test-equal #f (flpositive? +nan.0))
  (test-equal #f (flpositive? -inf.0))
  (test-equal #f (flpositive? +nan.0)))
(begin
  (test-equal #f (flnegative? 1.))
  (test-equal #f (flnegative? 2.))
  (test-equal #f (flnegative? 3.))
  (test-equal #f (flnegative? 4.))
  (test-equal #f (flnegative? 5.))
  (test-equal #f (flnegative? 6.))
  (test-equal #f (flnegative? 6.5))
  (test-equal #t (flnegative? -.325))
  (test-equal #f (flnegative? +inf.0))
  (test-equal #f (flnegative? +nan.0))
  (test-equal #t (flnegative? -inf.0))
  (test-equal #f (flnegative? +nan.0)))
(begin
  (test-equal #t (flfinite? 1.))
  (test-equal #t (flfinite? 2.))
  (test-equal #t (flfinite? 3.))
  (test-equal #t (flfinite? 4.))
  (test-equal #t (flfinite? 5.))
  (test-equal #t (flfinite? 6.))
  (test-equal #t (flfinite? 6.5))
  (test-equal #t (flfinite? -.325))
  (test-equal #f (flfinite? +inf.0))
  (test-equal #f (flfinite? +nan.0))
  (test-equal #f (flfinite? -inf.0))
  (test-equal #f (flfinite? +nan.0)))
(begin
  (test-equal #f (flinfinite? 1.))
  (test-equal #f (flinfinite? 2.))
  (test-equal #f (flinfinite? 3.))
  (test-equal #f (flinfinite? 4.))
  (test-equal #f (flinfinite? 5.))
  (test-equal #f (flinfinite? 6.))
  (test-equal #f (flinfinite? 6.5))
  (test-equal #f (flinfinite? -.325))
  (test-equal #t (flinfinite? +inf.0))
  (test-equal #f (flinfinite? +nan.0))
  (test-equal #t (flinfinite? -inf.0))
  (test-equal #f (flinfinite? +nan.0)))

(begin
  (test-equal #f (flnan? 1.))
  (test-equal #f (flnan? 2.))
  (test-equal #f (flnan? 3.))
  (test-equal #f (flnan? 4.))
  (test-equal #f (flnan? 5.))
  (test-equal #f (flnan? 6.))
  (test-equal #f (flnan? 6.5))
  (test-equal #f (flnan? -0.325))
  (test-equal #f (flnan? +inf.0))
  (test-equal #t (flnan? +nan.0))
  (test-equal #f (flnan? -inf.0))
  (test-equal #t (flnan? +nan.0)))


(begin
  (test-approx-eq 1. (flmax 1. 0.))
  (test-approx-eq 2. (flmax 2. -inf.0))
  (test-approx-eq +nan.0 (flmax 3. +nan.0))
  (test-approx-eq 4. (flmax 4. .5))
  (test-approx-eq 5. (flmax 5. -.1))
  (test-approx-eq 6. (flmax 6. -.3))
  (test-approx-eq 6.5 (flmax 6.5 5.6))
  (test-approx-eq -.325 (flmax -.325))
  (test-approx-eq +inf.0 (flmax +inf.0 -inf.0))
  (test-approx-eq +nan.0 (flmax +nan.0 +nan.0))
  (test-approx-eq 0. (flmax -inf.0 0.))
  (test-approx-eq +nan.0 (flmax +nan.0 .7)))

(begin
  (test-approx-eq 0. (flmin 1. 0.))
  (test-approx-eq -inf.0 (flmin 2. -inf.0))
  (test-approx-eq +nan.0 (flmin 3. +nan.0))
  (test-approx-eq .5 (flmin 4. .5))
  (test-approx-eq -.1 (flmin 5. -.1))
  (test-approx-eq -.3 (flmin 6. -.3))
  (test-approx-eq 5.6 (flmin 6.5 5.6))
  (test-approx-eq -.325 (flmin -.325))
  (test-approx-eq -inf.0 (flmin +inf.0 -inf.0))
  (test-approx-eq +nan.0 (flmin +nan.0 +nan.0))
  (test-approx-eq -inf.0 (flmin -inf.0 0.))
  (test-approx-eq +nan.0 (flmin +nan.0 .7)))

(begin
  (test-approx-eq 1. (fl+ 1. 0.))
  (test-approx-eq -inf.0 (fl+ 2. -inf.0))
  (test-approx-eq +nan.0 (fl+ 3. +nan.0))
  (test-approx-eq 4.5 (fl+ 4. .5))
  (test-approx-eq 4.9 (fl+ 5. -.1))
  (test-approx-eq 5.7 (fl+ 6. -.3))
  (test-approx-eq 12.1 (fl+ 6.5 5.6))
  (test-approx-eq -.325 (fl+ -.325))
  (test-approx-eq +nan.0 (fl+ +inf.0 -inf.0))
  (test-approx-eq +nan.0 (fl+ +nan.0 +nan.0))
  (test-approx-eq -inf.0 (fl+ -inf.0 0.))
  (test-approx-eq +nan.0 (fl+ +nan.0 .7)))

(begin
  (test-approx-eq 0. (fl* 1. 0.))
  (test-approx-eq -inf.0 (fl* 2. -inf.0))
  (test-approx-eq +nan.0 (fl* 3. +nan.0))
  (test-approx-eq 2. (fl* 4. .5))
  (test-approx-eq -.5 (fl* 5. -.1))
  (test-approx-eq -1.7999999999999998 (fl* 6. -.3))
  (test-approx-eq 36.4 (fl* 6.5 5.6))
  (test-approx-eq -.325 (fl* -.325))
  (test-approx-eq -inf.0 (fl* +inf.0 -inf.0))
  (test-approx-eq +nan.0 (fl* +nan.0 +nan.0))
  (test-approx-eq +nan.0 (fl* -inf.0 0.))
  (test-approx-eq +nan.0 (fl* +nan.0 .7)))

(begin
  (test-approx-eq 1.02 (fl+* 1. 0. 1.02))
  (test-approx-eq -inf.0 (fl+* 2. -inf.0 .2))
  (test-approx-eq +nan.0 (fl+* 3. +nan.0 .2))
  (test-approx-eq 8.5 (fl+* 4. 2. .5))
  (test-approx-eq +nan.0 (fl+* 5. -.1 +nan.0))
  (test-approx-eq +nan.0 (fl+* +nan.0 6. -.3))
  (test-approx-eq 7.55 (fl+* .3 6.5 5.6))
  (test-approx-eq .35500000000000004 (fl+* .2 3.4 -.325))
  (test-approx-eq +nan.0 (fl+* +inf.0 0. -inf.0))
  (test-approx-eq +nan.0 (fl+* +nan.0 1. +nan.0))
  (test-approx-eq +inf.0 (fl+* -inf.0 -inf.0 0.))
  (test-approx-eq +nan.0 (fl+* +nan.0 +inf.0 .7)))

(begin
  (test-approx-eq 1. (flmax 1.))
  (test-approx-eq 2. (flmax 2.))
  (test-approx-eq +nan.0 (flmax +nan.0))
  (test-approx-eq .5 (flmax .5))
  (test-approx-eq -.1 (flmax -.1))
  (test-approx-eq 6. (flmax 6.))
  (test-approx-eq 6.5 (flmax 6.5))
  (test-approx-eq -.325 (flmax -.325))
  (test-approx-eq -inf.0 (flmax -inf.0))
  (test-approx-eq +nan.0 (flmax +nan.0))
  (test-approx-eq -inf.0 (flmax -inf.0))
  (test-approx-eq +nan.0 (flmax +nan.0)))

(begin
  (test-approx-eq 1. (flmin 1.))
  (test-approx-eq 2. (flmin 2.))
  (test-approx-eq +nan.0 (flmin +nan.0))
  (test-approx-eq .5 (flmin .5))
  (test-approx-eq -.1 (flmin -.1))
  (test-approx-eq 6. (flmin 6.))
  (test-approx-eq 6.5 (flmin 6.5))
  (test-approx-eq -.325 (flmin -.325))
  (test-approx-eq -inf.0 (flmin -inf.0))
  (test-approx-eq +nan.0 (flmin +nan.0))
  (test-approx-eq -inf.0 (flmin -inf.0))
  (test-approx-eq +nan.0 (flmin +nan.0)))

(begin
  (test-approx-eq 1. (fl+ 1.))
  (test-approx-eq 2. (fl+ 2.))
  (test-approx-eq +nan.0 (fl+ +nan.0))
  (test-approx-eq .5 (fl+ .5))
  (test-approx-eq -.1 (fl+ -.1))
  (test-approx-eq 6. (fl+ 6.))
  (test-approx-eq 6.5 (fl+ 6.5))
  (test-approx-eq -.325 (fl+ -.325))
  (test-approx-eq -inf.0 (fl+ -inf.0))
  (test-approx-eq +nan.0 (fl+ +nan.0))
  (test-approx-eq -inf.0 (fl+ -inf.0))
  (test-approx-eq +nan.0 (fl+ +nan.0)))

(begin
  (test-approx-eq 1. (fl* 1.))
  (test-approx-eq 2. (fl* 2.))
  (test-approx-eq +nan.0 (fl* +nan.0))
  (test-approx-eq .5 (fl* .5))
  (test-approx-eq -.1 (fl* -.1))
  (test-approx-eq 6. (fl* 6.))
  (test-approx-eq 6.5 (fl* 6.5))
  (test-approx-eq -.325 (fl* -.325))
  (test-approx-eq -inf.0 (fl* -inf.0))
  (test-approx-eq +nan.0 (fl* +nan.0))
  (test-approx-eq -inf.0 (fl* -inf.0))
  (test-approx-eq +nan.0 (fl* +nan.0)))

(begin
  (test-approx-eq 1. (flabs 1.))
  (test-approx-eq 2. (flabs 2.))
  (test-approx-eq 0. (flabs 0.))
  (test-approx-eq .5 (flabs .5))
  (test-approx-eq .1 (flabs -.1))
  (test-approx-eq 6. (flabs 6.))
  (test-approx-eq 6.5 (flabs 6.5))
  (test-approx-eq .325 (flabs -.325))
  (test-approx-eq 0. (flabs -0.))
  (test-approx-eq 0. (flabs -0.))
  (test-approx-eq 0. (flabs -0.))
  (test-approx-eq 0. (flabs -0.)))
(begin
  (test-approx-eq 1. (flfloor 1.))
  (test-approx-eq 2. (flfloor 2.))
  (test-approx-eq 0. (flfloor 0.))
  (test-approx-eq 0. (flfloor .5))
  (test-approx-eq -1. (flfloor -.1))
  (test-approx-eq 6. (flfloor 6.))
  (test-approx-eq 6. (flfloor 6.5))
  (test-approx-eq -1. (flfloor -.325))
  (test-approx-eq -0. (flfloor -0.))
  (test-approx-eq -0. (flfloor -0.))
  (test-approx-eq -0. (flfloor -0.))
  (test-approx-eq -0. (flfloor -0.)))

(begin
  (test-approx-eq 1. (flceiling 1.))
  (test-approx-eq 2. (flceiling 2.))
  (test-approx-eq 0. (flceiling 0.))
  (test-approx-eq 1. (flceiling .5))
  (test-approx-eq -0. (flceiling -.1))
  (test-approx-eq 6. (flceiling 6.))
  (test-approx-eq 7. (flceiling 6.5))
  (test-approx-eq -0. (flceiling -.325))
  (test-approx-eq -0. (flceiling -0.))
  (test-approx-eq -0. (flceiling -0.))
  (test-approx-eq -0. (flceiling -0.))
  (test-approx-eq -0. (flceiling -0.)))

(begin
  (test-approx-eq 1. (flround 1.))
  (test-approx-eq 2. (flround 2.))
  (test-approx-eq 0. (flround 0.))
  (test-approx-eq 0. (flround .5))
  (test-approx-eq -0. (flround -.1))
  (test-approx-eq 6. (flround 6.))
  (test-approx-eq 6. (flround 6.5))
  (test-approx-eq -0. (flround -.325))
  (test-approx-eq -0. (flround -0.))
  (test-approx-eq -0. (flround -0.))
  (test-approx-eq -0. (flround -0.))
  (test-approx-eq -0. (flround -0.)))

(begin
  (test-approx-eq 1. (fltruncate 1.))
  (test-approx-eq 2. (fltruncate 2.))
  (test-approx-eq 0. (fltruncate 0.))
  (test-approx-eq 0. (fltruncate .5))
  (test-approx-eq 0. (fltruncate -.1))
  (test-approx-eq 6. (fltruncate 6.))
  (test-approx-eq 6. (fltruncate 6.5))
  (test-approx-eq 0. (fltruncate -.325))
  (test-approx-eq -0. (fltruncate -0.))
  (test-approx-eq -0. (fltruncate -0.))
  (test-approx-eq -0. (fltruncate -0.))
  (test-approx-eq -0. (fltruncate -0.)))

(begin
  (test-approx-eq 2.718281828459045 (flexp 1.))
  (test-approx-eq 7.38905609893065 (flexp 2.))
  (test-approx-eq +nan.0 (flexp +nan.0))
  (test-approx-eq 1.6487212707001282 (flexp .5))
  (test-approx-eq .9048374180359595 (flexp -.1))
  (test-approx-eq 403.4287934927351 (flexp 6.))
  (test-approx-eq 665.1416330443618 (flexp 6.5))
  (test-approx-eq .7225273536420722 (flexp -.325))
  (test-approx-eq 0. (flexp -inf.0))
  (test-approx-eq +nan.0 (flexp +nan.0))
  (test-approx-eq 0. (flexp -inf.0))
  (test-approx-eq +nan.0 (flexp +nan.0)))
(begin
  (test-approx-eq 1. (flsquare 1.))
  (test-approx-eq 4. (flsquare 2.))
  (test-approx-eq +nan.0 (flsquare +nan.0))
  (test-approx-eq .25 (flsquare .5))
  (test-approx-eq .010000000000000002 (flsquare -.1))
  (test-approx-eq 36. (flsquare 6.))
  (test-approx-eq 42.25 (flsquare 6.5))
  (test-approx-eq .10562500000000001 (flsquare -.325))
  (test-approx-eq +inf.0 (flsquare -inf.0))
  (test-approx-eq +nan.0 (flsquare +nan.0))
  (test-approx-eq +inf.0 (flsquare -inf.0))
  (test-approx-eq +nan.0 (flsquare +nan.0)))

(begin
  (test-approx-eq 1. (flsqrt 1.))
  (test-approx-eq 1.4142135623730951 (flsqrt 2.))
  (test-approx-eq +nan.0 (flsqrt +nan.0))
  (test-approx-eq .7071067811865476 (flsqrt .5))
  (test-approx-eq +nan.0 (flsqrt -.1))
  (test-approx-eq 2.449489742783178 (flsqrt 6.))
  (test-approx-eq 2.5495097567963922 (flsqrt 6.5))
  (test-approx-eq +nan.0 (flsqrt -.325))
  (test-approx-eq +nan.0 (flsqrt -inf.0))
  (test-approx-eq +nan.0 (flsqrt +nan.0))
  (test-approx-eq +nan.0 (flsqrt -inf.0))
  (test-approx-eq +nan.0 (flsqrt +nan.0)))

(begin
  (test-approx-eq 1.718281828459045 (flexp-1 1.))
  (test-approx-eq 6.38905609893065 (flexp-1 2.))
  (test-approx-eq +nan.0 (flexp-1 +nan.0))
  (test-approx-eq .6487212707001282 (flexp-1 .5))
  (test-approx-eq -.09516258196404043 (flexp-1 -.1))
  (test-approx-eq 402.4287934927351 (flexp-1 6.))
  (test-approx-eq 664.1416330443618 (flexp-1 6.5))
  (test-approx-eq -.2774726463579278 (flexp-1 -.325))
  (test-approx-eq -1. (flexp-1 -inf.0))
  (test-approx-eq +nan.0 (flexp-1 +nan.0))
  (test-approx-eq -1. (flexp-1 -inf.0))
  (test-approx-eq +nan.0 (flexp-1 +nan.0)))

(begin
  (test-approx-eq 2. (flexp2 1.))
  (test-approx-eq 4. (flexp2 2.))
  (test-approx-eq +nan.0 (flexp2 +nan.0))
  (test-approx-eq 1.4142135623730951 (flexp2 .5))
  (test-approx-eq .9330329915368074 (flexp2 -.1))
  (test-approx-eq 64. (flexp2 6.))
  (test-approx-eq 90.50966799187809 (flexp2 6.5))
  (test-approx-eq .7982983863566498 (flexp2 -.325))
  (test-approx-eq 0. (flexp2 -inf.0))
  (test-approx-eq +nan.0 (flexp2 +nan.0))
  (test-approx-eq 0. (flexp2 -inf.0))
  (test-approx-eq +nan.0 (flexp2 +nan.0)))


(test-assert (nan? (flasin 2.0)))

(test-approx-eq 2.0 (flcbrt 8.0)) 
(test-approx-eq -1.0 (flcbrt -1.0)) 
(test-approx-eq 1.0 (flcbrt 1.0)) 
(test-assert (nan? (flcbrt +nan.0)) )
(test-equal +inf.0 (flcbrt +inf.0)) 
(test-equal -inf.0 (flcbrt -inf.0)) 

(test-equal 2. (flmax 1. 2.)) 
(test-equal 2.3 (flmax 2.3 2.1 .2)) 
(test-assert (nan? (flmax 3.4 2. +nan.0)) )
(test-equal +inf.0 (flmax +inf.0 -inf.0 0.)) 
(test-assert (nan? (flmax 2. +nan.0 +inf.0)))

(test-equal 1. (flmin 1. 2.)) 
(test-equal .2 (flmin 2.3 2.1 .2)) 
(test-assert (nan? (flmin 3.4 2. +nan.0)) )
(test-equal -inf.0 (flmin +inf.0 -inf.0 0.)) 
(test-assert (nan? (flmin 2. +nan.0 +inf.0)))


(test-approx-eq 3. (fl+ 1. 2.)) 
(test-approx-eq 4.6 (fl+ 2.3 2.1 0.2)) 
(test-assert (nan? (fl+ 3.4 2. +nan.0))) 
(test-assert (nan? (fl+ +inf.0 -inf.0 0.))) 
(test-approx-eq 7. (fl+ 1.2 2.3 3.5)) 
(test-assert (nan? (fl+ 2. +nan.0 +inf.0)))

(test-exists fl-greatest)
(test-exists fl-least)
(test-exists fl-epsilon)
(test-exists fl-fast-fl+*)
(test-equal fl-integer-exponent-zero (flinteger-exponent 0.0))
(test-equal fl-integer-exponent-nan (flinteger-exponent +nan.0))

(single-number-tests 1.0)
(single-number-tests -1.0)
(single-number-tests -2.0)
(single-number-tests 2.0)
(double-number-tests 0.1 fl-pi)
(double-number-tests fl-pi fl-e)
(single-number-tests 1.0 2.0 3.0 +nan.0)
