# Copyright (c) 2021-2022 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/151
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 151\#.scm
MODULES_SCM = 151.scm 151.sld test/test.scm
MAIN_MODULES = 151
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
