(include "#.scm")

(test-eq #t (table? (make-table)))
(test-eq #f (table? '()))
(test-equal '((a . 1) (b . 2))
 (list-sort (lambda (x y) (< (cdr x) (cdr y)))
            (table->list (list->table '((a . 1) (b . 2) (a . 3))))))

(test-equal '(1 2 4 1 4 2 2)
 (let* ((left (list->table '((a . 1) (b . 2))))
        (right (list->table '((a . 4) (c . 5))))
        (keep (table-merge left right))
        (replace (table-merge left right #t)))
   (list (table-ref keep 'a) (table-ref keep 'b)
         (table-ref replace 'a) (table-ref left 'a)
         (table-ref right 'a) (table-length left) (table-length right))))
(test-assert
 (let* ((left (list->table '((a . 1))))
        (right (list->table '((a . 4) (b . 2)))))
   (and (eq? left (table-merge! left right))
        (= 1 (table-ref left 'a)) (= 2 (table-ref left 'b))
        (eq? left (table-merge! left right #t))
        (= 4 (table-ref left 'a)))))
(test-equal '(1 2 missing)
 (let* ((t (make-table test: string-ci=?))
        (unused (table-set! t "A" 1))
        (copy (table-copy t)))
   (table-set! copy "a" 2)
   (let ((before (list (table-ref t "a") (table-ref copy "A"))))
     (table-set! copy "A")
     (append before (list (table-ref copy "a" 'missing))))))
(test-equal '(2 5)
 (let ((count 0) (sum 0) (t (list->table '((a . 2) (b . 3)))))
   (table-for-each (lambda (key value)
                     (test-assert (memq key '(a b)))
                     (set! count (+ count 1))
                     (set! sum (+ sum value))) t)
   (list count sum)))
(test-error type-exception? (table-merge #f (make-table)))
(test-error type-exception? (table-merge! (make-table) #f))
