# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/digest
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = digest\#.scm
MODULES_SCM = digest.scm digest-test.scm
MAIN_MODULES = digest
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
