# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/char
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = char.sld
MAIN_MODULES = char
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
