
(define-macro (hygiene-environment-make-proc name gsi-name gsc-name)
 `(begin
    (define-macro (,name cte-obj . args)
       (let ((name1 ',gsi-name)
             (name2 ',gsc-name)
             (cte   (gensym 'cte)))
         `(let ((,cte ,cte-obj))
            (if (and (##vector? ,cte)
                     (##fx> (##vector-length ,cte) 1)
                     (##table? (##vector-ref ,cte 0)))
                (,name1 ,cte ,@args)
                (,name2 ,cte ,@args)))))
    (define-macro (,(##make-full-name "##" name) cte-obj . args)
       (let ((name1 ',(##make-full-name "##" gsi-name))
             (name2 ',(##make-full-name "##" gsc-name))
             (cte   (gensym 'cte)))
         `(let ((,cte ,cte-obj))
            (if (and (##vector? ,cte)
                     (##fx> (##vector-length ,cte) 1)
                     (##table? (##vector-ref ,cte 0)))
                (,name1 ,cte ,@args)
                (,name2 ,cte ,@args)))))))

(hygiene-environment-make-proc hygiene-environment-local-cte henv-local-cte hcte-local-cte)
(hygiene-environment-make-proc hygiene-environment-global-name henv-global-name hcte-global-name)
(hygiene-environment-make-proc hygiene-environment-top? henv-top? hcte-top?)
(hygiene-environment-make-proc hygiene-environment-top-cte henv-top-cte hcte-top-cte)
(hygiene-environment-make-proc hygiene-environment-top-cte-global-binding-table henv-top-cte-global-binding-table hcte-top-cte-global-binding-table)
(hygiene-environment-make-proc hygiene-environment-top-cte-global-binding-table-ref henv-top-cte-global-binding-table-ref hcte-top-cte-global-binding-table-ref)
(hygiene-environment-make-proc hygiene-environment-ctx-ref henv-ctx-ref hcte-ctx-ref)
(hygiene-environment-make-proc hygiene-environment-add-new-local-binding! henv-add-new-local-binding! hcte-add-new-local-binding!)
(hygiene-environment-make-proc hygiene-environment-add-new-top-level-binding! henv-add-new-top-level-binding! hcte-add-new-top-level-binding!)
(hygiene-environment-make-proc hygiene-environment-add-variable-cte henv-add-variable-cte hcte-add-variable-cte)
(hygiene-environment-make-proc hygiene-environment-add-macro-cte henv-add-macro-cte hcte-add-macro-cte)
(hygiene-environment-make-proc hygiene-environment-add-core-macro-cte henv-add-core-macro-cte hcte-add-core-macro-cte)
(hygiene-environment-make-proc top-hygiene-environment-add-macro-cte! top-henv-add-macro-cte! top-hcte-add-macro-cte!)
(hygiene-environment-make-proc top-hygiene-environment-add-core-macro-cte! top-henv-add-core-macro-cte! top-hcte-add-core-macro-cte!)
(hygiene-environment-make-proc hygiene-environment-process-namespace henv-process-namespace hcte-process-namespace)
(hygiene-environment-make-proc top-hygiene-environment-process-namespace! top-henv-process-namespace! top-hcte-process-namespace!)


