;==============================================================================

; File: "Xlib#.scm", Time-stamp: <2008-11-24 16:19:08 feeley>

; Copyright (c) 2005-2008 by Marc Feeley, All Rights Reserved.

;==============================================================================

(##namespace ("Xlib#"

; procedures and variables
Button1MotionMask
Button2MotionMask
Button3MotionMask
Button4MotionMask
Button5MotionMask
ButtonMotionMask
ButtonPressMask
ButtonReleaseMask
CirculateNotify
CirculateRequest
ClientMessage
ColormapChangeMask
ColormapNotify
ConfigureNotify
ConfigureRequest
CreateNotify
DestroyNotify
EnterWindowMask
Expose
ExposureMask
FocusChangeMask
FocusIn
FocusOut
GCArcMode
GCBackground
GCCapStyle
GCClipMask
GCClipXOrigin
GCClipYOrigin
GCDashList
GCDashOffset
GCFillRule
GCFillStyle
GCFont
GCForeground
GCFunction
GCGraphicsExposures
GCJoinStyle
GCLineStyle
GCLineWidth
GCPlaneMask
GCStipple
GCSubwindowMode
GCTile
GCTileStipXOrigin
GCTileStipYOrigin
GraphicsExpose
GravityNotify
KeyPressMask
KeyReleaseMask
KeymapNotify
KeymapStateMask
LeaveWindowMask
MapNotify
MapRequest
MappingNotify
NoEventMask
NoExpose
OwnerGrabButtonMask
PointerMotionHintMask
PointerMotionMask
PropertyChangeMask
PropertyNotify
ReparentNotify
ResizeRedirectMask
ResizeRequest
SelectionClear
SelectionNotify
SelectionRequest
StructureNotifyMask
SubstructureNotifyMask
SubstructureRedirectMask
UnmapNotify
VisibilityChangeMask
VisibilityNotify
XAllocColor
XBlackPixel
XChangeGC
XCheckMaskEvent
XClearWindow
XCloseDisplay
XColor-blue
XColor-blue-set!
XColor-green
XColor-green-set!
XColor-pixel
XColor-pixel-set!
XColor-red
XColor-red-set!
XConnectionNumber
XCreateGC
XCreateSimpleWindow
XDefaultColormapOfScreen
XDefaultGC
XDefaultGCOfScreen
XDefaultRootWindow
XDefaultScreen
XDefaultVisual
XDefaultVisualOfScreen
XDrawString
XFillArc
XFillRectangle
XFlush
XFontStruct-ascent
XFontStruct-descent
XFontStruct-fid
XGCValues-background
XGCValues-background-set!
XGCValues-font
XGCValues-font-set!
XGCValues-foreground
XGCValues-foreground-set!
XGetGCValues
XLoadFont
XLoadQueryFont
XMapWindow
XOpenDisplay
XParseColor
XQueryFont
XRootWindow
XRootWindowOfScreen
XScreenOfDisplay
XSelectInput
XTextWidth
XWhitePixel
convert-XEvent
make-XColor-box
make-XGCValues-box

))

;==============================================================================
