herefromlib = srfi/219
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 219\#.scm
MODULES_SCM = 219.scm 219.sld test/test.scm
MAIN_MODULES = 219
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
