# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/8
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 8\#.scm
MODULES_SCM = 8.scm 8.sld 8-test.scm
MAIN_MODULES = 8
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
