herefromlib = srfi/128
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 128\#.scm
MODULES_SCM = 128.scm 128.sld 128-impl.scm 162-impl.scm default.scm test/test.scm
MAIN_MODULES = 128
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
