#! /bin/sh

scale_icon()
{
  convert Icon-unscaled.png -resize $1x$1 -alpha remove $2
}

tiff2png -force Icon-unscaled.tiff

scale_icon 29   Icon-29.png
scale_icon 40   Icon-40.png
scale_icon 57   Icon-57.png
scale_icon 72   Icon-72.png
scale_icon 76   Icon-76.png
scale_icon 87   Icon-87.png
scale_icon 120  Icon-120.png
scale_icon 152  Icon-152.png
scale_icon 180  Icon-180.png
scale_icon 512  Icon-512.png
scale_icon 1024 Icon-1024.png
