#ifdef ___LINKER_INFO
; File: "repl-server.m", produced by Gambit-C v4.7.3
(
407003
" repl-server"
((" repl-server"))
(
"cr-lf"
"input"
"normal"
"output"
"repl"
"repl-pump"
"repl-server"
"repl-service"
"stdin"
"stdout"
)
(
"direction"
"eol-encoding"
"permanent-close"
"reuse-address"
"server-address"
"test"
)
(
" repl-server"
"repl-server#ide-repl-pump"
"repl-server#make-ide-repl-ports"
"repl-server#repl-channel-table"
"repl-server#repl-server"
"repl-server#repl-server-address"
"repl-server#setup-ide-repl-channel"
)
(
"##thread-make-repl-channel"
"repl-server#repl-server-start"
)
(
"##call-with-values"
"##default-thread-make-repl-channel"
"##make-repl-channel-ports"
"##repl-debug-main"
"##thread-interrupt!"
"##vector-set!"
"char=?"
"close-output-port"
"display"
"eq?"
"equal?"
"for-each"
"force-output"
"make-mutex"
"make-table"
"make-thread"
"make-thread-group"
"mutex-lock!"
"mutex-unlock!"
"open-string-pipe"
"open-tcp-server"
"read"
"read-char"
"read-line"
"table-ref"
"table-set!"
"thread-group->thread-list"
"thread-start!"
"thread-thread-group"
"with-exception-catcher"
"write-char"
)
 ()
)
#else
#define ___VERSION 407003
#define ___MODULE_NAME " repl-server"
#define ___LINKER_ID ____20_repl_2d_server
#define ___MH_PROC ___H__20_repl_2d_server
#define ___SCRIPT_LINE 0
#define ___SYMCOUNT 10
#define ___KEYCOUNT 6
#define ___GLOCOUNT 40
#define ___SUPCOUNT 9
#define ___CNSCOUNT 8
#define ___SUBCOUNT 3
#define ___LBLCOUNT 131
#define ___OFDCOUNT 3
#define ___MODDESCR ___REF_SUB(2)
#include "gambit.h"

___NEED_SYM(___S_cr_2d_lf)
___NEED_SYM(___S_input)
___NEED_SYM(___S_normal)
___NEED_SYM(___S_output)
___NEED_SYM(___S_repl)
___NEED_SYM(___S_repl_2d_pump)
___NEED_SYM(___S_repl_2d_server)
___NEED_SYM(___S_repl_2d_service)
___NEED_SYM(___S_stdin)
___NEED_SYM(___S_stdout)

___NEED_KEY(___K_direction)
___NEED_KEY(___K_eol_2d_encoding)
___NEED_KEY(___K_permanent_2d_close)
___NEED_KEY(___K_reuse_2d_address)
___NEED_KEY(___K_server_2d_address)
___NEED_KEY(___K_test)

___NEED_GLO(___G__20_repl_2d_server)
___NEED_GLO(___G__23__23_call_2d_with_2d_values)
___NEED_GLO(___G__23__23_default_2d_thread_2d_make_2d_repl_2d_channel)
___NEED_GLO(___G__23__23_make_2d_repl_2d_channel_2d_ports)
___NEED_GLO(___G__23__23_repl_2d_debug_2d_main)
___NEED_GLO(___G__23__23_thread_2d_interrupt_21_)
___NEED_GLO(___G__23__23_thread_2d_make_2d_repl_2d_channel)
___NEED_GLO(___G__23__23_vector_2d_set_21_)
___NEED_GLO(___G_char_3d__3f_)
___NEED_GLO(___G_close_2d_output_2d_port)
___NEED_GLO(___G_display)
___NEED_GLO(___G_eq_3f_)
___NEED_GLO(___G_equal_3f_)
___NEED_GLO(___G_for_2d_each)
___NEED_GLO(___G_force_2d_output)
___NEED_GLO(___G_make_2d_mutex)
___NEED_GLO(___G_make_2d_table)
___NEED_GLO(___G_make_2d_thread)
___NEED_GLO(___G_make_2d_thread_2d_group)
___NEED_GLO(___G_mutex_2d_lock_21_)
___NEED_GLO(___G_mutex_2d_unlock_21_)
___NEED_GLO(___G_open_2d_string_2d_pipe)
___NEED_GLO(___G_open_2d_tcp_2d_server)
___NEED_GLO(___G_read)
___NEED_GLO(___G_read_2d_char)
___NEED_GLO(___G_read_2d_line)
___NEED_GLO(___G_repl_2d_server_23_ide_2d_repl_2d_pump)
___NEED_GLO(___G_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___NEED_GLO(___G_repl_2d_server_23_repl_2d_channel_2d_table)
___NEED_GLO(___G_repl_2d_server_23_repl_2d_server)
___NEED_GLO(___G_repl_2d_server_23_repl_2d_server_2d_address)
___NEED_GLO(___G_repl_2d_server_23_repl_2d_server_2d_start)
___NEED_GLO(___G_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___NEED_GLO(___G_table_2d_ref)
___NEED_GLO(___G_table_2d_set_21_)
___NEED_GLO(___G_thread_2d_group_2d__3e_thread_2d_list)
___NEED_GLO(___G_thread_2d_start_21_)
___NEED_GLO(___G_thread_2d_thread_2d_group)
___NEED_GLO(___G_with_2d_exception_2d_catcher)
___NEED_GLO(___G_write_2d_char)

___BEGIN_SYM
___DEF_SYM(0,___S_cr_2d_lf,"cr-lf")
___DEF_SYM(1,___S_input,"input")
___DEF_SYM(2,___S_normal,"normal")
___DEF_SYM(3,___S_output,"output")
___DEF_SYM(4,___S_repl,"repl")
___DEF_SYM(5,___S_repl_2d_pump,"repl-pump")
___DEF_SYM(6,___S_repl_2d_server,"repl-server")
___DEF_SYM(7,___S_repl_2d_service,"repl-service")
___DEF_SYM(8,___S_stdin,"stdin")
___DEF_SYM(9,___S_stdout,"stdout")
___END_SYM

#define ___SYM_cr_2d_lf ___SYM(0,___S_cr_2d_lf)
#define ___SYM_input ___SYM(1,___S_input)
#define ___SYM_normal ___SYM(2,___S_normal)
#define ___SYM_output ___SYM(3,___S_output)
#define ___SYM_repl ___SYM(4,___S_repl)
#define ___SYM_repl_2d_pump ___SYM(5,___S_repl_2d_pump)
#define ___SYM_repl_2d_server ___SYM(6,___S_repl_2d_server)
#define ___SYM_repl_2d_service ___SYM(7,___S_repl_2d_service)
#define ___SYM_stdin ___SYM(8,___S_stdin)
#define ___SYM_stdout ___SYM(9,___S_stdout)

___BEGIN_KEY
___DEF_KEY(0,___K_direction,"direction")
___DEF_KEY(1,___K_eol_2d_encoding,"eol-encoding")
___DEF_KEY(2,___K_permanent_2d_close,"permanent-close")
___DEF_KEY(3,___K_reuse_2d_address,"reuse-address")
___DEF_KEY(4,___K_server_2d_address,"server-address")
___DEF_KEY(5,___K_test,"test")
___END_KEY

#define ___KEY_direction ___KEY(0,___K_direction)
#define ___KEY_eol_2d_encoding ___KEY(1,___K_eol_2d_encoding)
#define ___KEY_permanent_2d_close ___KEY(2,___K_permanent_2d_close)
#define ___KEY_reuse_2d_address ___KEY(3,___K_reuse_2d_address)
#define ___KEY_server_2d_address ___KEY(4,___K_server_2d_address)
#define ___KEY_test ___KEY(5,___K_test)

___BEGIN_GLO
___DEF_GLO(0," repl-server")
___DEF_GLO(1,"##thread-make-repl-channel")
___DEF_GLO(2,"repl-server#ide-repl-pump")
___DEF_GLO(3,"repl-server#make-ide-repl-ports")
___DEF_GLO(4,"repl-server#repl-channel-table")
___DEF_GLO(5,"repl-server#repl-server")
___DEF_GLO(6,"repl-server#repl-server-address")
___DEF_GLO(7,"repl-server#repl-server-start")
___DEF_GLO(8,"repl-server#setup-ide-repl-channel")

___DEF_GLO(9,"##call-with-values")
___DEF_GLO(10,"##default-thread-make-repl-channel")

___DEF_GLO(11,"##make-repl-channel-ports")
___DEF_GLO(12,"##repl-debug-main")
___DEF_GLO(13,"##thread-interrupt!")
___DEF_GLO(14,"##vector-set!")
___DEF_GLO(15,"char=?")
___DEF_GLO(16,"close-output-port")
___DEF_GLO(17,"display")
___DEF_GLO(18,"eq?")
___DEF_GLO(19,"equal?")
___DEF_GLO(20,"for-each")
___DEF_GLO(21,"force-output")
___DEF_GLO(22,"make-mutex")
___DEF_GLO(23,"make-table")
___DEF_GLO(24,"make-thread")
___DEF_GLO(25,"make-thread-group")
___DEF_GLO(26,"mutex-lock!")
___DEF_GLO(27,"mutex-unlock!")
___DEF_GLO(28,"open-string-pipe")
___DEF_GLO(29,"open-tcp-server")
___DEF_GLO(30,"read")
___DEF_GLO(31,"read-char")
___DEF_GLO(32,"read-line")
___DEF_GLO(33,"table-ref")
___DEF_GLO(34,"table-set!")
___DEF_GLO(35,"thread-group->thread-list")
___DEF_GLO(36,"thread-start!")
___DEF_GLO(37,"thread-thread-group")
___DEF_GLO(38,"with-exception-catcher")
___DEF_GLO(39,"write-char")
___END_GLO

#define ___GLO__20_repl_2d_server ___GLO(0,___G__20_repl_2d_server)
#define ___PRM__20_repl_2d_server ___PRM(0,___G__20_repl_2d_server)
#define ___GLO__23__23_thread_2d_make_2d_repl_2d_channel ___GLO(1,___G__23__23_thread_2d_make_2d_repl_2d_channel)
#define ___PRM__23__23_thread_2d_make_2d_repl_2d_channel ___PRM(1,___G__23__23_thread_2d_make_2d_repl_2d_channel)
#define ___GLO_repl_2d_server_23_ide_2d_repl_2d_pump ___GLO(2,___G_repl_2d_server_23_ide_2d_repl_2d_pump)
#define ___PRM_repl_2d_server_23_ide_2d_repl_2d_pump ___PRM(2,___G_repl_2d_server_23_ide_2d_repl_2d_pump)
#define ___GLO_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports ___GLO(3,___G_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
#define ___PRM_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports ___PRM(3,___G_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
#define ___GLO_repl_2d_server_23_repl_2d_channel_2d_table ___GLO(4,___G_repl_2d_server_23_repl_2d_channel_2d_table)
#define ___PRM_repl_2d_server_23_repl_2d_channel_2d_table ___PRM(4,___G_repl_2d_server_23_repl_2d_channel_2d_table)
#define ___GLO_repl_2d_server_23_repl_2d_server ___GLO(5,___G_repl_2d_server_23_repl_2d_server)
#define ___PRM_repl_2d_server_23_repl_2d_server ___PRM(5,___G_repl_2d_server_23_repl_2d_server)
#define ___GLO_repl_2d_server_23_repl_2d_server_2d_address ___GLO(6,___G_repl_2d_server_23_repl_2d_server_2d_address)
#define ___PRM_repl_2d_server_23_repl_2d_server_2d_address ___PRM(6,___G_repl_2d_server_23_repl_2d_server_2d_address)
#define ___GLO_repl_2d_server_23_repl_2d_server_2d_start ___GLO(7,___G_repl_2d_server_23_repl_2d_server_2d_start)
#define ___PRM_repl_2d_server_23_repl_2d_server_2d_start ___PRM(7,___G_repl_2d_server_23_repl_2d_server_2d_start)
#define ___GLO_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel ___GLO(8,___G_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
#define ___PRM_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel ___PRM(8,___G_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
#define ___GLO__23__23_call_2d_with_2d_values ___GLO(9,___G__23__23_call_2d_with_2d_values)
#define ___PRM__23__23_call_2d_with_2d_values ___PRM(9,___G__23__23_call_2d_with_2d_values)
#define ___GLO__23__23_default_2d_thread_2d_make_2d_repl_2d_channel ___GLO(10,___G__23__23_default_2d_thread_2d_make_2d_repl_2d_channel)
#define ___PRM__23__23_default_2d_thread_2d_make_2d_repl_2d_channel ___PRM(10,___G__23__23_default_2d_thread_2d_make_2d_repl_2d_channel)
#define ___GLO__23__23_make_2d_repl_2d_channel_2d_ports ___GLO(11,___G__23__23_make_2d_repl_2d_channel_2d_ports)
#define ___PRM__23__23_make_2d_repl_2d_channel_2d_ports ___PRM(11,___G__23__23_make_2d_repl_2d_channel_2d_ports)
#define ___GLO__23__23_repl_2d_debug_2d_main ___GLO(12,___G__23__23_repl_2d_debug_2d_main)
#define ___PRM__23__23_repl_2d_debug_2d_main ___PRM(12,___G__23__23_repl_2d_debug_2d_main)
#define ___GLO__23__23_thread_2d_interrupt_21_ ___GLO(13,___G__23__23_thread_2d_interrupt_21_)
#define ___PRM__23__23_thread_2d_interrupt_21_ ___PRM(13,___G__23__23_thread_2d_interrupt_21_)
#define ___GLO__23__23_vector_2d_set_21_ ___GLO(14,___G__23__23_vector_2d_set_21_)
#define ___PRM__23__23_vector_2d_set_21_ ___PRM(14,___G__23__23_vector_2d_set_21_)
#define ___GLO_char_3d__3f_ ___GLO(15,___G_char_3d__3f_)
#define ___PRM_char_3d__3f_ ___PRM(15,___G_char_3d__3f_)
#define ___GLO_close_2d_output_2d_port ___GLO(16,___G_close_2d_output_2d_port)
#define ___PRM_close_2d_output_2d_port ___PRM(16,___G_close_2d_output_2d_port)
#define ___GLO_display ___GLO(17,___G_display)
#define ___PRM_display ___PRM(17,___G_display)
#define ___GLO_eq_3f_ ___GLO(18,___G_eq_3f_)
#define ___PRM_eq_3f_ ___PRM(18,___G_eq_3f_)
#define ___GLO_equal_3f_ ___GLO(19,___G_equal_3f_)
#define ___PRM_equal_3f_ ___PRM(19,___G_equal_3f_)
#define ___GLO_for_2d_each ___GLO(20,___G_for_2d_each)
#define ___PRM_for_2d_each ___PRM(20,___G_for_2d_each)
#define ___GLO_force_2d_output ___GLO(21,___G_force_2d_output)
#define ___PRM_force_2d_output ___PRM(21,___G_force_2d_output)
#define ___GLO_make_2d_mutex ___GLO(22,___G_make_2d_mutex)
#define ___PRM_make_2d_mutex ___PRM(22,___G_make_2d_mutex)
#define ___GLO_make_2d_table ___GLO(23,___G_make_2d_table)
#define ___PRM_make_2d_table ___PRM(23,___G_make_2d_table)
#define ___GLO_make_2d_thread ___GLO(24,___G_make_2d_thread)
#define ___PRM_make_2d_thread ___PRM(24,___G_make_2d_thread)
#define ___GLO_make_2d_thread_2d_group ___GLO(25,___G_make_2d_thread_2d_group)
#define ___PRM_make_2d_thread_2d_group ___PRM(25,___G_make_2d_thread_2d_group)
#define ___GLO_mutex_2d_lock_21_ ___GLO(26,___G_mutex_2d_lock_21_)
#define ___PRM_mutex_2d_lock_21_ ___PRM(26,___G_mutex_2d_lock_21_)
#define ___GLO_mutex_2d_unlock_21_ ___GLO(27,___G_mutex_2d_unlock_21_)
#define ___PRM_mutex_2d_unlock_21_ ___PRM(27,___G_mutex_2d_unlock_21_)
#define ___GLO_open_2d_string_2d_pipe ___GLO(28,___G_open_2d_string_2d_pipe)
#define ___PRM_open_2d_string_2d_pipe ___PRM(28,___G_open_2d_string_2d_pipe)
#define ___GLO_open_2d_tcp_2d_server ___GLO(29,___G_open_2d_tcp_2d_server)
#define ___PRM_open_2d_tcp_2d_server ___PRM(29,___G_open_2d_tcp_2d_server)
#define ___GLO_read ___GLO(30,___G_read)
#define ___PRM_read ___PRM(30,___G_read)
#define ___GLO_read_2d_char ___GLO(31,___G_read_2d_char)
#define ___PRM_read_2d_char ___PRM(31,___G_read_2d_char)
#define ___GLO_read_2d_line ___GLO(32,___G_read_2d_line)
#define ___PRM_read_2d_line ___PRM(32,___G_read_2d_line)
#define ___GLO_table_2d_ref ___GLO(33,___G_table_2d_ref)
#define ___PRM_table_2d_ref ___PRM(33,___G_table_2d_ref)
#define ___GLO_table_2d_set_21_ ___GLO(34,___G_table_2d_set_21_)
#define ___PRM_table_2d_set_21_ ___PRM(34,___G_table_2d_set_21_)
#define ___GLO_thread_2d_group_2d__3e_thread_2d_list ___GLO(35,___G_thread_2d_group_2d__3e_thread_2d_list)
#define ___PRM_thread_2d_group_2d__3e_thread_2d_list ___PRM(35,___G_thread_2d_group_2d__3e_thread_2d_list)
#define ___GLO_thread_2d_start_21_ ___GLO(36,___G_thread_2d_start_21_)
#define ___PRM_thread_2d_start_21_ ___PRM(36,___G_thread_2d_start_21_)
#define ___GLO_thread_2d_thread_2d_group ___GLO(37,___G_thread_2d_thread_2d_group)
#define ___PRM_thread_2d_thread_2d_group ___PRM(37,___G_thread_2d_thread_2d_group)
#define ___GLO_with_2d_exception_2d_catcher ___GLO(38,___G_with_2d_exception_2d_catcher)
#define ___PRM_with_2d_exception_2d_catcher ___PRM(38,___G_with_2d_exception_2d_catcher)
#define ___GLO_write_2d_char ___GLO(39,___G_write_2d_char)
#define ___PRM_write_2d_char ___PRM(39,___G_write_2d_char)

___BEGIN_CNS
 ___DEF_CNS(___REF_SYM(9,___S_stdout),___REF_NUL)
,___DEF_CNS(___REF_SYM(8,___S_stdin),___REF_NUL)
,___DEF_CNS(___REF_KEY(0,___K_direction),___REF_CNS(3))
,___DEF_CNS(___REF_SYM(3,___S_output),___REF_NUL)
,___DEF_CNS(___REF_KEY(0,___K_direction),___REF_CNS(5))
,___DEF_CNS(___REF_SYM(1,___S_input),___REF_CNS(6))
,___DEF_CNS(___REF_KEY(2,___K_permanent_2d_close),___REF_CNS(7))
,___DEF_CNS(___REF_FAL,___REF_NUL)
___END_CNS

___DEF_SUB_STR(___X0,6)
               ___STR6(42,58,55,48,48,48)
___DEF_SUB_STR(___X1,10)
               ___STR8(80,97,115,115,119,111,114,100)
               ___STR2(58,32)
___DEF_SUB_VEC(___X2,5)
               ___VEC1(___REF_SYM(6,___S_repl_2d_server))
               ___VEC1(___REF_PRC(1))
               ___VEC1(___REF_FIX(1))
               ___VEC1(___REF_NUL)
               ___VEC1(___REF_FAL)
               ___VEC0

___BEGIN_SUB
 ___DEF_SUB(___X0)
,___DEF_SUB(___X1)
,___DEF_SUB(___X2)
___END_SUB



#undef ___MD_ALL
#define ___MD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___MR_ALL
#define ___MR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___MW_ALL
#define ___MW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_M_COD
___BEGIN_M_HLBL
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0__20_repl_2d_server)
___DEF_M_HLBL(___L1__20_repl_2d_server)
___DEF_M_HLBL(___L2__20_repl_2d_server)
___DEF_M_HLBL(___L3__20_repl_2d_server)
___DEF_M_HLBL(___L4__20_repl_2d_server)
___DEF_M_HLBL(___L5__20_repl_2d_server)
___DEF_M_HLBL(___L6__20_repl_2d_server)
___DEF_M_HLBL(___L7__20_repl_2d_server)
___DEF_M_HLBL(___L8__20_repl_2d_server)
___DEF_M_HLBL(___L9__20_repl_2d_server)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L1_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L2_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L3_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L4_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L5_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L6_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L7_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L8_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L9_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L10_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L11_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L12_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L13_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L14_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L15_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L16_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L17_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L18_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L19_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L20_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L21_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L22_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L23_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L24_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L25_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L26_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L27_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L28_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L29_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L30_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L31_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L32_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L33_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L34_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L35_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L36_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L37_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L38_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L39_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L40_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L41_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L42_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L43_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L44_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L45_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L46_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L47_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L48_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L49_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L50_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L51_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L52_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L53_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L54_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L1_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L2_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L3_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L4_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L5_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L6_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L7_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L8_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L9_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L10_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L11_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L12_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L13_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L14_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L15_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L16_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L17_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L18_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L1_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L2_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L3_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L4_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L5_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L6_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L7_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L8_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L1_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L2_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L3_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L4_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L5_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L6_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L7_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L8_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L9_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L10_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L11_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L12_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L13_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L14_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L15_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L16_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L17_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L18_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L19_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L20_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L21_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L22_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL(___L23_repl_2d_server_23_repl_2d_server)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_M_HLBL(___L1_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_M_HLBL(___L2_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_M_HLBL(___L3_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_M_HLBL(___L4_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_M_HLBL(___L5_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_M_HLBL(___L6_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_M_HLBL(___L7_repl_2d_server_23_repl_2d_server_2d_start)
___END_M_HLBL

___BEGIN_M_SW

#undef ___PH_PROC
#define ___PH_PROC ___H__20_repl_2d_server
#undef ___PH_LBL0
#define ___PH_LBL0 1
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0__20_repl_2d_server)
___DEF_P_HLBL(___L1__20_repl_2d_server)
___DEF_P_HLBL(___L2__20_repl_2d_server)
___DEF_P_HLBL(___L3__20_repl_2d_server)
___DEF_P_HLBL(___L4__20_repl_2d_server)
___DEF_P_HLBL(___L5__20_repl_2d_server)
___DEF_P_HLBL(___L6__20_repl_2d_server)
___DEF_P_HLBL(___L7__20_repl_2d_server)
___DEF_P_HLBL(___L8__20_repl_2d_server)
___DEF_P_HLBL(___L9__20_repl_2d_server)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0__20_repl_2d_server)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(0,0,0,0)
___DEF_GLBL(___L__20_repl_2d_server)
   ___SET_STK(1,___R0)
   ___SET_R2(___PRM_eq_3f_)
   ___SET_R1(___KEY_test)
   ___SET_R0(___LBL(2))
   ___ADJFP(4)
   ___POLL(1)
___DEF_SLBL(1,___L1__20_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(2),23,___G_make_2d_table)
___DEF_SLBL(2,___L2__20_repl_2d_server)
   ___SET_GLO(4,___G_repl_2d_server_23_repl_2d_channel_2d_table,___R1)
   ___SET_GLO(1,___G__23__23_thread_2d_make_2d_repl_2d_channel,___LBL(4))
   ___SET_GLO(6,___G_repl_2d_server_23_repl_2d_server_2d_address,___FAL)
   ___SET_GLO(6,___G_repl_2d_server_23_repl_2d_server_2d_address,___SUB(0))
   ___SET_R1(___VOID)
   ___POLL(3)
___DEF_SLBL(3,___L3__20_repl_2d_server)
   ___ADJFP(-4)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_SLBL(4,___L4__20_repl_2d_server)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(4,1,0,0)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R0(___LBL(6))
   ___ADJFP(8)
   ___POLL(5)
___DEF_SLBL(5,___L5__20_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(1),37,___G_thread_2d_thread_2d_group)
___DEF_SLBL(6,___L6__20_repl_2d_server)
   ___SET_R2(___R1)
   ___SET_R3(___FAL)
   ___SET_R1(___GLO_repl_2d_server_23_repl_2d_channel_2d_table)
   ___SET_R0(___LBL(7))
   ___JUMPGLOSAFE(___SET_NARGS(3),33,___G_table_2d_ref)
___DEF_SLBL(7,___L7__20_repl_2d_server)
   ___IF(___NOT(___FALSEP(___R1)))
   ___GOTO(___L10__20_repl_2d_server)
   ___END_IF
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___POLL(8)
___DEF_SLBL(8,___L8__20_repl_2d_server)
   ___ADJFP(-8)
   ___JUMPGLOSAFE(___SET_NARGS(1),10,___G__23__23_default_2d_thread_2d_make_2d_repl_2d_channel)
___DEF_GLBL(___L10__20_repl_2d_server)
   ___POLL(9)
___DEF_SLBL(9,___L9__20_repl_2d_server)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(1))
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_repl_2d_server_23_ide_2d_repl_2d_pump
#undef ___PH_LBL0
#define ___PH_LBL0 12
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L1_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L2_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L3_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L4_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L5_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L6_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L7_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L8_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L9_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L10_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L11_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L12_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L13_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L14_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L15_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L16_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L17_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L18_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L19_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L20_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L21_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L22_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L23_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L24_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L25_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L26_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L27_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L28_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L29_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L30_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L31_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L32_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L33_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L34_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L35_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L36_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L37_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L38_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L39_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L40_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L41_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L42_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L43_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L44_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L45_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L46_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L47_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L48_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L49_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L50_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L51_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L52_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L53_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L54_repl_2d_server_23_ide_2d_repl_2d_pump)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(4,___NOTHING)
   ___WRONG_NARGS(0,4,0,0)
___DEF_GLBL(___L_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R0(___LBL(2))
   ___ADJFP(7)
   ___POLL(1)
___DEF_SLBL(1,___L1_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(0),22,___G_make_2d_mutex)
___DEF_SLBL(2,___L2_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(-2,___ALLOC_CLO(4))
   ___SET_STK(-1,___ALLOC_CLO(3))
   ___BEGIN_SETUP_CLO(4,___STK(-2),53)
   ___ADD_CLO_ELEM(0,___STK(-7))
   ___ADD_CLO_ELEM(1,___R1)
   ___ADD_CLO_ELEM(2,___STK(-4))
   ___ADD_CLO_ELEM(3,___STK(-3))
   ___END_SETUP_CLO(4)
   ___BEGIN_SETUP_CLO(3,___STK(-1),14)
   ___ADD_CLO_ELEM(0,___STK(-7))
   ___ADD_CLO_ELEM(1,___STK(-5))
   ___ADD_CLO_ELEM(2,___R1)
   ___END_SETUP_CLO(3)
   ___SET_R2(___FAL)
   ___SET_R1(___SYM_repl_2d_pump)
   ___SET_R0(___LBL(4))
   ___ADJFP(4)
   ___CHECK_HEAP(3,4096)
___DEF_SLBL(3,___L3_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(2),25,___G_make_2d_thread_2d_group)
___DEF_SLBL(4,___L4_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(-11,___R1)
   ___SET_R2(___STK(-6))
   ___SET_R0(___LBL(5))
   ___GOTO(___L55_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_SLBL(5,___L5_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-11))
   ___SET_R0(___STK(-10))
   ___ADJFP(-12)
   ___POLL(6)
___DEF_SLBL(6,___L6_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L55_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___ALLOC_CLO(1))
   ___BEGIN_SETUP_CLO(1,___STK(2),11)
   ___ADD_CLO_ELEM(0,___R2)
   ___END_SETUP_CLO(1)
   ___SET_STK(3,___R1)
   ___SET_R1(___STK(2))
   ___SET_R3(___STK(3))
   ___SET_R2(___FAL)
   ___SET_R0(___LBL(9))
   ___ADJFP(4)
   ___CHECK_HEAP(7,4096)
___DEF_SLBL(7,___L7_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___POLL(8)
___DEF_SLBL(8,___L8_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(3),24,___G_make_2d_thread)
___DEF_SLBL(9,___L9_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R0(___STK(-3))
   ___POLL(10)
___DEF_SLBL(10,___L10_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(1),36,___G_thread_2d_start_21_)
___DEF_SLBL(11,___L11_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(11,0,0,0)
   ___SET_R1(___LBL(13))
   ___SET_R2(___CLO(___R4,1))
   ___POLL(12)
___DEF_SLBL(12,___L12_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(2),38,___G_with_2d_exception_2d_catcher)
___DEF_SLBL(13,___L13_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(13,1,0,0)
   ___SET_R1(___FAL)
   ___JUMPPRM(___NOTHING,___R0)
___DEF_SLBL(14,___L14_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(14,0,0,0)
   ___SET_R3(___CLO(___R4,3))
   ___SET_R2(___CLO(___R4,2))
   ___SET_R1(___CLO(___R4,1))
   ___POLL(15)
___DEF_SLBL(15,___L15_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___GOTO(___L56_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_SLBL(16,___L16_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R3(___STK(-4))
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(17)
___DEF_SLBL(17,___L17_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L56_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(19))
   ___ADJFP(8)
   ___POLL(18)
___DEF_SLBL(18,___L18_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___JUMPPRM(___SET_NARGS(1),___PRM_read_2d_char)
___DEF_SLBL(19,___L19_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___EOFP(___R1))
   ___GOTO(___L57_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___GOTO(___L83_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_SLBL(20,___L20_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___CDR(___STK(-5)))
   ___IF(___PAIRP(___R1))
   ___GOTO(___L58_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L57_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___VOID)
   ___POLL(21)
___DEF_SLBL(21,___L21_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L58_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(-5,___R1)
   ___SET_R1(___CAR(___R1))
   ___SET_R0(___LBL(22))
   ___JUMPGENSAFE(___SET_NARGS(1),___STK(-6))
___DEF_SLBL(22,___L22_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___CDR(___STK(-5)))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(23)
___DEF_SLBL(23,___L23_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___GOTO(___L61_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_SLBL(24,___L24_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___NOT(___PROCEDUREP(___STK(-6))))
   ___GOTO(___L63_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_R2(___STK(-6))
   ___SET_R3(___R1)
   ___SET_R0(___LBL(28))
   ___ADJFP(-4)
   ___IF(___NOT(___PAIRP(___R3)))
   ___GOTO(___L60_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L59_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R3(___CDR(___R3))
   ___POLL(25)
___DEF_SLBL(25,___L25_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___PAIRP(___R3))
   ___GOTO(___L59_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L60_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___NOT(___NULLP(___R3)))
   ___GOTO(___L82_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_STK(1,___R2)
   ___SET_R2(___R1)
   ___SET_R1(___STK(1))
   ___POLL(26)
___DEF_SLBL(26,___L26_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L61_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___NOT(___PAIRP(___R2)))
   ___GOTO(___L62_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R1(___CAR(___R2))
   ___SET_R0(___LBL(20))
   ___ADJFP(8)
   ___POLL(27)
___DEF_SLBL(27,___L27_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___JUMPGENSAFE(___SET_NARGS(1),___STK(-6))
___DEF_GLBL(___L62_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___VOID)
   ___JUMPPRM(___NOTHING,___R0)
___DEF_GLBL(___L63_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(28))
   ___ADJFP(-4)
   ___JUMPPRM(___SET_NARGS(2),___PRM_for_2d_each)
___DEF_SLBL(28,___L28_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___GOTO(___L64_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_SLBL(29,___L29_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___NOT(___FALSEP(___R1)))
   ___GOTO(___L79_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L64_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-3))
   ___SET_R1(___STK(-4))
   ___SET_R3(___SYM_normal)
   ___SET_R0(___STK(-5))
   ___ADJFP(-6)
   ___POLL(30)
___DEF_SLBL(30,___L30_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L65_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R1(___STK(-1))
   ___SET_R0(___LBL(32))
   ___ADJFP(10)
   ___POLL(31)
___DEF_SLBL(31,___L31_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___JUMPPRM(___SET_NARGS(1),___PRM_read_2d_char)
___DEF_SLBL(32,___L32_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___NOT(___EOFP(___R1)))
   ___GOTO(___L66_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_R1(___VOID)
   ___POLL(33)
___DEF_SLBL(33,___L33_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___ADJFP(-12)
   ___JUMPPRM(___NOTHING,___STK(3))
___DEF_GLBL(___L66_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___BEGIN_SWITCH_CHAR(___STK(-6))
   ___SWITCH_CHAR_CASE_GOTO(___CHR(251),___L67_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(252),___L67_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(253),___L78_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(254),___L67_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(255),___L68_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_SWITCH_CHAR
   ___IF_GOTO(___EQP(___STK(-6),___SYM_normal),___L71_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L67_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-7))
   ___SET_R1(___STK(-8))
   ___SET_R3(___SYM_normal)
   ___SET_R0(___STK(-9))
   ___ADJFP(-10)
   ___POLL(34)
___DEF_SLBL(34,___L34_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___GOTO(___L65_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L68_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___BEGIN_SWITCH_CHAR(___R1)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(244),___L77_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(251),___L69_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(252),___L69_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(253),___L69_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(254),___L69_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_SWITCH_CHAR
   ___SET_R2(___STK(-7))
   ___SET_R1(___STK(-8))
   ___SET_R3(___SYM_normal)
   ___SET_R0(___STK(-9))
   ___ADJFP(-10)
   ___POLL(35)
___DEF_SLBL(35,___L35_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___GOTO(___L65_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_SLBL(36,___L36_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L70_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_R1(___STK(-5))
___DEF_GLBL(___L69_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R3(___R1)
   ___SET_R2(___STK(-7))
   ___SET_R1(___STK(-8))
   ___SET_R0(___STK(-9))
   ___ADJFP(-10)
   ___POLL(37)
___DEF_SLBL(37,___L37_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___GOTO(___L65_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L70_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-5))
   ___GOTO(___L72_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L71_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___NOT(___CHARP(___R1)))
   ___GOTO(___L76_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___CHAREQP(___R1,___CHR(255)))
   ___GOTO(___L69_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L72_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(-5,___R1)
   ___SET_R1(___STK(-7))
   ___SET_R0(___LBL(38))
   ___JUMPGLOSAFE(___SET_NARGS(1),26,___G_mutex_2d_lock_21_)
___DEF_SLBL(38,___L38_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___NOT(___CHARP(___STK(-5))))
   ___GOTO(___L75_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___CHAREQP(___STK(-5),___CHR(4)))
   ___GOTO(___L73_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___GOTO(___L74_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_SLBL(39,___L39_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L74_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L73_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-10))
   ___SET_R0(___LBL(40))
   ___JUMPPRM(___SET_NARGS(1),___PRM_close_2d_output_2d_port)
___DEF_SLBL(40,___L40_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-7))
   ___SET_R0(___LBL(41))
   ___JUMPGLOSAFE(___SET_NARGS(1),27,___G_mutex_2d_unlock_21_)
___DEF_SLBL(41,___L41_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R3(___STK(-6))
   ___SET_R2(___STK(-7))
   ___SET_R1(___STK(-8))
   ___SET_R0(___STK(-9))
   ___ADJFP(-10)
   ___POLL(42)
___DEF_SLBL(42,___L42_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___GOTO(___L65_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L74_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-10))
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(43))
   ___JUMPPRM(___SET_NARGS(2),___PRM_write_2d_char)
___DEF_SLBL(43,___L43_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-10))
   ___SET_R0(___LBL(40))
   ___JUMPGLOSAFE(___SET_NARGS(1),21,___G_force_2d_output)
___DEF_GLBL(___L75_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-5))
   ___SET_R2(___CHR(4))
   ___SET_R0(___LBL(39))
   ___JUMPPRM(___SET_NARGS(2),___PRM_char_3d__3f_)
___DEF_GLBL(___L76_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(-5,___R1)
   ___SET_R2(___CHR(255))
   ___SET_R0(___LBL(36))
   ___JUMPPRM(___SET_NARGS(2),___PRM_char_3d__3f_)
___DEF_GLBL(___L77_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(-6,___GLO__23__23_thread_2d_interrupt_21_)
   ___SET_R1(___STK(-8))
   ___SET_R0(___LBL(24))
   ___JUMPGLOSAFE(___SET_NARGS(1),35,___G_thread_2d_group_2d__3e_thread_2d_list)
___DEF_GLBL(___L78_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF(___NOT(___CHARP(___R1)))
   ___GOTO(___L81_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___NOT(___CHAREQP(___R1,___CHR(6))))
   ___GOTO(___L80_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___END_IF
   ___ADJFP(-4)
___DEF_GLBL(___L79_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-3))
   ___SET_R0(___LBL(44))
   ___JUMPGLOSAFE(___SET_NARGS(1),26,___G_mutex_2d_lock_21_)
___DEF_SLBL(44,___L44_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-7))
   ___SET_R1(___CHR(255))
   ___SET_R0(___LBL(45))
   ___JUMPPRM(___SET_NARGS(2),___PRM_write_2d_char)
___DEF_SLBL(45,___L45_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-7))
   ___SET_R1(___CHR(251))
   ___SET_R0(___LBL(46))
   ___JUMPPRM(___SET_NARGS(2),___PRM_write_2d_char)
___DEF_SLBL(46,___L46_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-7))
   ___SET_R1(___CHR(6))
   ___SET_R0(___LBL(47))
   ___JUMPPRM(___SET_NARGS(2),___PRM_write_2d_char)
___DEF_SLBL(47,___L47_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-7))
   ___SET_R0(___LBL(48))
   ___JUMPGLOSAFE(___SET_NARGS(1),21,___G_force_2d_output)
___DEF_SLBL(48,___L48_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-3))
   ___SET_R0(___LBL(28))
   ___JUMPGLOSAFE(___SET_NARGS(1),27,___G_mutex_2d_unlock_21_)
___DEF_GLBL(___L80_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___ADJFP(-4)
   ___GOTO(___L64_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_GLBL(___L81_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___CHR(6))
   ___SET_R0(___LBL(29))
   ___ADJFP(-4)
   ___JUMPPRM(___SET_NARGS(2),___PRM_char_3d__3f_)
___DEF_GLBL(___L82_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R2)
   ___SET_R2(___R1)
   ___SET_R1(___STK(1))
   ___ADJFP(1)
   ___POLL(49)
___DEF_SLBL(49,___L49_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___ADJFP(-1)
   ___JUMPPRM(___SET_NARGS(2),___PRM_for_2d_each)
___DEF_GLBL(___L83_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_STK(-3,___R1)
   ___SET_R1(___STK(-4))
   ___SET_R0(___LBL(50))
   ___JUMPGLOSAFE(___SET_NARGS(1),26,___G_mutex_2d_lock_21_)
___DEF_SLBL(50,___L50_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-6))
   ___SET_R1(___STK(-3))
   ___SET_R0(___LBL(51))
   ___JUMPPRM(___SET_NARGS(2),___PRM_write_2d_char)
___DEF_SLBL(51,___L51_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(52))
   ___JUMPGLOSAFE(___SET_NARGS(1),21,___G_force_2d_output)
___DEF_SLBL(52,___L52_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-4))
   ___SET_R0(___LBL(16))
   ___JUMPGLOSAFE(___SET_NARGS(1),27,___G_mutex_2d_unlock_21_)
___DEF_SLBL(53,___L53_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(53,0,0,0)
   ___SET_STK(1,___CLO(___R4,1))
   ___SET_STK(2,___CLO(___R4,3))
   ___SET_R2(___CLO(___R4,2))
   ___SET_R1(___CLO(___R4,4))
   ___SET_R3(___SYM_normal)
   ___ADJFP(2)
   ___POLL(54)
___DEF_SLBL(54,___L54_repl_2d_server_23_ide_2d_repl_2d_pump)
   ___GOTO(___L65_repl_2d_server_23_ide_2d_repl_2d_pump)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports
#undef ___PH_LBL0
#define ___PH_LBL0 68
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L1_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L2_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L3_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L4_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L5_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L6_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L7_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L8_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L9_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L10_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L11_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L12_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L13_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L14_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L15_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L16_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L17_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L18_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(0,2,0,0)
___DEF_GLBL(___L_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___SET_STK(1,___LBL(17))
   ___SET_STK(2,___ALLOC_CLO(2))
   ___BEGIN_SETUP_CLO(2,___STK(2),3)
   ___ADD_CLO_ELEM(0,___R1)
   ___ADD_CLO_ELEM(1,___R2)
   ___END_SETUP_CLO(2)
   ___SET_R2(___STK(2))
   ___SET_R1(___STK(1))
   ___ADJFP(2)
   ___CHECK_HEAP(1,4096)
___DEF_SLBL(1,___L1_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___POLL(2)
___DEF_SLBL(2,___L2_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___GOTO(___L19_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_SLBL(3,___L3_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(3,2,0,0)
   ___SET_STK(1,___LBL(15))
   ___SET_STK(2,___ALLOC_CLO(4))
   ___BEGIN_SETUP_CLO(4,___STK(2),6)
   ___ADD_CLO_ELEM(0,___CLO(___R4,1))
   ___ADD_CLO_ELEM(1,___R1)
   ___ADD_CLO_ELEM(2,___R2)
   ___ADD_CLO_ELEM(3,___CLO(___R4,2))
   ___END_SETUP_CLO(4)
   ___SET_R2(___STK(2))
   ___SET_R1(___STK(1))
   ___ADJFP(2)
   ___CHECK_HEAP(4,4096)
___DEF_SLBL(4,___L4_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___POLL(5)
___DEF_SLBL(5,___L5_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_GLBL(___L19_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___ADJFP(-2)
   ___JUMPGLOSAFE(___SET_NARGS(2),9,___G__23__23_call_2d_with_2d_values)
___DEF_SLBL(6,___L6_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(6,2,0,0)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R4)
   ___SET_R3(___LBL(14))
   ___SET_R1(___CLO(___R4,2))
   ___SET_R2(___FIX(4L))
   ___SET_R0(___LBL(8))
   ___ADJFP(8)
   ___POLL(7)
___DEF_SLBL(7,___L7_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___JUMPPRM(___SET_NARGS(3),___PRM__23__23_vector_2d_set_21_)
___DEF_SLBL(8,___L8_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___SET_R3(___LBL(13))
   ___SET_R1(___STK(-6))
   ___SET_R2(___FIX(4L))
   ___SET_R0(___LBL(9))
   ___JUMPPRM(___SET_NARGS(3),___PRM__23__23_vector_2d_set_21_)
___DEF_SLBL(9,___L9_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___SET_STK(1,___CLO(___STK(-4),1))
   ___SET_R3(___CLO(___STK(-4),4))
   ___SET_R2(___CLO(___STK(-4),3))
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(10))
   ___ADJFP(1)
   ___JUMPINT(___SET_NARGS(4),___PRC(12),___L_repl_2d_server_23_ide_2d_repl_2d_pump)
___DEF_SLBL(10,___L10_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___SET_R0(___CLO(___STK(-4),2))
   ___BEGIN_ALLOC_VALUES(2)
   ___ADD_VALUES_ELEM(0,___R0)
   ___ADD_VALUES_ELEM(1,___STK(-6))
   ___END_ALLOC_VALUES(2)
   ___SET_R1(___GET_VALUES(2))
   ___CHECK_HEAP(11,4096)
___DEF_SLBL(11,___L11_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___POLL(12)
___DEF_SLBL(12,___L12_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_SLBL(13,___L13_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(13,1,0,0)
   ___SET_R1(___CNS(0))
   ___JUMPPRM(___NOTHING,___R0)
___DEF_SLBL(14,___L14_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(14,1,0,0)
   ___SET_R1(___CNS(1))
   ___JUMPPRM(___NOTHING,___R0)
___DEF_SLBL(15,___L15_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(15,0,0,0)
   ___SET_R1(___CNS(2))
   ___POLL(16)
___DEF_SLBL(16,___L16_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___GOTO(___L20_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_SLBL(17,___L17_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(17,0,0,0)
   ___SET_R1(___CNS(4))
   ___POLL(18)
___DEF_SLBL(18,___L18_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___DEF_GLBL(___L20_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
   ___JUMPGLOSAFE(___SET_NARGS(1),28,___G_open_2d_string_2d_pipe)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel
#undef ___PH_LBL0
#define ___PH_LBL0 88
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L1_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L2_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L3_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L4_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L5_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L6_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L7_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L8_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(0,2,0,0)
___DEF_GLBL(___L_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___SET_STK(1,___ALLOC_CLO(2))
   ___BEGIN_SETUP_CLO(2,___STK(1),7)
   ___ADD_CLO_ELEM(0,___R1)
   ___ADD_CLO_ELEM(1,___R2)
   ___END_SETUP_CLO(2)
   ___SET_STK(2,___ALLOC_CLO(1))
   ___BEGIN_SETUP_CLO(1,___STK(2),3)
   ___ADD_CLO_ELEM(0,___R2)
   ___END_SETUP_CLO(1)
   ___SET_R2(___STK(2))
   ___SET_R1(___STK(1))
   ___ADJFP(2)
   ___CHECK_HEAP(1,4096)
___DEF_SLBL(1,___L1_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___POLL(2)
___DEF_SLBL(2,___L2_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___ADJFP(-2)
   ___JUMPGLOSAFE(___SET_NARGS(2),9,___G__23__23_call_2d_with_2d_values)
___DEF_SLBL(3,___L3_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(3,2,0,0)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R4)
   ___SET_R0(___LBL(5))
   ___ADJFP(8)
   ___POLL(4)
___DEF_SLBL(4,___L4_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___JUMPGLOSAFE(___SET_NARGS(2),11,___G__23__23_make_2d_repl_2d_channel_2d_ports)
___DEF_SLBL(5,___L5_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___SET_R3(___R1)
   ___SET_R2(___CLO(___STK(-6),1))
   ___SET_R1(___GLO_repl_2d_server_23_repl_2d_channel_2d_table)
   ___SET_R0(___STK(-7))
   ___POLL(6)
___DEF_SLBL(6,___L6_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___ADJFP(-8)
   ___JUMPGLOSAFE(___SET_NARGS(3),34,___G_table_2d_set_21_)
___DEF_SLBL(7,___L7_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(7,0,0,0)
   ___SET_R2(___CLO(___R4,2))
   ___SET_R1(___CLO(___R4,1))
   ___POLL(8)
___DEF_SLBL(8,___L8_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
   ___JUMPINT(___SET_NARGS(2),___PRC(68),___L_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_repl_2d_server_23_repl_2d_server
#undef ___PH_LBL0
#define ___PH_LBL0 98
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L1_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L2_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L3_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L4_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L5_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L6_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L7_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L8_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L9_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L10_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L11_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L12_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L13_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L14_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L15_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L16_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L17_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L18_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L19_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L20_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L21_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L22_repl_2d_server_23_repl_2d_server)
___DEF_P_HLBL(___L23_repl_2d_server_23_repl_2d_server)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_repl_2d_server_23_repl_2d_server)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_repl_2d_server_23_repl_2d_server)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___BEGIN_ALLOC_LIST(6,___TRU)
   ___ADD_LIST_ELEM(1,___KEY_reuse_2d_address)
   ___ADD_LIST_ELEM(2,___SYM_cr_2d_lf)
   ___ADD_LIST_ELEM(3,___KEY_eol_2d_encoding)
   ___ADD_LIST_ELEM(4,___GLO_repl_2d_server_23_repl_2d_server_2d_address)
   ___ADD_LIST_ELEM(5,___KEY_server_2d_address)
   ___END_ALLOC_LIST(6)
   ___SET_R1(___GET_LIST(6))
   ___SET_R0(___LBL(3))
   ___ADJFP(8)
   ___CHECK_HEAP(1,4096)
___DEF_SLBL(1,___L1_repl_2d_server_23_repl_2d_server)
   ___POLL(2)
___DEF_SLBL(2,___L2_repl_2d_server_23_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(1),29,___G_open_2d_tcp_2d_server)
___DEF_SLBL(3,___L3_repl_2d_server_23_repl_2d_server)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(4)
___DEF_SLBL(4,___L4_repl_2d_server_23_repl_2d_server)
   ___GOTO(___L24_repl_2d_server_23_repl_2d_server)
___DEF_SLBL(5,___L5_repl_2d_server_23_repl_2d_server)
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(6)
___DEF_SLBL(6,___L6_repl_2d_server_23_repl_2d_server)
___DEF_GLBL(___L24_repl_2d_server_23_repl_2d_server)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(8))
   ___ADJFP(8)
   ___POLL(7)
___DEF_SLBL(7,___L7_repl_2d_server_23_repl_2d_server)
   ___JUMPPRM(___SET_NARGS(1),___PRM_read)
___DEF_SLBL(8,___L8_repl_2d_server_23_repl_2d_server)
   ___SET_STK(-4,___R1)
   ___SET_R2(___FAL)
   ___SET_R1(___SYM_repl_2d_service)
   ___SET_R0(___LBL(9))
   ___JUMPGLOSAFE(___SET_NARGS(2),25,___G_make_2d_thread_2d_group)
___DEF_SLBL(9,___L9_repl_2d_server_23_repl_2d_server)
   ___SET_STK(-3,___ALLOC_CLO(3))
   ___BEGIN_SETUP_CLO(3,___STK(-3),12)
   ___ADD_CLO_ELEM(0,___STK(-4))
   ___ADD_CLO_ELEM(1,___STK(-6))
   ___ADD_CLO_ELEM(2,___R1)
   ___END_SETUP_CLO(3)
   ___SET_STK(-4,___R1)
   ___SET_R1(___STK(-3))
   ___SET_R3(___STK(-4))
   ___SET_R2(___SYM_repl)
   ___SET_R0(___LBL(11))
   ___CHECK_HEAP(10,4096)
___DEF_SLBL(10,___L10_repl_2d_server_23_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(3),24,___G_make_2d_thread)
___DEF_SLBL(11,___L11_repl_2d_server_23_repl_2d_server)
   ___SET_R0(___LBL(5))
   ___JUMPGLOSAFE(___SET_NARGS(1),36,___G_thread_2d_start_21_)
___DEF_SLBL(12,___L12_repl_2d_server_23_repl_2d_server)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(12,0,0,0)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R4)
   ___SET_R2(___CLO(___R4,3))
   ___SET_R1(___CLO(___R4,1))
   ___SET_R0(___LBL(14))
   ___ADJFP(8)
   ___POLL(13)
___DEF_SLBL(13,___L13_repl_2d_server_23_repl_2d_server)
   ___JUMPINT(___SET_NARGS(2),___PRC(88),___L_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel)
___DEF_SLBL(14,___L14_repl_2d_server_23_repl_2d_server)
   ___IF(___NOT(___FALSEP(___CLO(___STK(-6),2))))
   ___GOTO(___L26_repl_2d_server_23_repl_2d_server)
   ___END_IF
   ___ADJFP(-4)
   ___GOTO(___L25_repl_2d_server_23_repl_2d_server)
___DEF_SLBL(15,___L15_repl_2d_server_23_repl_2d_server)
___DEF_GLBL(___L25_repl_2d_server_23_repl_2d_server)
   ___SET_R0(___STK(-3))
   ___POLL(16)
___DEF_SLBL(16,___L16_repl_2d_server_23_repl_2d_server)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(0),12,___G__23__23_repl_2d_debug_2d_main)
___DEF_GLBL(___L26_repl_2d_server_23_repl_2d_server)
   ___SET_R2(___CLO(___STK(-6),1))
   ___SET_R1(___CLO(___STK(-6),2))
   ___SET_R0(___LBL(15))
   ___ADJFP(-4)
   ___GOTO(___L28_repl_2d_server_23_repl_2d_server)
___DEF_SLBL(17,___L17_repl_2d_server_23_repl_2d_server)
   ___IF(___NOT(___FALSEP(___R1)))
   ___GOTO(___L29_repl_2d_server_23_repl_2d_server)
   ___END_IF
___DEF_GLBL(___L27_repl_2d_server_23_repl_2d_server)
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(18)
___DEF_SLBL(18,___L18_repl_2d_server_23_repl_2d_server)
___DEF_GLBL(___L28_repl_2d_server_23_repl_2d_server)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R1(___SUB(1))
   ___SET_R0(___LBL(20))
   ___ADJFP(8)
   ___POLL(19)
___DEF_SLBL(19,___L19_repl_2d_server_23_repl_2d_server)
   ___JUMPPRM(___SET_NARGS(2),___PRM_display)
___DEF_SLBL(20,___L20_repl_2d_server_23_repl_2d_server)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(21))
   ___JUMPGLOSAFE(___SET_NARGS(1),21,___G_force_2d_output)
___DEF_SLBL(21,___L21_repl_2d_server_23_repl_2d_server)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(22))
   ___JUMPGLOSAFE(___SET_NARGS(1),32,___G_read_2d_line)
___DEF_SLBL(22,___L22_repl_2d_server_23_repl_2d_server)
   ___IF(___NOT(___EQP(___R1,___STK(-6))))
   ___GOTO(___L30_repl_2d_server_23_repl_2d_server)
   ___END_IF
___DEF_GLBL(___L29_repl_2d_server_23_repl_2d_server)
   ___SET_R1(___VOID)
   ___POLL(23)
___DEF_SLBL(23,___L23_repl_2d_server_23_repl_2d_server)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L30_repl_2d_server_23_repl_2d_server)
   ___IF(___NOT(___MEMALLOCATEDP(___R1)))
   ___GOTO(___L27_repl_2d_server_23_repl_2d_server)
   ___END_IF
   ___IF(___NOT(___MEMALLOCATEDP(___STK(-6))))
   ___GOTO(___L27_repl_2d_server_23_repl_2d_server)
   ___END_IF
   ___SET_R2(___SUBTYPE(___STK(-6)))
   ___SET_R3(___SUBTYPE(___R1))
   ___IF(___NOT(___FIXEQ(___R3,___R2)))
   ___GOTO(___L27_repl_2d_server_23_repl_2d_server)
   ___END_IF
   ___SET_R2(___STK(-6))
   ___SET_R0(___LBL(17))
   ___JUMPPRM(___SET_NARGS(2),___PRM_equal_3f_)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_repl_2d_server_23_repl_2d_server_2d_start
#undef ___PH_LBL0
#define ___PH_LBL0 123
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_P_HLBL(___L1_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_P_HLBL(___L2_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_P_HLBL(___L3_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_P_HLBL(___L4_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_P_HLBL(___L5_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_P_HLBL(___L6_repl_2d_server_23_repl_2d_server_2d_start)
___DEF_P_HLBL(___L7_repl_2d_server_23_repl_2d_server_2d_start)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_repl_2d_server_23_repl_2d_server_2d_start)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_repl_2d_server_23_repl_2d_server_2d_start)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___ALLOC_CLO(1))
   ___BEGIN_SETUP_CLO(1,___STK(2),6)
   ___ADD_CLO_ELEM(0,___R1)
   ___END_SETUP_CLO(1)
   ___SET_R1(___STK(2))
   ___SET_R0(___LBL(3))
   ___ADJFP(4)
   ___CHECK_HEAP(1,4096)
___DEF_SLBL(1,___L1_repl_2d_server_23_repl_2d_server_2d_start)
   ___POLL(2)
___DEF_SLBL(2,___L2_repl_2d_server_23_repl_2d_server_2d_start)
   ___JUMPGLOSAFE(___SET_NARGS(1),24,___G_make_2d_thread)
___DEF_SLBL(3,___L3_repl_2d_server_23_repl_2d_server_2d_start)
   ___SET_R0(___LBL(4))
   ___JUMPGLOSAFE(___SET_NARGS(1),36,___G_thread_2d_start_21_)
___DEF_SLBL(4,___L4_repl_2d_server_23_repl_2d_server_2d_start)
   ___SET_R1(___VOID)
   ___POLL(5)
___DEF_SLBL(5,___L5_repl_2d_server_23_repl_2d_server_2d_start)
   ___ADJFP(-4)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_SLBL(6,___L6_repl_2d_server_23_repl_2d_server_2d_start)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(6,0,0,0)
   ___SET_R1(___CLO(___R4,1))
   ___POLL(7)
___DEF_SLBL(7,___L7_repl_2d_server_23_repl_2d_server_2d_start)
   ___JUMPINT(___SET_NARGS(1),___PRC(98),___L_repl_2d_server_23_repl_2d_server)
___END_P_SW
___END_P_COD

___END_M_SW
___END_M_COD

___BEGIN_LBL
 ___DEF_LBL_INTRO(___H__20_repl_2d_server," repl-server",___REF_FAL,10,0)
,___DEF_LBL_PROC(___H__20_repl_2d_server,0,-1)
,___DEF_LBL_RET(___H__20_repl_2d_server,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H__20_repl_2d_server,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H__20_repl_2d_server,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_PROC(___H__20_repl_2d_server,1,-1)
,___DEF_LBL_RET(___H__20_repl_2d_server,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H__20_repl_2d_server,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H__20_repl_2d_server,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H__20_repl_2d_server,___IFD(___RETI,8,8,0x3f00L))
,___DEF_LBL_RET(___H__20_repl_2d_server,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_INTRO(___H_repl_2d_server_23_ide_2d_repl_2d_pump,"repl-server#ide-repl-pump",___REF_FAL,55,
0)
,___DEF_LBL_PROC(___H_repl_2d_server_23_ide_2d_repl_2d_pump,4,-1)
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,8,1,0x3f1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,1,0x1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___OFD(___RETI,12,1,0x3f062L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,1,0x62L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,1,0x43L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_PROC(___H_repl_2d_server_23_ide_2d_repl_2d_pump,0,1)
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_PROC(___H_repl_2d_server_23_ide_2d_repl_2d_pump,1,-1)
,___DEF_LBL_PROC(___H_repl_2d_server_23_ide_2d_repl_2d_pump,0,3)
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,8,0,0x3f0fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___OFD(___RETI,12,2,0x3f03fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___OFD(___RETI,12,2,0x3f004L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x7fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x7fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x7fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,1,4,0x3f0L))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_PROC(___H_repl_2d_server_23_ide_2d_repl_2d_pump,0,4)
,___DEF_LBL_RET(___H_repl_2d_server_23_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_INTRO(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,"repl-server#make-ide-repl-ports",
___REF_FAL,19,0)
,___DEF_LBL_PROC(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,2,-1)
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_PROC(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,2,2)
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_PROC(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,2,4)
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,8,0,0x3f0fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETN,5,0,0xbL))
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_PROC(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,1,-1)
,___DEF_LBL_PROC(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,1,-1)
,___DEF_LBL_PROC(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,0,-1)
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_PROC(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,0,-1)
,___DEF_LBL_RET(___H_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,"repl-server#setup-ide-repl-channel",
___REF_FAL,9,0)
,___DEF_LBL_PROC(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,2,-1)
,___DEF_LBL_RET(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_PROC(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,2,1)
,___DEF_LBL_RET(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,8,8,0x3f00L))
,___DEF_LBL_PROC(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,0,2)
,___DEF_LBL_RET(___H_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_repl_2d_server_23_repl_2d_server,"repl-server#repl-server",___REF_FAL,24,0)

,___DEF_LBL_PROC(___H_repl_2d_server_23_repl_2d_server,1,-1)
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_PROC(___H_repl_2d_server_23_repl_2d_server,0,3)
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_INTRO(___H_repl_2d_server_23_repl_2d_server_2d_start,"repl-server#repl-server-start",___REF_FAL,
8,0)
,___DEF_LBL_PROC(___H_repl_2d_server_23_repl_2d_server_2d_start,1,-1)
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server_2d_start,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server_2d_start,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server_2d_start,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server_2d_start,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server_2d_start,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_PROC(___H_repl_2d_server_23_repl_2d_server_2d_start,0,1)
,___DEF_LBL_RET(___H_repl_2d_server_23_repl_2d_server_2d_start,___IFD(___RETI,0,0,0x3fL))
___END_LBL

___BEGIN_OFD
 ___DEF_OFD(___RETI,12,1)
               ___GCMAP1(0x3f062L)
,___DEF_OFD(___RETI,12,2)
               ___GCMAP1(0x3f03fL)
,___DEF_OFD(___RETI,12,2)
               ___GCMAP1(0x3f004L)
___END_OFD

___BEGIN_MOD_PRM
___DEF_MOD_PRM(0,___G__20_repl_2d_server,1)
___DEF_MOD_PRM(2,___G_repl_2d_server_23_ide_2d_repl_2d_pump,12)
___DEF_MOD_PRM(3,___G_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,68)
___DEF_MOD_PRM(8,___G_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,88)
___DEF_MOD_PRM(5,___G_repl_2d_server_23_repl_2d_server,98)
___DEF_MOD_PRM(7,___G_repl_2d_server_23_repl_2d_server_2d_start,123)
___END_MOD_PRM

___BEGIN_MOD_C_INIT
___END_MOD_C_INIT

___BEGIN_MOD_GLO
___DEF_MOD_GLO(0,___G__20_repl_2d_server,1)
___DEF_MOD_GLO(2,___G_repl_2d_server_23_ide_2d_repl_2d_pump,12)
___DEF_MOD_GLO(3,___G_repl_2d_server_23_make_2d_ide_2d_repl_2d_ports,68)
___DEF_MOD_GLO(8,___G_repl_2d_server_23_setup_2d_ide_2d_repl_2d_channel,88)
___DEF_MOD_GLO(5,___G_repl_2d_server_23_repl_2d_server,98)
___DEF_MOD_GLO(7,___G_repl_2d_server_23_repl_2d_server_2d_start,123)
___END_MOD_GLO

___BEGIN_MOD_SYM_KEY
___DEF_MOD_SYM(0,___S_cr_2d_lf,"cr-lf")
___DEF_MOD_SYM(1,___S_input,"input")
___DEF_MOD_SYM(2,___S_normal,"normal")
___DEF_MOD_SYM(3,___S_output,"output")
___DEF_MOD_SYM(4,___S_repl,"repl")
___DEF_MOD_SYM(5,___S_repl_2d_pump,"repl-pump")
___DEF_MOD_SYM(6,___S_repl_2d_server,"repl-server")
___DEF_MOD_SYM(7,___S_repl_2d_service,"repl-service")
___DEF_MOD_SYM(8,___S_stdin,"stdin")
___DEF_MOD_SYM(9,___S_stdout,"stdout")
___DEF_MOD_KEY(0,___K_direction,"direction")
___DEF_MOD_KEY(1,___K_eol_2d_encoding,"eol-encoding")
___DEF_MOD_KEY(2,___K_permanent_2d_close,"permanent-close")
___DEF_MOD_KEY(3,___K_reuse_2d_address,"reuse-address")
___DEF_MOD_KEY(4,___K_server_2d_address,"server-address")
___DEF_MOD_KEY(5,___K_test,"test")
___END_MOD_SYM_KEY

#endif
