# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/9
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 9\#.scm
MODULES_SCM = 9.scm 9.sld test/test.scm
MAIN_MODULES = 9
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
