# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/boolean
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = boolean\#.scm
MODULES_SCM = boolean.scm boolean.sld
MAIN_MODULES = boolean
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
