# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/process-context
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = process-context.sld
MAIN_MODULES = process-context
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
