herefromlib = srfi/143
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 143\#.scm
MODULES_SCM = 143.scm 132.sld test/test.scm delndups.scm lmsort.scm merge.scm select.scm sort.scm sortp.scm vector-util.scm vhsort.scm visort.scm vmsort.scm vqsort2.scm vqsort3.scm vr7rs.scm
MAIN_MODULES = 143
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
