herefromlib = srfi/143
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 143\#.scm
MODULES_SCM = 143.scm 132.sld test/test.scm 
MAIN_MODULES = 143
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
