# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/parameter
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = parameter\#.scm
MODULES_SCM = parameter.scm parameter.sld
MAIN_MODULES = parameter
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
