# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/64
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 64\#.scm
MODULES_SCM = 64.scm 64.sld test/test.scm
MAIN_MODULES = 64
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
