# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/time
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = time.sld
MAIN_MODULES = time
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
