# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/60
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = 60.scm 60.sld test.scm
MAIN_MODULES = 60
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
