# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/procedure
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = procedure\#.scm
MODULES_SCM = procedure.scm procedure.sld
MAIN_MODULES = procedure
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
