# Copyright (c) 1994-2022 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/0
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 0\#.scm
MODULES_SCM = 0.scm 0.sld test/test.scm demo/demo.scm
MAIN_MODULES = 0
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
