# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/0
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 0\#.scm
MODULES_SCM = 0.scm 0.sld 0-test.scm
MAIN_MODULES = 0
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
