# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _test
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _test\#.scm
MODULES_SCM = _test.scm test.scm all.scm quiet.scm verbose.scm
MAIN_MODULES = _test all quiet verbose
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
