# Copyright (c) 1994-2023 by Marc Feeley, All Rights Reserved.

herefromlib = _test
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _test\#.scm test-expand\#.scm
MODULES_SCM = _test.scm _test.sld test-expand.scm test/test.scm all/all.scm quiet/quiet.scm verbose/verbose.scm
MAIN_MODULES = _test test-expand all quiet verbose
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
