# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/69
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 69\#.scm
MODULES_SCM = 69.scm 69.sld test.scm
MAIN_MODULES = 69
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
