# Copyright (c) 2020-2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/176
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 176\#.scm
MODULES_SCM = 176.scm 176.sld test.scm
MAIN_MODULES = 176
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
