herefromlib = srfi/144
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 144\#.scm
MODULES_SCM = 144.scm 132.sld test/test.scm 
MAIN_MODULES = 144
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
