# Copyright (c) 2019 by Frédéric Hamel, All Rights Reserved.
# Copyright (c) 2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/pkg
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = pkg\#.scm
MODULES_SCM = pkg.scm
MAIN_MODULES = pkg
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
