# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/zlib
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = zlib\#.scm
MODULES_SCM = zlib.scm
MAIN_MODULES = zlib
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
