# Copyright (c) 1994-2026 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/39
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 39\#.scm
MODULES_SCM = 39.scm 39.sld test/test.scm demo/demo.scm
MAIN_MODULES = 39
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
