# Copyright (c) 2020 by Bradley J. Lucier, All Rights Reserved.

herefromlib = srfi/179
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 179\#.scm
MODULES_SCM = 179.scm 179.sld generalized-arrays.scm test-arrays.scm girl.pgm test.pgm
MAIN_MODULES = 179
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
