(declare (extended-bindings) (not constant-fold) (not safe))

(define f (##not 123))
(define t (##not f))
(define s "")
(define x 1.5)
(define y (##s16vector 32767 -32768))
(define z (##list 1 2 3))

(define (test x)
  (println (##s16vector? x))
  (println (if (##s16vector? x) 11 22)))

(test 0)
(test 1)
(test f)
(test t)
(test s)
(test x)
(test y)
(test z)
(test (##cdr z))

(println (##s16vector-ref y 0))
(println (##s16vector-ref y 1))
(##s16vector-set! y 1 88)
(println (##s16vector-ref y 1))
