(include "#.scm")

(test-eq #f (port? #f))
(test-assert (output-port? (current-error-port)))
(test-assert
 (let ((p (open-input-string "a")))
   (let ((result (and (port? p) (input-port-open? p) (char-ready? p))))
     (close-port p)
     result)))
(test-assert
 (let ((p (open-output-string)))
   (let ((result (output-port-open? p))) (close-port p) result)))
(test-equal '((1 1 0) (1 2 1) (2 1 2) (2 2 3))
 (let ((p (open-input-string "a\nb")))
   (define (position)
     (list (input-port-line p) (input-port-column p) (input-port-char-position p)))
   (let* ((a (position))
          (unused1 (read-char p)) (b (position))
          (unused2 (read-char p)) (c (position))
          (unused3 (read-char p)) (d (position)))
     (close-port p)
     (list a b c d))))
(test-equal '(2 3 "a\nbc")
 (let ((p (open-output-string)))
   (display "a" p)
   (newline p)
   (display "bc" p)
   (flush-output-port p)
   (force-output p)
   (let ((result (list (output-port-line p) (output-port-column p)
                       (get-output-string p))))
     (close-port p)
     result)))
(test-eqv 80
 (let ((p (open-output-u8vector)))
   (let ((width (output-port-width p))) (close-port p) width)))
(test-assert
 (let* ((p (open-string))
        (rt (readtable-case-conversion?-set (current-readtable) #t)))
   (input-port-readtable-set! p rt)
   (output-port-readtable-set! p rt)
   (let ((result (and (eq? rt (input-port-readtable p))
                      (eq? rt (output-port-readtable p)))))
     (close-port p)
     result)))
(test-eq 'finished
 (let ((p (open-input-string "a")))
   (test-eq 'finished (call-with-port p (lambda (port) (read-char port) 'finished)))
   'finished))
(test-eqv 65
 (let ((p (open-input-u8vector #u8(65))))
   (input-port-timeout-set! p 0)
   (port-io-exception-handler-set! p (lambda (exception) (raise exception)))
   (test-eq #t (u8-ready? p))
   (let ((byte (read-u8 p))) (close-port p) byte)))
(test-eqv 42
 (let ((p (open-output-u8vector)))
   (output-port-timeout-set! p 0)
   (write-u8 42 p)
   (let ((byte (u8vector-ref (get-output-u8vector p) 0))) (close-port p) byte)))
(test-eq #t
 (let ((p (open-dummy)))
   (let ((result (and (port? p) (eof-object? (read p)))))
     (close-port p)
     result)))
(test-equal "(a 1)" (call-with-output-string (lambda (p) (write-simple '(a 1) p))))
(test-equal "(a 1)" (call-with-output-string (lambda (p) (write-shared '(a 1) p))))
(test-equal "(a 1)\n" (call-with-output-string (lambda (p) (pp '(a 1) p))))
(test-error type-exception? (output-port-width #f))
(test-error type-exception? (input-port-open? #f))
(test-error type-exception? (output-port-open? #f))

(test-equal #u8(233)
 (let ((p (open-output-u8vector)))
   (port-settings-set! p '(char-encoding: ISO-8859-1))
   (write-char #\xE9 p)
   (let ((result (get-output-u8vector p))) (close-port p) result)))
(test-assert
 (let ((p (open-input-u8vector #u8(97 98 99))))
   (peek-char p)
   (let ((result (and (> (input-port-characters-buffered p) 0)
                      (>= (input-port-bytes-buffered p) 0))))
     (close-port p)
     result)))
(test-eqv 42
 (let ((p (open-input-string "42")))
   (let ((result (with-input-from-port p (lambda () (read)))))
     (close-port p)
     result)))
(test-equal "42"
 (let ((p (open-output-string)))
   (with-output-to-port p (lambda () (write 42)))
   (let ((result (get-output-string p))) (close-port p) result)))

(let ((p (open-input-u8vector #u8(97 98 99))))
  (dynamic-wind
   (lambda () #f)
   (lambda ()
     (peek-char p)
     (let ((e (with-exception-catcher (lambda (e) e)
               (lambda () (port-settings-set! p '(char-encoding: ISO-8859-1))))))
       (test-eq #t (nonempty-input-port-character-buffer-exception? e))
       (test-eq #f (nonempty-input-port-character-buffer-exception? #f))
       (test-eq port-settings-set! (nonempty-input-port-character-buffer-exception-procedure e))
       (test-equal (list p '(char-encoding: ISO-8859-1))
        (nonempty-input-port-character-buffer-exception-arguments e))))
   (lambda () (close-port p))))
