(include "#.scm")

(define p (open-input-string "a\nb"))
(test-eq 1 (input-port-line p))
(test-eq 1 (input-port-column p))
(test-eq #\a (read-char p))
(test-eq 2 (input-port-column p))
(test-eq #\newline (read-char p))
(test-eq 2 (input-port-line p))
(test-eq 1 (input-port-column p))
(close-port p)

(define o (open-output-string))
(test-eq 1 (output-port-line o))
(test-eq 1 (output-port-column o))
(display "x" o)
(test-eq 2 (output-port-column o))
(newline o)
(test-eq 2 (output-port-line o))
(close-port o)

(test-error-tail type-exception? (input-port-line 1))
(test-error-tail type-exception? (output-port-column 1))
(test-error-tail wrong-number-of-arguments-exception? (input-port-line))
(test-error-tail wrong-number-of-arguments-exception? (output-port-line))
