(include "#.scm")

(test-eqv 6 (six.x*y 2 3))
(test-eqv 2 (six.x/y 6 3))
(test-eqv 3 (six.x%y 7 4))
(test-eqv 3 (six.x//y 7 2))
(test-eqv 3 (six.x+y 1 2))
(test-eqv 2 (six.x-y 5 3))
(test-eq #t (six.x==y 1 1))
(test-eq #t (six.x!=y 1 2))
(test-eq #t (six.x<y 1 2))
(test-eq #t (six.x>y 2 1))
(test-eq #t (six.x<=y 1 1))
(test-eq #t (six.x>=y 2 1))
(test-eqv 2 (six.x&&y 1 2))
(test-eqv 1 (six.x&y 3 1))
(test-eqv 2 (six.x^y 3 1))
(test-eqv 8 (six.x<<y 1 3))
(test-eqv 2 (six.x>>y 8 2))
(test-eqv 2 (six.x>>>y 8 2))
(test-eqv 8 (six.x**y 2 3))
(test-eqv 3 (six.+x 3))
(test-eqv -3 (six.-x 3))
(test-eq #f (six.!x 0))
(test-eq #t (six.notx #f))
(test-eqv -1 (six.~x 0))
(test-eq #t (six.x===y 1 1))
(test-eq #t (six.x!==y 1 2))
(test-eqv 1 (six.x?y:z #t 1 2))
(test-eqv 3 (|six.x\|y| 1 2))
(test-eqv 0 (|six.x\|\|y| 0 2))
(test-equal '(1 . 2) (six.cons 1 2))
(test-equal '() (six.null))
(test-equal '(1 . 2) (six.list 1 2))
(test-equal '#(2 2 2) (six.make-array 2 3))
(test-eqv 2 (six.xandy 1 2))
(test-eqv 3 (six.xory #f 3))
(test-eq #t (six.xisy 1 1))
(test-equal '(1 2) (six.xiny 1 '(1 2)))
(test-eqv 5 (six.literal 5))
(test-eqv 2 (let ((a 1)) (six.++x a) a))
(test-equal '(1 2) (let ((a 1)) (let ((r (six.x++ a))) (list r a))))
(test-eqv 1 (let ((a 2)) (six.--x a) a))
(test-equal '(2 1) (let ((a 2)) (let ((r (six.x-- a))) (list r a))))
(test-eqv 3 (let ((a 1)) (six.x+=y a 2) a))
(test-eqv 7 (let ((a 0)) (six.x=y a 7) a))
(test-eqv 12 (let ((a 3)) (six.x*=y a 4) a))
(test-eqv 3 (let ((a 5)) (six.x-=y a 2) a))
(test-eqv 4 (let ((a 8)) (six.x/=y a 2) a))
(test-eqv 3 (let ((a 7)) (six.x%=y a 4) a))
(test-eqv 1 (let ((a 3)) (six.x&=y a 1) a))
(test-eqv 2 (let ((a 3)) (six.x^=y a 1) a))
(test-eqv 8 (let ((a 1)) (six.x<<=y a 3) a))
(test-eqv 2 (let ((a 8)) (six.x>>=y a 2) a))
(test-eqv 8 (let ((a 2)) (six.x**=y a 3) a))
(test-eqv 3 (let ((a 7)) (six.x//=y a 2) a))
(test-eqv 3 (let ((a 1)) (|six.x\|=y| a 2) a))
(test-eqv 9 (let ((a 0)) (six.x:=y a 9) a))
(test-eqv 2 (|six.x,y| 1 2))
(test-equal '(1 . 2) (six.x:y 1 2))

