# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/promise
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = promise\#.scm
MODULES_SCM = promise.scm promise.sld
MAIN_MODULES = promise
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
