# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/file
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = file.sld
MAIN_MODULES = file
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
