# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/geiser
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = geiser\#.scm
MODULES_SCM = geiser.scm
MAIN_MODULES = geiser
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
