# Copyright (c) 1994-2023 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/132
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 132\#.scm
MODULES_SCM = 132.scm 132.sld test/test.scm delndups.scm lmsort.scm merge.scm select.scm sort.scm sortp.scm vector-util.scm vhsort.scm visort.scm vmsort.scm vqsort2.scm vqsort3.scm vr7rs.scm
MAIN_MODULES = 132
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
