# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/132
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 132\#.scm
MODULES_SCM = 132.scm
MAIN_MODULES = 132
OTHER_RCFILES = makefile 132-test.scm

include $(libfromhere)/module-common.mk
