# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/132
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 132\#.scm
MODULES_SCM = 132.scm 132.sld 132-test.scm delndups.scm  lmsort.scm  makefile  merge.scm  select.scm  vhsort.scm  visort.scm  vmsort.scm  vqsort2.scm  vqsort3.scm
MAIN_MODULES = 132
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
