# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/4
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 4\#.scm
MODULES_SCM = 4.scm 4.sld 4-test.scm
MAIN_MODULES = 4
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
