# Copyright (c) 2021 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/5
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 5\#.scm
MODULES_SCM = 5.scm 5.sld test/test.scm
MAIN_MODULES = 5
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
