#! /bin/sh

# Copyright (c) 1994-2007 by Marc Feeley, All Rights Reserved.

herefromroot="prebuilt/macosx"
rootfromhere="../.."

if [ "`id -un`" != "root" ] ; then
  echo "You must execute this script as root!"
  echo "Try executing the command:"
  echo "  sudo $0"
  exit 1
fi

export INSTALL_PREFIX="/Library/Gambit-C"

cd "`dirname $0`"

for VARIANT in intel powerpc universal; do

  cd "$rootfromhere"

  case "$VARIANT" in
        intel) CONFIG_ARCH="-arch i386";;
      powerpc) CONFIG_ARCH="-arch ppc";;
    universal) CONFIG_ARCH="-arch i386 -arch ppc";;
  esac

  CFLAGS="$CONFIG_ARCH" LDFLAGS="$CONFIG_ARCH" ./configure --prefix="$INSTALL_PREFIX" --enable-single-host # --enable-gcc-opts

  cd "$herefromroot"

  chmod +x build-phase2

  ./build-phase2 "$VARIANT" > build-phase2.out

  cat build-phase2.out

  if fgrep "============ ALL TESTS SUCCESSFUL" build-phase2.out > /dev/null; then
    rm -f build-phase2.out
    echo "============ $VARIANT BUILD SUCCESSFUL"
  else
    rm -f build-phase2.out
    echo "============ $VARIANT BUILD FAILED"
    exit 1
  fi

done

echo "============ BUILD SUCCESSFUL"
