# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = scheme/complex
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = complex.sld
MAIN_MODULES = complex
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
