# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = srfi/158
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 158\#.scm
MODULES_SCM = 158.scm 158.sld test/test.scm
MAIN_MODULES = 158
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
