# Copyright (c) 2005-2022 by Marc Feeley, All Rights Reserved.

herefromlib = _base64
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _base64\#.scm
MODULES_SCM = _base64.scm test/test.scm
MAIN_MODULES = _base64
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
