# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = termite/otp
libfromhere = ../..
SUBDIRS =
HEADERS_SCM =
MODULES_SCM = gen_event.scm gen_server.scm
MAIN_MODULES =
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
