# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/string
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = string\#.scm
MODULES_SCM = string.scm string.sld
MAIN_MODULES = string
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
