# Copyright (c) 1994-2021 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/env-vars
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = env-vars\#.scm
MODULES_SCM = env-vars.scm env-vars.sld
MAIN_MODULES = env-vars
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
