# Copyright (c) 1994-2021 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/unstable
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = unstable\#.scm
MODULES_SCM = unstable.scm unstable.sld
MAIN_MODULES = unstable
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
