(declare (extended-bindings) (not constant-fold) (not safe))

(define a 0)
(define b 536870911)
(define c -536870912)
(define d 1)
(define e -1)
(define f 357913941)

(define (test x)
  (println (##fxior x a))
  (println (##fxior x b))
  (println (##fxior x c))
  (println (##fxior x d))
  (println (##fxior x e))
  (println (##fxior x f)))

(test a)
(test b)
(test c)
(test d)
(test e)
(test f)
