(declare (extended-bindings) (not constant-fold) (not safe))

(println (##fxmodulo 500000000 1))
(println (##fxmodulo 500000000 -1))
(println (##fxmodulo -500000000 1))
(println (##fxmodulo -500000000 -1))

(println (##fxmodulo 6 2))
(println (##fxmodulo 5 2))
(println (##fxmodulo 4 2))
(println (##fxmodulo 3 2))
(println (##fxmodulo 2 2))
(println (##fxmodulo 1 2))
(println (##fxmodulo 0 2))
(println (##fxmodulo -1 2))
(println (##fxmodulo -2 2))
(println (##fxmodulo -3 2))
(println (##fxmodulo -4 2))
(println (##fxmodulo -5 2))
(println (##fxmodulo -6 2))

(println (##fxmodulo 6 -2))
(println (##fxmodulo 5 -2))
(println (##fxmodulo 4 -2))
(println (##fxmodulo 3 -2))
(println (##fxmodulo 2 -2))
(println (##fxmodulo 1 -2))
(println (##fxmodulo 0 -2))
(println (##fxmodulo -1 -2))
(println (##fxmodulo -2 -2))
(println (##fxmodulo -3 -2))
(println (##fxmodulo -4 -2))
(println (##fxmodulo -5 -2))
(println (##fxmodulo -6 -2))

(println (##fxmodulo 6 3))
(println (##fxmodulo 5 3))
(println (##fxmodulo 4 3))
(println (##fxmodulo 3 3))
(println (##fxmodulo 2 3))
(println (##fxmodulo 1 3))
(println (##fxmodulo 0 3))
(println (##fxmodulo -1 3))
(println (##fxmodulo -2 3))
(println (##fxmodulo -3 3))
(println (##fxmodulo -4 3))
(println (##fxmodulo -5 3))
(println (##fxmodulo -6 3))

(println (##fxmodulo 6 -3))
(println (##fxmodulo 5 -3))
(println (##fxmodulo 4 -3))
(println (##fxmodulo 3 -3))
(println (##fxmodulo 2 -3))
(println (##fxmodulo 1 -3))
(println (##fxmodulo 0 -3))
(println (##fxmodulo -1 -3))
(println (##fxmodulo -2 -3))
(println (##fxmodulo -3 -3))
(println (##fxmodulo -4 -3))
(println (##fxmodulo -5 -3))
(println (##fxmodulo -6 -3))
