(declare (extended-bindings) (not constant-fold) (not safe))

(println (##fxquotient 500000000 1))
(println (##fxquotient 500000000 -1))
(println (##fxquotient -500000000 1))
(println (##fxquotient -500000000 -1))

(println (##fxquotient 6 2))
(println (##fxquotient 5 2))
(println (##fxquotient 4 2))
(println (##fxquotient 3 2))
(println (##fxquotient 2 2))
(println (##fxquotient 1 2))
(println (##fxquotient 0 2))
(println (##fxquotient -1 2))
(println (##fxquotient -2 2))
(println (##fxquotient -3 2))
(println (##fxquotient -4 2))
(println (##fxquotient -5 2))
(println (##fxquotient -6 2))

(println (##fxquotient 6 -2))
(println (##fxquotient 5 -2))
(println (##fxquotient 4 -2))
(println (##fxquotient 3 -2))
(println (##fxquotient 2 -2))
(println (##fxquotient 1 -2))
(println (##fxquotient 0 -2))
(println (##fxquotient -1 -2))
(println (##fxquotient -2 -2))
(println (##fxquotient -3 -2))
(println (##fxquotient -4 -2))
(println (##fxquotient -5 -2))
(println (##fxquotient -6 -2))

(println (##fxquotient 6 3))
(println (##fxquotient 5 3))
(println (##fxquotient 4 3))
(println (##fxquotient 3 3))
(println (##fxquotient 2 3))
(println (##fxquotient 1 3))
(println (##fxquotient 0 3))
(println (##fxquotient -1 3))
(println (##fxquotient -2 3))
(println (##fxquotient -3 3))
(println (##fxquotient -4 3))
(println (##fxquotient -5 3))
(println (##fxquotient -6 3))

(println (##fxquotient 6 -3))
(println (##fxquotient 5 -3))
(println (##fxquotient 4 -3))
(println (##fxquotient 3 -3))
(println (##fxquotient 2 -3))
(println (##fxquotient 1 -3))
(println (##fxquotient 0 -3))
(println (##fxquotient -1 -3))
(println (##fxquotient -2 -3))
(println (##fxquotient -3 -3))
(println (##fxquotient -4 -3))
(println (##fxquotient -5 -3))
(println (##fxquotient -6 -3))
