(declare (extended-bindings) (not constant-fold) (not safe))

(println (##fxremainder 500000000 1))
(println (##fxremainder 500000000 -1))
(println (##fxremainder -500000000 1))
(println (##fxremainder -500000000 -1))

(println (##fxremainder 6 2))
(println (##fxremainder 5 2))
(println (##fxremainder 4 2))
(println (##fxremainder 3 2))
(println (##fxremainder 2 2))
(println (##fxremainder 1 2))
(println (##fxremainder 0 2))
(println 111111111)
(println (##fxremainder -1 2))
(println 222222222)
(println (##fxremainder -2 2))
(println 333333333)
(println (##fxremainder -3 2))
(println (##fxremainder -4 2))
(println (##fxremainder -5 2))
(println (##fxremainder -6 2))

(println (##fxremainder 6 -2))
(println (##fxremainder 5 -2))
(println (##fxremainder 4 -2))
(println (##fxremainder 3 -2))
(println (##fxremainder 2 -2))
(println (##fxremainder 1 -2))
(println (##fxremainder 0 -2))
(println (##fxremainder -1 -2))
(println (##fxremainder -2 -2))
(println (##fxremainder -3 -2))
(println (##fxremainder -4 -2))
(println (##fxremainder -5 -2))
(println (##fxremainder -6 -2))

(println (##fxremainder 6 3))
(println (##fxremainder 5 3))
(println (##fxremainder 4 3))
(println (##fxremainder 3 3))
(println (##fxremainder 2 3))
(println (##fxremainder 1 3))
(println (##fxremainder 0 3))
(println (##fxremainder -1 3))
(println (##fxremainder -2 3))
(println (##fxremainder -3 3))
(println (##fxremainder -4 3))
(println (##fxremainder -5 3))
(println (##fxremainder -6 3))

(println (##fxremainder 6 -3))
(println (##fxremainder 5 -3))
(println (##fxremainder 4 -3))
(println (##fxremainder 3 -3))
(println (##fxremainder 2 -3))
(println (##fxremainder 1 -3))
(println (##fxremainder 0 -3))
(println (##fxremainder -1 -3))
(println (##fxremainder -2 -3))
(println (##fxremainder -3 -3))
(println (##fxremainder -4 -3))
(println (##fxremainder -5 -3))
(println (##fxremainder -6 -3))
