(declare (extended-bindings) (not constant-fold) (not safe))

(println (##fxwrapquotient 500000000 1))
(println (##fxwrapquotient 500000000 -1))
(println (##fxwrapquotient -500000000 1))
(println (##fxwrapquotient -500000000 -1))

(println (##fxwrapquotient 6 2))
(println (##fxwrapquotient 5 2))
(println (##fxwrapquotient 4 2))
(println (##fxwrapquotient 3 2))
(println (##fxwrapquotient 2 2))
(println (##fxwrapquotient 1 2))
(println (##fxwrapquotient 0 2))
(println (##fxwrapquotient -1 2))
(println (##fxwrapquotient -2 2))
(println (##fxwrapquotient -3 2))
(println (##fxwrapquotient -4 2))
(println (##fxwrapquotient -5 2))
(println (##fxwrapquotient -6 2))

(println (##fxwrapquotient 6 -2))
(println (##fxwrapquotient 5 -2))
(println (##fxwrapquotient 4 -2))
(println (##fxwrapquotient 3 -2))
(println (##fxwrapquotient 2 -2))
(println (##fxwrapquotient 1 -2))
(println (##fxwrapquotient 0 -2))
(println (##fxwrapquotient -1 -2))
(println (##fxwrapquotient -2 -2))
(println (##fxwrapquotient -3 -2))
(println (##fxwrapquotient -4 -2))
(println (##fxwrapquotient -5 -2))
(println (##fxwrapquotient -6 -2))

(println (##fxwrapquotient 6 3))
(println (##fxwrapquotient 5 3))
(println (##fxwrapquotient 4 3))
(println (##fxwrapquotient 3 3))
(println (##fxwrapquotient 2 3))
(println (##fxwrapquotient 1 3))
(println (##fxwrapquotient 0 3))
(println (##fxwrapquotient -1 3))
(println (##fxwrapquotient -2 3))
(println (##fxwrapquotient -3 3))
(println (##fxwrapquotient -4 3))
(println (##fxwrapquotient -5 3))
(println (##fxwrapquotient -6 3))

(println (##fxwrapquotient 6 -3))
(println (##fxwrapquotient 5 -3))
(println (##fxwrapquotient 4 -3))
(println (##fxwrapquotient 3 -3))
(println (##fxwrapquotient 2 -3))
(println (##fxwrapquotient 1 -3))
(println (##fxwrapquotient 0 -3))
(println (##fxwrapquotient -1 -3))
(println (##fxwrapquotient -2 -3))
(println (##fxwrapquotient -3 -3))
(println (##fxwrapquotient -4 -3))
(println (##fxwrapquotient -5 -3))
(println (##fxwrapquotient -6 -3))
