# Copyright (c) 2024 by Marc Feeley, All Rights Reserved.

herefromlib = _json
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _json\#.scm
MODULES_SCM = _json.scm _json.sld test/test.scm
MAIN_MODULES = _json
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
