# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/test
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = test\#.scm
MODULES_SCM = test.scm test-test.scm
MAIN_MODULES = test
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
