# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = _zlib
libfromhere = ..
SUBDIRS =
HEADERS_SCM = _zlib\#.scm
MODULES_SCM = _zlib.scm test.scm
MAIN_MODULES = _zlib
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
