# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/symkey
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = symkey\#.scm
MODULES_SCM = symkey.scm symkey.sld
MAIN_MODULES = symkey
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
