(include "#.scm")

(test-eqv 1. (##fldenominator 0.))
(test-eqv 1. (##fldenominator -0.))
(test-eqv 2. (##fldenominator .5))
(test-eqv 1. (##fldenominator 1.))
(test-eqv 2. (##fldenominator 1.5))
(test-eqv 2. (##fldenominator 3.5))
(test-eqv 1. (##fldenominator 5.))

(test-eqv 1. (fldenominator 0.))
(test-eqv 1. (fldenominator -0.))
(test-eqv 2. (fldenominator .5))
(test-eqv 1. (fldenominator 1.))
(test-eqv 2. (fldenominator 1.5))
(test-eqv 2. (fldenominator 3.5))
(test-eqv 1. (fldenominator 5.))

(test-error-tail wrong-number-of-arguments-exception? (fldenominator))
(test-error-tail wrong-number-of-arguments-exception? (fldenominator 1. 2.))

(test-error-tail type-exception? (fldenominator 1))
(test-error-tail type-exception? (fldenominator 1/2))
(test-error-tail type-exception? (fldenominator -inf.0))
(test-error-tail type-exception? (fldenominator +inf.0))
