(include "#.scm")

(test-eqv 1.0 (##fldenominator  0.0))
(test-eqv 1.0 (##fldenominator -0.0))
(test-eqv 2.0 (##fldenominator  0.5))
(test-eqv 1.0 (##fldenominator  1.0))
(test-eqv 2.0 (##fldenominator  1.5))
(test-eqv 2.0 (##fldenominator  3.5))
(test-eqv 1.0 (##fldenominator  5.0))

(test-eqv 1.0 (fldenominator  0.0))
(test-eqv 1.0 (fldenominator -0.0))
(test-eqv 2.0 (fldenominator  0.5))
(test-eqv 1.0 (fldenominator  1.0))
(test-eqv 2.0 (fldenominator  1.5))
(test-eqv 2.0 (fldenominator  3.5))
(test-eqv 1.0 (fldenominator  5.0))

(test-error-tail wrong-number-of-arguments-exception? (fldenominator))
(test-error-tail wrong-number-of-arguments-exception? (fldenominator 1.0 2.0))

(test-error-tail type-exception? (fldenominator 1))
(test-error-tail type-exception? (fldenominator 1/2))
(test-error-tail type-exception? (fldenominator -inf.0))
(test-error-tail type-exception? (fldenominator +inf.0))
