(include "#.scm")

(test-eqv #f (##fl= +inf.0 -inf.0))
(test-eqv #t (##fl= -0. 0.))
(test-eqv #t (##fl= 0.))
(test-eqv #f (##fl= 0. 1.5))
(test-eqv #f (##fl= 2. -1.5 .5))
(test-eqv #f (##fl= -1. 1. 1.))
(test-eqv #t (##fl= 1. 1. 1.))

(test-eqv #f (fl= +inf.0 -inf.0))
(test-eqv #t (fl= -0. 0.))
(test-eqv #t (fl= 0.))
(test-eqv #f (fl= 0. 1.5))
(test-eqv #f (fl= 2. -1.5 .5))
(test-eqv #f (fl= -1. 1. 1.))
(test-eqv #t (fl= 1. 1. 1.))

(test-error-tail type-exception? (fl= 1 1.))
(test-error-tail type-exception? (fl= 1. 1))
(test-error-tail type-exception? (fl= 1. 1. 1))
(test-error-tail type-exception? (fl= 1/2))
