(include "#.scm")

(test-eqv #f (##fleven? +inf.0))
(test-eqv #f (##fleven? -inf.0))
(test-eqv #t (##fleven? -0.0))
(test-eqv #t (##fleven? 0.0))
(test-eqv #f (##fleven? 1.5))
(test-eqv #f (##fleven? -1.5))
(test-eqv #t (##fleven? 2.0))
(test-eqv #t (##fleven? -2.0))
(test-eqv #f (##fleven? 3.0))
(test-eqv #f (##fleven? -3.0))

(test-eqv #t (fleven? -0.0))
(test-eqv #t (fleven? 0.0))
(test-eqv #t (fleven? 2.0))
(test-eqv #t (fleven? -2.0))
(test-eqv #f (fleven? 3.0))
(test-eqv #f (fleven? -3.0))

(test-error-tail wrong-number-of-arguments-exception? (fleven?))
(test-error-tail wrong-number-of-arguments-exception? (fleven? 1.0 2.0))

(test-error-tail type-exception? (fleven? 1))
(test-error-tail type-exception? (fleven? 1/2))
(test-error-tail type-exception? (fleven? +inf.0))
(test-error-tail type-exception? (fleven? -inf.0))
(test-error-tail type-exception? (fleven? +nan.0))
(test-error-tail type-exception? (fleven? 1.5))
(test-error-tail type-exception? (fleven? -1.5))
