(include "#.scm")

(test-eqv #f (##flodd? +inf.0))
(test-eqv #f (##flodd? -inf.0))
(test-eqv #f (##flodd? -0.))
(test-eqv #f (##flodd? 0.))
(test-eqv #f (##flodd? 1.5))
(test-eqv #f (##flodd? -1.5))
(test-eqv #f (##flodd? 2.))
(test-eqv #f (##flodd? -2.))
(test-eqv #t (##flodd? 3.))
(test-eqv #t (##flodd? -3.))

(test-eqv #f (flodd? -0.))
(test-eqv #f (flodd? 0.))
(test-eqv #f (flodd? 2.))
(test-eqv #f (flodd? -2.))
(test-eqv #t (flodd? 3.))
(test-eqv #t (flodd? -3.))

(test-error-tail wrong-number-of-arguments-exception? (flodd?))
(test-error-tail wrong-number-of-arguments-exception? (flodd? 1. 2.))

(test-error-tail type-exception? (flodd? 1))
(test-error-tail type-exception? (flodd? 1/2))
(test-error-tail type-exception? (flodd? +inf.0))
(test-error-tail type-exception? (flodd? -inf.0))
(test-error-tail type-exception? (flodd? +nan.0))
(test-error-tail type-exception? (flodd? 1.5))
(test-error-tail type-exception? (flodd? -1.5))
