(include "#.scm")

(test-eqv +inf.0 (##fltruncate +inf.0))
(test-eqv -inf.0 (##fltruncate -inf.0))
(test-eqv -0. (##fltruncate -0.))
(test-eqv 0. (##fltruncate 0.))
(test-eqv 1. (##fltruncate 1.5))
(test-eqv -1. (##fltruncate -1.5))
(test-eqv 2. (##fltruncate 2.12))
(test-eqv -2. (##fltruncate -2.12))
(test-eqv 3. (##fltruncate 3.123))
(test-eqv -3. (##fltruncate -3.123))

(test-eqv +inf.0 (fltruncate +inf.0))
(test-eqv -inf.0 (fltruncate -inf.0))
(test-eqv -0. (fltruncate -0.))
(test-eqv 0. (fltruncate 0.))
(test-eqv 1. (fltruncate 1.5))
(test-eqv -1. (fltruncate -1.5))
(test-eqv 2. (fltruncate 2.12))
(test-eqv -2. (fltruncate -2.12))
(test-eqv 3. (fltruncate 3.123))
(test-eqv -3. (fltruncate -3.123))

(test-error-tail wrong-number-of-arguments-exception? (fltruncate))
(test-error-tail wrong-number-of-arguments-exception? (fltruncate 1. 2.))

(test-error-tail type-exception? (fltruncate 1))
(test-error-tail type-exception? (fltruncate 1/2))
