(include "#.scm")

(test-eqv +inf.0 (##fltruncate +inf.0))
(test-eqv -inf.0 (##fltruncate -inf.0))
(test-eqv -0.0   (##fltruncate -0.0))
(test-eqv  0.0   (##fltruncate 0.0))
(test-eqv  1.0   (##fltruncate 1.5))
(test-eqv -1.0   (##fltruncate -1.5))
(test-eqv  2.0   (##fltruncate 2.12))
(test-eqv -2.0   (##fltruncate -2.12))
(test-eqv  3.0   (##fltruncate 3.123))
(test-eqv -3.0   (##fltruncate -3.123))

(test-eqv +inf.0 (fltruncate +inf.0))
(test-eqv -inf.0 (fltruncate -inf.0))
(test-eqv -0.0   (fltruncate -0.0))
(test-eqv  0.0   (fltruncate 0.0))
(test-eqv  1.0   (fltruncate 1.5))
(test-eqv -1.0   (fltruncate -1.5))
(test-eqv  2.0   (fltruncate 2.12))
(test-eqv -2.0   (fltruncate -2.12))
(test-eqv  3.0   (fltruncate 3.123))
(test-eqv -3.0   (fltruncate -3.123))

(test-error-tail wrong-number-of-arguments-exception? (fltruncate))
(test-error-tail wrong-number-of-arguments-exception? (fltruncate 1.0 2.0))

(test-error-tail type-exception? (fltruncate 1))
(test-error-tail type-exception? (fltruncate 1/2))
