(include "#.scm")

(test-eq #t (exact? 1))
(test-eq #f (exact? 1.))
(test-eq #t (inexact? 1.))
(test-eq #f (inexact? 1))
(test-eq #t (rational? 2/3))
(test-eq #f (rational? 1+2i))
(test-eq #t (real? 1.))
(test-eq #f (real? 1+2i))
(test-eq #t (positive? 1))
(test-eq #f (positive? -1))
(test-eq #t (negative? -1))
(test-eq #f (negative? 1))
(test-eq #t (zero? 0))
(test-eq #f (zero? 1))
(test-error-tail type-exception? (exact? 'a))
(test-error-tail type-exception? (inexact? 'a))
(test-error-tail wrong-number-of-arguments-exception? (exact?))
(test-error-tail wrong-number-of-arguments-exception? (zero? 0 1))
