(include "#.scm")

(test-eq #t (>= 3 3 2))
(test-eq #f (>= 3 3 4))
(test-eq #t (complex? 1+2i))
(test-eq #t (complex? 1))
(test-eq #f (complex? 'one))
(test-eq #t (inexact? 1.0))
(test-eq #f (inexact? 1/2))
(test-eqv -3 (min 4 -3 2))
(test-eqv 4 (min 4))
(test-eqv 3 (numerator 3/4))
(test-eqv -3 (numerator -6/8))
(test-eqv -2 (floor -3/2))
(test-eqv -1 (ceiling -3/2))
(test-eqv -1 (truncate -3/2))
(test-eqv 2 (floor 5/2))
(test-eqv 3 (ceiling 5/2))
(test-eqv 2 (truncate 5/2))
(test-eqv 2 (round 5/2))
(test-eqv 4 (round 7/2))
(test-eqv -2 (round -5/2))
(test-eqv -4 (round -7/2))
(test-eqv 1/3 (rationalize 3/10 1/10))
(test-eqv 3/10 (rationalize 3/10 0))
(test-eqv 0 (rationalize 0 1/10))
(test-eqv -21 (replace-bit-field 5 2 -6 -37))
(test-eqv 37 (replace-bit-field 0 2 -6 37))
(test-eqv 15 (replace-bit-field 4 0 -1 0))
(test-error type-exception? (floor #f))
(test-error type-exception? (ceiling 1+2i))
(test-error type-exception? (truncate #f))
(test-error type-exception? (round #f))
(test-error type-exception? (replace-bit-field -1 0 1 0))
