# Copyright (c) 1994-2021 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/process
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = process\#.scm
MODULES_SCM = process.scm process.sld
MAIN_MODULES = process
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
