herefromlib = srfi/2
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 2\#.scm expand\#.scm syntax-utils\#.scm
MODULES_SCM = 2.scm expand.scm syntax-utils.scm test/test.scm
MAIN_MODULES = 2 expand syntax-utils
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
