herefromlib = srfi/2
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = 2\#.scm
MODULES_SCM = 2.scm expand-and-let.scm syntax-utils.scm
MAIN_MODULES = 2
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
