# Copyright (c) 1994-2019 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/hamt/primitive-hamt
libfromhere = ../../..
SUBDIRS =
HEADERS_SCM = primitive-hamt\#.scm
MODULES_SCM = primitive-hamt.scm
MAIN_MODULES = primitive-hamt

include $(libfromhere)/module-common.mk
