# Copyright (c) 1994-2020 by Marc Feeley, All Rights Reserved.

herefromlib = gambit/vector
libfromhere = ../..
SUBDIRS =
HEADERS_SCM = vector\#.scm
MODULES_SCM = vector.scm vector.sld
MAIN_MODULES = vector
OTHER_RCFILES = makefile

include $(libfromhere)/module-common.mk
